"use client";
import {useState} from "react";
import Link from "next/link";
import {useLocale,useTranslations} from "next-intl";
import {calculateCapexPlan,capexPlanCsv,type CapexPlan} from "@/lib/hotellerie/capex-plan";
type Draft={year:string;spending:string;funding:string;reference:string};
export default function CapexPage(){
 const t=useTranslations("capexPlan"),locale=useLocale(),prefix=locale==="fr"?"":`/${locale}`;
 const [opening,setOpening]=useState(""),[openingReference,setOpeningReference]=useState(""),[years,setYears]=useState<Draft[]>([{year:"",spending:"",funding:"",reference:""}]);
 const number=(s:string)=>s.trim()?Number(s):NaN;
 const input:CapexPlan={opening:number(opening),openingReference,years:years.map(y=>({...y,year:number(y.year),spending:number(y.spending),funding:number(y.funding)}))};
 let result:ReturnType<typeof calculateCapexPlan>|null=null;try{result=calculateCapexPlan(input)}catch{}
 const fmt=(n:number)=>n.toLocaleString(locale==="lb"?"de-DE":locale,{minimumFractionDigits:2,maximumFractionDigits:2});
 const save=()=>{const url=URL.createObjectURL(new Blob([capexPlanCsv(input)],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="hotel-capex-plan.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <div className="mx-auto max-w-6xl px-4 py-10"><Link className="text-sm underline" href={`${prefix}/hotellerie`}>{t("back")}</Link><h1 className="mt-3 text-2xl font-bold">{t("title")}</h1><p className="mt-3 text-sm">{t("scope")}</p>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><label htmlFor="capex-opening" className="min-w-0 text-sm">{t("opening")}<input id="capex-opening" type="number" min="0" step="0.01" value={opening} onChange={e=>setOpening(e.target.value)} className="mt-1 block w-full min-w-0 rounded border p-2" /></label><label htmlFor="capex-opening-reference" className="min-w-0 text-sm">{t("openingReference")}<input id="capex-opening-reference" maxLength={1500} value={openingReference} onChange={e=>setOpeningReference(e.target.value)} className="mt-1 block w-full min-w-0 rounded border p-2" /></label></div>
 <div className="mt-5 space-y-4">{years.map((row,i)=><fieldset key={i} data-capex-year={i} className="min-w-0 rounded-lg border p-4"><legend className="px-2 font-semibold">{t("annual")} {i+1}</legend><div className="grid gap-4 sm:grid-cols-3">{(["year","spending","funding"] as const).map(k=><label key={k} htmlFor={`capex-${i}-${k}`} className="min-w-0 text-sm">{t(k)}<input id={`capex-${i}-${k}`} data-field={k} type="number" step={k==="year"?"1":"0.01"} value={row[k]} onChange={e=>setYears(v=>v.map((y,j)=>j===i?{...y,[k]:e.target.value}:y))} className="mt-1 block w-full min-w-0 rounded border p-2" /></label>)}</div><label htmlFor={`capex-${i}-reference`} className="mt-3 block text-sm">{t("reference")}<textarea id={`capex-${i}-reference`} data-field="reference" value={row.reference} maxLength={1500} onChange={e=>setYears(v=>v.map((y,j)=>j===i?{...y,reference:e.target.value}:y))} className="mt-1 block w-full rounded border p-2" /></label><button disabled={years.length===1} onClick={()=>setYears(v=>v.filter((_,j)=>j!==i))} className="mt-3 text-sm underline disabled:opacity-40">{t("remove")}</button></fieldset>)}</div>
 <button id="capex-add" disabled={years.length>=30} onClick={()=>setYears(v=>[...v,{year:v.at(-1)?.year?String(Number(v.at(-1)!.year)+1):"",spending:"",funding:"",reference:""}])} className="mt-4 rounded border px-4 py-2 disabled:opacity-40">{t("add")}</button>
 <p className="mt-5 text-sm">{t("timing")}</p>
 {!result?<p role="status" className="mt-5 rounded border p-4 text-sm">{t("invalid")}</p>:<section className="mt-6"><h2 className="text-xl font-semibold">{t("results")}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{(["totalSpending","totalFunding","closing","additionalFunding"] as const).map(k=><div key={k} className="min-w-0 rounded border p-4"><h3 className="text-sm">{t(k)}</h3><p data-capex-result={k} className="mt-2 break-words text-xl font-semibold">{fmt(result![k])} €</p></div>)}</div><div className="mt-4 overflow-x-auto rounded border" role="region" aria-label={t("results")} tabIndex={0}><table className="w-full min-w-[700px] text-sm"><thead><tr>{["year","opening","spending","funding","closing","gap"].map(k=><th scope="col" key={k} className="p-3 text-left">{t(k)}</th>)}</tr></thead><tbody>{result.years.map(y=><tr key={y.year} className="border-t"><th scope="row" className="p-3">{y.year}</th>{(["opening","spending","funding","closing","gap"] as const).map(k=><td key={k} className="p-3">{fmt(y[k])} €</td>)}</tr>)}</tbody></table></div><button id="capex-csv" onClick={save} className="mt-4 rounded border px-4 py-2">{t("csv")}</button></section>}
 </div>;
}
