"use client";
import {useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {calculateAcquisition,parseAcquisition,acquisitionCsv,type AcquisitionInput} from '@/lib/hotellerie/acquisition-evidence';
import Breadcrumbs from '@/components/Breadcrumbs';
import RelatedTools from '@/components/RelatedTools';
const fields=['name','price','entryCosts','entryCapex','entryReference','debt','annualRatePct','months','monthlyCosts','loanReference','exitPrice','exitCosts','exitReference','discountPct','discountReference'] as const;
const numbers=['price','entryCosts','entryCapex','debt','annualRatePct','months','monthlyCosts','exitPrice','exitCosts','discountPct'] as const;
type Draft=Record<typeof fields[number],string>;
export default function AcquisitionPage(){const t=useTranslations('hotelAcquisitionEvidence'),locale=useLocale(),[draft,setDraft]=useState<Draft>(Object.fromEntries(fields.map(k=>[k,''])) as Draft),[years,setYears]=useState([{cash:'',reference:''}]),[error,setError]=useState(false);
 const input=useMemo(()=>({...draft,version:1, ...Object.fromEntries(numbers.map(k=>[k,draft[k].trim()?Number(draft[k]):NaN])),years:years.map(y=>({...y,cash:y.cash.trim()?Number(y.cash):NaN}))}) as unknown as AcquisitionInput,[draft,years]);
 const result=useMemo(()=>{try{return calculateAcquisition(input)}catch{return null}},[input]);const fmt=(n:number,d=2)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:d,maximumFractionDigits:d});const save=(data:string,type:string,ext:string)=>{const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download='hotel-acquisition.'+ext;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const metrics=['totalEntry','initialEquity','monthlyPayment','exitDebt','netExit','contributed','distributed','netGain','multiple','npv','irr'] as const;
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 [overflow-wrap:anywhere]"><Breadcrumbs/><h1 className="mt-3 text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-sm text-muted">{t('scope')}</p><section className="mt-6 rounded-xl border border-card-border bg-card p-4"><div className="grid gap-4 sm:grid-cols-2">{fields.map(key=><label key={key} className="min-w-0 text-sm">{t(key)}<input id={'acquisition-'+key} type={(numbers as readonly string[]).includes(key)?'number':'text'} value={draft[key]} step={key==='months'?'1':key==='annualRatePct'||key==='discountPct'?'0.0001':'0.01'} maxLength={key==='name'?160:500} onChange={e=>setDraft(old=>({...old,[key]:e.target.value}))} className="mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2 text-sm"/></label>)}</div><p className="mt-4 text-sm text-muted">{t('entryScope')}</p><p className="mt-3 text-sm text-muted">{t('loanScope')}</p><p className="mt-3 text-sm text-muted">{t('exitScope')}</p></section><h2 className="mt-6 text-xl font-semibold">{t('cashTitle')}</h2><p className="mt-3 text-sm text-muted">{t('cashScope')}</p><div className="mt-4 space-y-3">{years.map((y,k)=><div key={k} data-acquisition-input-year={k+1} className="grid gap-3 rounded-lg border border-card-border bg-card p-4 sm:grid-cols-2"><label className="min-w-0 text-sm">{t('cash')} — {k+1}<input data-field="cash" type="number" step="0.01" value={y.cash} onChange={e=>setYears(old=>old.map((v,n)=>n===k?{...v,cash:e.target.value}:v))} className="mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2"/></label><label className="min-w-0 text-sm">{t('reference')} — {k+1}<input data-field="reference" maxLength={500} value={y.reference} onChange={e=>setYears(old=>old.map((v,n)=>n===k?{...v,reference:e.target.value}:v))} className="mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2"/></label></div>)}</div><div className="mt-3 flex flex-wrap gap-3"><button id="acquisition-add" disabled={years.length>=30} onClick={()=>setYears(old=>[...old,{cash:'',reference:''}])} className="rounded border border-card-border px-4 py-2 text-sm disabled:opacity-40">{t('add')}</button><button id="acquisition-remove" disabled={years.length<=1} onClick={()=>setYears(old=>old.slice(0,-1))} className="rounded border border-card-border px-4 py-2 text-sm disabled:opacity-40">{t('remove')}</button></div>
 {!result?<p role="status" className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{t('invalid')}</p>:<section data-acquisition-results className="mt-8"><h2 className="text-xl font-semibold text-navy">{t('result')}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(k=><div key={k} className="min-w-0 rounded-xl border border-card-border bg-card p-4"><h3 className="text-sm">{t(k)}</h3><p data-acquisition-total={k} className="mt-2 text-xl font-semibold">{result[k]===null?'—':fmt(result[k],k==='multiple'?3:2)+(k==='multiple'?' ×':k==='irr'?' %':' €')}</p></div>)}</div><p className="mt-4 text-sm text-muted">{t('returnScope')}</p><div className="mt-4 overflow-x-auto rounded-lg border border-card-border"><table className="w-full min-w-[1000px] text-sm"><thead><tr>{['year','cash','debtMonths','debtService','dscr','remaining','exit','equityCash'].map(k=><th key={k} className="p-3 text-left">{t(k)}</th>)}</tr></thead><tbody>{result.years.map(y=><tr key={y.year} data-acquisition-year={y.year} className="border-t border-card-border"><td className="p-3">{y.year}</td>{(['cash','debtMonths','debtService','dscr','remaining','exit','equityCash'] as const).map(k=><td data-value={k} key={k} className="whitespace-nowrap p-3">{y[k]===null?'—':k==='debtMonths'?y[k]:fmt(y[k],k==='dscr'?3:2)+(k==='dscr'?' ×':' €')}</td>)}</tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap gap-3"><button id="acquisition-csv" onClick={()=>save(acquisitionCsv(input),'text/csv;charset=utf-8','csv')} className="rounded border border-card-border px-4 py-2 text-sm">{t('csv')}</button><button id="acquisition-json" onClick={()=>save(JSON.stringify(input,null,2),'application/json','json')} className="rounded border border-card-border px-4 py-2 text-sm">{t('json')}</button></div></section>}
 <label className="mt-6 block text-sm">{t('import')}<input id="acquisition-import" type="file" accept=".json,application/json" className="mt-2 block max-w-full" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>100000)throw Error();const data=parseAcquisition(await f.text());setDraft(Object.fromEntries(fields.map(k=>[k,String(data[k])])) as Draft);setYears(data.years.map(y=>({cash:String(y.cash),reference:y.reference})));setError(false)}catch{setError(true)}finally{e.target.value=''}}}/></label>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{t('importError')}</p>}<p className="mt-3 text-sm text-muted">{t('storage')}</p><a href="https://www.rics.org/profession-standards/rics-standards-and-guidance/sector-standards/valuation-standards/discounted-cash-flow-valuation" target="_blank" rel="noopener noreferrer" className="mt-4 block text-sm underline">{t('source')}</a><RelatedTools keys={['hotelExploitation','hotelValorisation','bancaire']}/></main>;
}

