export type CompsetHotel={id:string;name:string;role:'benchmark'|'subject';rooms:number;available:number;sold:number;revenue:number;reference:string};
export type CompsetInput={version:1;start:string;end:string;selectionReference:string;hotels:CompsetHotel[]};
function date(s:string){if(typeof s!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(s))throw new RangeError('Date required');const ms=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(ms)||new Date(ms).toISOString().slice(0,10)!==s)throw new RangeError('Invalid date');return ms}
function ref(s:string,max=500){if(typeof s!=='string'||!s.trim()||s.length>max)throw new RangeError('Reference required')}
function integer(n:number,max:number){if(!Number.isInteger(n)||n<0||n>max)throw new RangeError('Invalid count')}
function kpis(available:number,sold:number,revenue:number){return {available,sold,revenue,adr:sold===0?null:revenue/sold,occupancyPct:available===0?null:sold/available*100,revpar:available===0?null:revenue/available}}
export function calculateCompset(i:CompsetInput){if(!i||i.version!==1)throw new RangeError('Invalid version');const days=(date(i.end)-date(i.start))/86400000+1;if(days<1||days>366)throw new RangeError('Invalid period');ref(i.selectionReference);if(!Array.isArray(i.hotels)||i.hotels.length<1||i.hotels.length>100)throw new RangeError('Invalid hotels');const ids=new Set<string>();let subjects=0;const hotels=i.hotels.map(h=>{if(!h||!['subject','benchmark'].includes(h.role))throw new RangeError('Invalid hotel');ref(h.id,100);if(ids.has(h.id))throw new RangeError('Duplicate hotel');ids.add(h.id);ref(h.name,160);ref(h.reference);integer(h.rooms,100000);if(h.rooms===0)throw new RangeError('Rooms required');integer(h.available,h.rooms*days);integer(h.sold,h.available);if(typeof h.revenue!=='number'||!Number.isFinite(h.revenue)||h.revenue<0||h.revenue>1e9||Math.abs(h.revenue*100-Math.round(h.revenue*100))>1e-5||h.sold===0&&h.revenue!==0)throw new RangeError('Invalid revenue');if(h.role==='subject')subjects++;return {...h,...kpis(h.available,h.sold,h.revenue)}});const benchmark=hotels.filter(h=>h.role==='benchmark');if(!benchmark.length||subjects>1)throw new RangeError('A benchmark and at most one subject required');const totals=kpis(benchmark.reduce((s,h)=>s+h.available,0),benchmark.reduce((s,h)=>s+h.sold,0),benchmark.reduce((s,h)=>s+Math.round(h.revenue*100),0)/100),subject=hotels.find(h=>h.role==='subject')??null;const index=(n:number|null|undefined,d:number|null)=>n==null||d===null||d===0?null:n/d*100;return {days,benchmarkCount:benchmark.length,totals,subject,ari:index(subject?.adr,totals.adr),mpi:index(subject?.occupancyPct,totals.occupancyPct),rgi:index(subject?.revpar,totals.revpar),hotels}}
export function parseCompset(raw:string):CompsetInput{if(raw.length>200000)throw new RangeError('File too large');const i=JSON.parse(raw);calculateCompset(i);return i}
export function compsetCsv(i:CompsetInput){const r=calculateCompset(i),units:Record<string,string>={days:'days',benchmarkCount:'hotels',rooms:'rooms',available:'available-room-nights',sold:'sold-room-nights',revenue:'EUR',adr:'EUR/sold-room-night',occupancyPct:'percent',revpar:'EUR/available-room-night',ari:'index-100',mpi:'index-100',rgi:'index-100'},cell=(v:unknown)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const rows:unknown[][]=[['kind','label','value','unit'],['input','start',i.start,'date'],['input','end',i.end,'date'],['input','selectionReference',i.selectionReference,'text'],...Object.entries(r.totals).map(([k,v])=>['benchmark',k,v,units[k]]),...(['days','benchmarkCount','ari','mpi','rgi'] as const).map(k=>['result',k,r[k],units[k]]),...r.hotels.flatMap(h=>Object.entries(h).map(([k,v])=>['hotel_'+h.id,k,v,units[k]??'text']))];return '\uFEFF'+rows.map(row=>row.map(cell).join(';')).join('\r\n')}
