import {calculerMensualite,genererTableauAmortissement} from '../calculations';
export type HotelCoverageInput={name:string;principal:number;annualRatePct:number;months:number;monthlyCosts:number;upfrontCosts:number;loanReference:string;annualCash:number;cashReference:string;target:number;targetReference:string;propertyValue:number|null;valueReference:string;stressedAnnualCash:number|null;stressReference:string};
function amount(n:number,min=0,max=1e9,precision=100){if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max||Math.abs(n*precision-Math.round(n*precision))>1e-5)throw new RangeError('Invalid amount')}
function reference(s:string,max=500){if(typeof s!=='string'||!s.trim()||s.length>max)throw new RangeError('Reference required')}
export function calculateHotelCoverage(i:HotelCoverageInput){
 reference(i.name,160);reference(i.loanReference);reference(i.cashReference);reference(i.targetReference);amount(i.principal);amount(i.annualRatePct,0,30,10000);amount(i.months,1,600,1);amount(i.monthlyCosts);amount(i.upfrontCosts);amount(i.annualCash,-1e9);amount(i.target,.0001,100,10000);if(i.principal===0&&(i.monthlyCosts!==0||i.upfrontCosts!==0))throw new RangeError('No loan costs without loan');
 if(i.propertyValue!==null){amount(i.propertyValue,.01,1e12);reference(i.valueReference)}if(i.stressedAnnualCash!==null){amount(i.stressedAnnualCash,-1e9);reference(i.stressReference)}
 const monthlyPayment=calculerMensualite(i.principal,i.annualRatePct/100,i.months/12),schedule=i.principal>0?genererTableauAmortissement(i.principal,i.annualRatePct/100,i.months/12):[],years=[];
 for(let offset=0;offset<schedule.length;offset+=12){const part=schedule.slice(offset,offset+12),months=part.length,principal=part.reduce((s,m)=>s+m.capital,0),interest=part.reduce((s,m)=>s+m.interets,0),costs=i.monthlyCosts*months,debtService=principal+interest+costs,cash=i.annualCash*months/12,stress=i.stressedAnnualCash===null?null:i.stressedAnnualCash*months/12;years.push({year:offset/12+1,months,principal,interest,costs,debtService,cash,dscr:debtService===0?null:cash/debtService,stressDscr:debtService===0||stress===null?null:stress/debtService,remaining:part.at(-1)!.capitalRestant})}
 const first=years[0],annualDebtService=(monthlyPayment+i.monthlyCosts)*12,interest=schedule.reduce((s,m)=>s+m.interets,0),recurringCosts=i.monthlyCosts*i.months;
 // Solve the same level-payment model for the declared coverage target. This is a mathematical capacity, not a credit offer.
 const paymentCapacity=Math.max(0,i.annualCash/i.target/12-i.monthlyCosts),unitPayment=calculerMensualite(1,i.annualRatePct/100,i.months/12),capacity=paymentCapacity/unitPayment;
 if(!Number.isFinite(capacity)||capacity>1e12)throw new RangeError('Capacity out of scope');
 return {monthlyPayment,monthlyOutflow:monthlyPayment+i.monthlyCosts,annualDebtService,dscr:annualDebtService===0?null:i.annualCash/annualDebtService,stressDscr:annualDebtService===0||i.stressedAnnualCash===null?null:i.stressedAnnualCash/annualDebtService,ltv:i.propertyValue===null?null:i.principal/i.propertyValue*100,capacity,interest,recurringCosts,upfrontCosts:i.upfrontCosts,totalRepayment:i.principal+interest+recurringCosts+i.upfrontCosts,firstPeriodMonths:first?.months??0,years};
}
export function hotelCoverageCsv(i:HotelCoverageInput){const r=calculateHotelCoverage(i),cell=(v:unknown)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const units:Record<string,string>={annualRatePct:'percent',months:'months',annualCash:'EUR/year',stressedAnnualCash:'EUR/year',target:'times',dscr:'times',stressDscr:'times',ltv:'percent',monthlyPayment:'EUR/month',monthlyOutflow:'EUR/month',monthlyCosts:'EUR/month',annualDebtService:'EUR/year',firstPeriodMonths:'months'};const rows:unknown[][]=[['kind','label','value','unit'],...Object.entries(i).map(([k,v])=>['input',k,v,units[k]??(typeof v==='number'?'EUR':'text')]),...Object.entries(r).filter(([k])=>k!=='years').map(([k,v])=>['result',k,v,units[k]??'EUR']),...r.years.flatMap(y=>Object.entries(y).map(([k,v])=>['year_'+y.year,k,v,k==='year'?'year':units[k]??'EUR']))];return '\uFEFF'+rows.map(row=>row.map(cell).join(';')).join('\r\n')}
