export const HOTEL_OPERATING_KINDS=['roomsRevenue','fbRevenue','otherRevenue','departmentPayroll','departmentOther','overheadPayroll','overheadOther','managementFees','nonOperatingIncome','nonOperatingCosts','replacementReserve'] as const;
export type HotelOperatingKind=typeof HOTEL_OPERATING_KINDS[number];
export type HotelOperatingInput={name:string;start:string;end:string;rooms:number;availableRoomNights:number;soldRoomNights:number;capacityReference:string;accountingReference:string;lines:{id:string;kind:HotelOperatingKind;label:string;amount:number;reference:string}[]};
function date(s:string){if(typeof s!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(s))throw new RangeError('Date required');const ms=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(ms)||new Date(ms).toISOString().slice(0,10)!==s)throw new RangeError('Invalid date');return ms}
function integer(n:number,max:number){if(!Number.isInteger(n)||n<0||n>max)throw new RangeError('Invalid count');return n}
function cents(n:number){if(typeof n!=='number'||!Number.isFinite(n)||n<0||n>1e9||Math.abs(n*100-Math.round(n*100))>1e-5)throw new RangeError('Invalid amount');return Math.round(n*100)}
function ref(s:string,max=500){if(typeof s!=='string'||!s.trim()||s.length>max)throw new RangeError('Reference required')}
export function calculateHotelOperating(input:HotelOperatingInput){
 ref(input.name,160);ref(input.capacityReference);ref(input.accountingReference);const days=(date(input.end)-date(input.start))/86400000+1;if(days<1||days>366)throw new RangeError('Period must contain 1 to 366 days');const rooms=integer(input.rooms,100000);if(!rooms)throw new RangeError('Rooms required');const available=integer(input.availableRoomNights,rooms*days),sold=integer(input.soldRoomNights,available);
 if(!Array.isArray(input.lines)||input.lines.length>200)throw new RangeError('Invalid lines');const sums=Object.fromEntries(HOTEL_OPERATING_KINDS.map(k=>[k,0])) as Record<HotelOperatingKind,number>,ids=new Set<string>(),seen=new Set<string>();
 for(const l of input.lines){if(!l||typeof l.id!=='string'||!l.id||l.id.length>100||ids.has(l.id)||!HOTEL_OPERATING_KINDS.includes(l.kind))throw new RangeError('Invalid line');ids.add(l.id);seen.add(l.kind);ref(l.label,160);ref(l.reference);sums[l.kind]+=cents(l.amount)}
 if(HOTEL_OPERATING_KINDS.some(k=>!seen.has(k)))throw new RangeError('Each category must be documented, including zero');if(sold===0&&sums.roomsRevenue>0)throw new RangeError('Room revenue without sold room nights');if(Object.values(sums).some(v=>v>1e12))throw new RangeError('Out of scope');
 const revenue=sums.roomsRevenue+sums.fbRevenue+sums.otherRevenue,departmentalProfit=revenue-sums.departmentPayroll-sums.departmentOther,gop=departmentalProfit-sums.overheadPayroll-sums.overheadOther,ebitda=gop-sums.managementFees+sums.nonOperatingIncome-sums.nonOperatingCosts,afterReserve=ebitda-sums.replacementReserve;
 const ratio=(n:number,d:number)=>d===0?null:n/d;
 return {days,theoreticalRoomNights:rooms*days,unavailableRoomNights:rooms*days-available,totals:Object.fromEntries(Object.entries(sums).map(([k,v])=>[k,v/100])) as Record<HotelOperatingKind,number>,revenue:revenue/100,payroll:(sums.departmentPayroll+sums.overheadPayroll)/100,departmentalProfit:departmentalProfit/100,gop:gop/100,ebitda:ebitda/100,afterReserve:afterReserve/100,occupancy:ratio(sold*100,available),adr:ratio(sums.roomsRevenue/100,sold),revpar:ratio(sums.roomsRevenue/100,available),trevpar:ratio(revenue/100,available),goppar:ratio(gop/100,available),gopMargin:ratio(gop*100,revenue),ebitdaMargin:ratio(ebitda*100,revenue)};
}
export function hotelOperatingCsv(input:HotelOperatingInput){
 const r=calculateHotelOperating(input),cell=(v:unknown)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};
 const units:Record<string,string>={start:'date',end:'date',rooms:'rooms',availableRoomNights:'room-nights',soldRoomNights:'room-nights',days:'days',theoreticalRoomNights:'room-nights',unavailableRoomNights:'room-nights',occupancy:'percent',gopMargin:'percent',ebitdaMargin:'percent',adr:'EUR/sold-room-night',revpar:'EUR/available-room-night',trevpar:'EUR/available-room-night',goppar:'EUR/available-room-night'};
 return '\uFEFF'+[['kind','label','value','reference','unit'],...input.lines.map(l=>[l.kind,l.label,l.amount,l.reference,'EUR']),...Object.entries(input).filter(([k])=>k!=='lines').map(([k,v])=>['input',k,v,'',units[k]??'text']),...Object.entries(r).filter(([k])=>k!=='totals').map(([k,v])=>['result',k,v,'',units[k]??'EUR'])].map(row=>row.map(cell).join(';')).join('\r\n');
}
