export type HotelComparable={id:string;name:string;date:string;price:number;rooms:number;adjustmentPct:number;adjustmentReference:string;weight:number;reference:string};
export type HotelValueInput={name:string;valuationDate:string;rooms:number;rightsReference:string;incomeEnabled:boolean;comparisonEnabled:boolean;annualIncome:number;incomeReference:string;capRatePct:number;rateReference:string;comparables:HotelComparable[]};
function ref(s:string,max=500){if(typeof s!=='string'||!s.trim()||s.length>max)throw new RangeError('Reference required')}
function date(s:string){if(typeof s!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(s))throw new RangeError('Date required');const ms=Date.parse(s+'T00:00:00Z');if(!Number.isFinite(ms)||new Date(ms).toISOString().slice(0,10)!==s)throw new RangeError('Invalid date');return ms}
function num(n:number,min:number,max:number,precision=100){if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max||Math.abs(n*precision-Math.round(n*precision))>1e-5)throw new RangeError('Invalid numeric input')}
export function calculateHotelValue(i:HotelValueInput){
 ref(i.name,160);ref(i.rightsReference);const valuation=date(i.valuationDate);num(i.rooms,1,100000,1);if(typeof i.incomeEnabled!=='boolean'||typeof i.comparisonEnabled!=='boolean'||(!i.incomeEnabled&&!i.comparisonEnabled))throw new RangeError('Select method');
 let incomeValue:number|null=null,comparisonValue:number|null=null,selectedPricePerRoom:number|null=null;
 if(i.incomeEnabled){num(i.annualIncome,-1e9,1e9);num(i.capRatePct,.0001,100,10000);ref(i.incomeReference);ref(i.rateReference);if(i.annualIncome>0)incomeValue=i.annualIncome/(i.capRatePct/100);if(incomeValue!==null&&incomeValue>1e12)throw new RangeError('Out of scope')}
 const comparableRows: (HotelComparable&{pricePerRoom:number;adjustedPricePerRoom:number;normalizedWeight:number})[]=[];
 if(i.comparisonEnabled){if(!Array.isArray(i.comparables)||i.comparables.length<1||i.comparables.length>50)throw new RangeError('One to 50 comparable transactions');const ids=new Set<string>();let weighted=0,totalWeight=0;
  for(const c of i.comparables){if(!c||typeof c.id!=='string'||!c.id||c.id.length>100||ids.has(c.id))throw new RangeError('Invalid comparable');ids.add(c.id);ref(c.name,160);ref(c.reference);ref(c.adjustmentReference);if(date(c.date)>valuation)throw new RangeError('Comparable after valuation');num(c.rooms,1,100000,1);num(c.price,.01,1e10);num(c.adjustmentPct,-100,100);num(c.weight,0,100);const unit=c.price/c.rooms,adjusted=unit*(1+c.adjustmentPct/100);weighted+=adjusted*c.weight;totalWeight+=c.weight;comparableRows.push({...c,pricePerRoom:unit,adjustedPricePerRoom:adjusted,normalizedWeight:0})}
  if(totalWeight<=0)throw new RangeError('Positive weight required');selectedPricePerRoom=weighted/totalWeight;comparisonValue=selectedPricePerRoom*i.rooms;if(comparisonValue>1e12)throw new RangeError('Out of scope');for(const c of comparableRows)c.normalizedWeight=c.weight/totalWeight*100;
 }
 return {incomeValue,comparisonValue,selectedPricePerRoom,comparables:comparableRows};
}
export function hotelValueCsv(i:HotelValueInput){const r=calculateHotelValue(i),cell=(v:unknown)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const rows:unknown[][]=[['kind','label','value','unit','reference'],['input','name',i.name,'text',''],['input','valuation_date',i.valuationDate,'date',''],['input','rooms',i.rooms,'rooms',''],['input','rights',i.rightsReference,'text','']];if(i.incomeEnabled)rows.push(['income','annual_income',i.annualIncome,'EUR/year',i.incomeReference],['income','cap_rate',i.capRatePct,'percent',i.rateReference],['result','capitalisation',r.incomeValue,'EUR','']);if(i.comparisonEnabled){for(const c of r.comparables)rows.push(['comparable',c.name,c.price,'EUR',c.reference],['comparable_date',c.name,c.date,'date',''],['comparable_rooms',c.name,c.rooms,'rooms',''],['comparable_adjustment',c.name,c.adjustmentPct,'percent',c.adjustmentReference],['comparable_weight',c.name,c.weight,'weight',''],['comparable_normalized_weight',c.name,c.normalizedWeight,'percent',''],['comparable_adjusted_price',c.name,c.adjustedPricePerRoom,'EUR/room','']);rows.push(['result','selected_price_per_room',r.selectedPricePerRoom,'EUR/room',''],['result','comparison',r.comparisonValue,'EUR',''])}return '\uFEFF'+rows.map(row=>row.map(cell).join(';')).join('\r\n')}
