"use client";
import { useState } from "react";
import Link from "next/link";
import {useLocale,useTranslations} from "next-intl";
import {GREEN_KEY_SOURCES,validateGreenKeyFile,greenKeyFileCsv,type GreenKeyFile,type GreenKeyRow} from "@/lib/hotellerie/green-key-file";
const empty=():GreenKeyRow=>({criterion:"",kind:"unknown",status:"unknown",proof:""});
export default function GreenKeyPage(){
 const t=useTranslations("greenKeyFile"),locale=useLocale(),prefix=locale==="fr"?"":`/${locale}`;
 const [file,setFile]=useState<GreenKeyFile>({name:"",version:"",scope:"",rows:[empty()]});
 let valid=true;try{validateGreenKeyFile(file)}catch{valid=false}
 const update=(i:number,patch:Partial<GreenKeyRow>)=>setFile(f=>({...f,rows:f.rows.map((r,j)=>j===i?{...r,...patch}:r)}));
 const save=()=>{const url=URL.createObjectURL(new Blob([greenKeyFileCsv(file)],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="green-key-evidence.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <div className="mx-auto max-w-6xl px-4 py-10"><Link href={`${prefix}/hotellerie`} className="text-sm underline">{t("back")}</Link><h1 className="mt-3 text-2xl font-bold">{t("title")}</h1><p data-green-key-scope className="mt-4 rounded-lg border p-4 text-sm">{t("notice")}</p>
 <section className="mt-5"><h2 className="text-lg font-semibold">{t("sources")}</h2><p className="mt-2 text-sm">{t("transition")}</p><ul className="mt-3 space-y-2 text-sm">{Object.entries(GREEN_KEY_SOURCES).map(([k,url])=><li key={k}><a href={url} target="_blank" rel="noopener noreferrer" className="underline">{t(`source_${k}`)}</a></li>)}</ul></section>
 <div className="mt-6 grid gap-4 sm:grid-cols-2"><label htmlFor="gk-name" className="min-w-0 text-sm">{t("name")}<input id="gk-name" maxLength={160} value={file.name} onChange={e=>setFile(f=>({...f,name:e.target.value}))} className="mt-1 block w-full rounded border p-2" /></label><label htmlFor="gk-version" className="min-w-0 text-sm">{t("version")}<select id="gk-version" value={file.version} onChange={e=>setFile(f=>({...f,version:e.target.value as GreenKeyFile["version"]}))} className="mt-1 block w-full rounded border p-2"><option value="">{t("choose")}</option><option value="2022-2026">2022–2026</option><option value="2026-2031">2026–2031</option></select></label></div>
 <label htmlFor="gk-scope" className="mt-4 block text-sm">{t("scope")}<textarea id="gk-scope" rows={3} maxLength={1500} value={file.scope} onChange={e=>setFile(f=>({...f,scope:e.target.value}))} className="mt-1 block w-full rounded border p-2" /></label>
 <p className="mt-5 text-sm">{t("instructions")}</p><div className="mt-4 space-y-4">{file.rows.map((row,i)=><fieldset key={i} data-gk-row={i} className="min-w-0 rounded border p-4"><legend className="px-2">{t("item")} {i+1}</legend><label htmlFor={`gk-${i}-criterion`} className="block text-sm">{t("criterion")}<input id={`gk-${i}-criterion`} maxLength={500} value={row.criterion} onChange={e=>update(i,{criterion:e.target.value})} className="mt-1 block w-full rounded border p-2" /></label><div className="mt-3 grid gap-4 sm:grid-cols-2"><label htmlFor={`gk-${i}-kind`} className="min-w-0 text-sm">{t("kind")}<select id={`gk-${i}-kind`} value={row.kind} onChange={e=>update(i,{kind:e.target.value as GreenKeyRow["kind"]})} className="mt-1 block w-full rounded border p-2">{["unknown","imperative","guideline"].map(k=><option key={k} value={k}>{t(`kind_${k}`)}</option>)}</select></label><label htmlFor={`gk-${i}-status`} className="min-w-0 text-sm">{t("status")}<select id={`gk-${i}-status`} value={row.status} onChange={e=>update(i,{status:e.target.value as GreenKeyRow["status"]})} className="mt-1 block w-full rounded border p-2">{["unknown","evidence","review","na"].map(k=><option key={k} value={k}>{t(`status_${k}`)}</option>)}</select></label></div><label htmlFor={`gk-${i}-proof`} className="mt-3 block text-sm">{t("proof")}<textarea id={`gk-${i}-proof`} maxLength={2000} rows={3} value={row.proof} onChange={e=>update(i,{proof:e.target.value})} className="mt-1 block w-full rounded border p-2" /></label><button disabled={file.rows.length===1} onClick={()=>setFile(f=>({...f,rows:f.rows.filter((_,j)=>j!==i)}))} className="mt-3 text-sm underline disabled:opacity-40">{t("remove")}</button></fieldset>)}</div>
 <div className="mt-4 flex flex-wrap gap-3"><button id="gk-add" disabled={file.rows.length>=200} onClick={()=>setFile(f=>({...f,rows:[...f.rows,empty()]}))} className="rounded border px-4 py-2 disabled:opacity-40">{t("add")}</button><button id="gk-csv" disabled={!valid} onClick={save} className="rounded border px-4 py-2 disabled:opacity-40">{t("csv")}</button></div>{!valid&&<p role="status" className="mt-3 text-sm">{t("invalid")}</p>}
 </div>;
}
