"use client";
import {useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {calculateConstructionBudget,constructionBudgetCsv,type ConstructionBudgetInput,type ConstructionBudgetLine} from '@/lib/construction-budget';
import {PdfButton} from '@/components/PdfButton';
import Breadcrumbs from '@/components/Breadcrumbs';
import RelatedTools from '@/components/RelatedTools';
type Draft=Omit<ConstructionBudgetLine,'quantity'|'unitPriceTtc'>&{quantity:string;unitPriceTtc:string};
const empty=(id:string):Draft=>({id,label:'',kind:'works',quantity:'1',unit:'unit',unitPriceTtc:'',reference:''});
const trades=['Terrassement','Maconnerie','Charpente','Couverture','Zinguerie','MenuiserieExt','Facade','Sanitaire','Chauffage','Electricite','Platrerie','Chapes','Carrelage','Revetements','MenuiserieInt','Peinture','Marbrerie'];
export default function EstimateurConstruction(){
 const t=useTranslations('constructionBudget'),old=useTranslations('estimateurConstruction'),locale=useLocale();
 const [lines,setLines]=useState<Draft[]>([empty('line-1')]),[counter,setCounter]=useState(2),[surface,setSurface]=useState(''),[rate,setRate]=useState('0'),[reason,setReason]=useState('');
 const input=useMemo<ConstructionBudgetInput>(()=>({surfaceM2:surface.trim()?Number(surface):null,contingencyPct:rate.trim()?Number(rate):NaN,contingencyReason:reason,lines:lines.map(l=>({...l,quantity:l.quantity.trim()?Number(l.quantity):NaN,unitPriceTtc:l.unitPriceTtc.trim()?Number(l.unitPriceTtc):NaN}))}),[lines,surface,rate,reason]);
 const result=useMemo(()=>{try{return calculateConstructionBudget(input)}catch{return null}},[input]);
 const number=(n:number)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:2,maximumFractionDigits:2});
 function update(id:string,values:Partial<Draft>){setLines(old=>old.map(l=>l.id===id?{...l,...values}:l))}
 const css='mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2 text-sm';
 const exportCsv=()=>{const url=URL.createObjectURL(new Blob([constructionBudgetCsv(input)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='construction-budget.csv';a.click();URL.revokeObjectURL(url)};
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 [overflow-wrap:anywhere]"><Breadcrumbs/><h1 className="mt-3 text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-sm text-muted">{t('scope')}</p>
  <section className="mt-6 rounded-xl border border-card-border bg-card p-4"><label htmlFor="budget-surface" className="text-sm font-semibold">{t('surface')}</label><input id="budget-surface" type="number" value={surface} min="0.0001" max="1000000" step="any" onChange={e=>setSurface(e.target.value)} className={css}/><p className="mt-2 text-sm text-muted">{t('surfaceScope')}</p></section>
  <h2 className="mt-6 text-lg font-semibold text-navy">{t('lines')}</h2><p className="mt-2 text-sm text-muted">{t('lineScope')}</p><datalist id="budget-trades">{trades.map(k=><option key={k} value={old('trade'+k)}/>)}</datalist>
  <div className="mt-4 space-y-4">{lines.map((line,i)=><section key={line.id} data-budget-line={line.id} className="min-w-0 rounded-xl border border-card-border bg-card p-4">
   <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{t('line')} {i+1}</h3><button type="button" onClick={()=>setLines(rows=>rows.filter(r=>r.id!==line.id))} className="text-sm text-rose-700 underline">{t('remove')}</button></div>
   <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="min-w-0 text-sm">{t('label')}<input data-field="label" list="budget-trades" value={line.label} maxLength={240} onChange={e=>update(line.id,{label:e.target.value})} className={css}/></label><label className="min-w-0 text-sm">{t('kind')}<select data-field="kind" value={line.kind} onChange={e=>update(line.id,{kind:e.target.value as Draft['kind']})} className={css}><option value="works">{t('works')}</option><option value="fees">{t('fees')}</option></select></label></div>
   <div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="min-w-0 text-sm">{t('quantity')}<input data-field="quantity" type="number" min="0.0001" max="1000000" step="0.0001" value={line.quantity} onChange={e=>update(line.id,{quantity:e.target.value})} className={css}/></label><label className="min-w-0 text-sm">{t('unit')}<select data-field="unit" value={line.unit} onChange={e=>update(line.id,{unit:e.target.value as Draft['unit']})} className={css}>{(['unit','m2','m3','m','h'] as const).map(u=><option key={u} value={u}>{u==='unit'?t('lump'):u==='m2'?'m²':u==='m3'?'m³':u}</option>)}</select></label><label className="min-w-0 text-sm">{t('unitPrice')}<input data-field="unitPriceTtc" type="number" min="0" max="100000000" step="0.01" value={line.unitPriceTtc} onChange={e=>update(line.id,{unitPriceTtc:e.target.value})} className={css}/></label></div>
   <label className="mt-3 block text-sm">{t('reference')}<input data-field="reference" value={line.reference} maxLength={500} onChange={e=>update(line.id,{reference:e.target.value})} className={css}/></label>
  </section>)}</div>
  <button id="budget-add" type="button" disabled={lines.length>=200} onClick={()=>{setLines(old=>[...old,empty('line-'+counter)]);setCounter(counter+1)}} className="mt-4 rounded-lg border border-card-border px-4 py-2 text-sm disabled:opacity-50">{t('add')}</button>
  <section className="mt-6 rounded-xl border border-card-border bg-card p-4"><label htmlFor="budget-rate" className="text-sm font-semibold">{t('contingency')}</label><input id="budget-rate" type="number" min="0" max="100" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} className={css}/><p className="mt-2 text-sm text-muted">{t('contingencyScope')}</p><label htmlFor="budget-reason" className="mt-3 block text-sm">{t('reason')}</label><input id="budget-reason" value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} className={css}/></section>
  {!result?<p role="status" className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm">{t('invalid')}</p>:<section data-budget-results className="mt-6 rounded-xl border border-card-border bg-card p-4"><h2 className="text-lg font-semibold text-navy">{t('resultTitle')}</h2><p className="mt-2 text-sm text-muted">{t('partial')}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2">{([['worksTtc','works'],['feesTtc','fees'],['contingencyTtc','contingencyAmount'],['totalTtc','total']] as const).map(([key,label])=><div key={key} className="rounded-lg bg-navy/5 p-3"><dt className="text-sm">{t(label)}</dt><dd data-budget-total={key} className="mt-2 text-xl font-bold text-navy">{number(result[key])} €</dd></div>)}</dl>{result.costPerM2!==null&&<p className="mt-4 text-sm">{t('perM2')}: <strong data-budget-perm2>{number(result.costPerM2)} €/m²</strong></p>}
   <div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">{t('label')}</th><th className="p-2 text-right">{t('total')}</th></tr></thead><tbody>{result.lines.map(l=><tr key={l.id} className="border-t border-card-border"><td className="p-2">{l.label}</td><td className="p-2 text-right">{number(l.totalTtc)} €</td></tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap gap-3"><button id="budget-export" onClick={exportCsv} className="rounded-lg border border-card-border px-3 py-2 text-sm">{t('csv')}</button><PdfButton label="PDF" filename="construction-budget.pdf" generateBlob={async()=>{const {generateConstructionBudgetPdfBlob}=await import('@/components/ConstructionBudgetPdf');return generateConstructionBudgetPdfBlob({input,locale,labels:Object.fromEntries(['title','scope','surface','line','label','kind','works','fees','quantity','unit','unitPrice','reference','contingency','contingencyScope','reason','resultTitle','partial','contingencyAmount','total','perM2','lump','indexScope','source'].map(k=>[k,t(k)]))})}}/></div>
  </section>}
  <section className="mt-6 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm"><p>{t('indexScope')}</p><a className="mt-2 inline-block underline" href="https://statistiques.public.lu/fr/donnees/methodologie/methodes/economie-totale-prix/prix-construction.html" target="_blank" rel="noopener noreferrer">{t('source')}</a></section><RelatedTools keys={['valorisation','bancaire']}/>
 </main>;
}
