"use client";
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from 'recharts';
import {calculateReportedIntensities,compareTrajectory,parseTrajectory} from '@/lib/crrem';
const EXAMPLE='year;targetEnergy;targetCarbon;assetEnergy;assetCarbon\n2026;100;20;100;20\n2027;90;19;100;20\n2028;80;18;70;17';
export default function TrajectoryPage(){
 const t=useTranslations('trajectoryAudit'),locale=useLocale(),fmt=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{maximumFractionDigits:6}).format(n);
 const [metrics,setMetrics]=useState({area:NaN,energy:NaN,carbon:NaN}),[reference,setReference]=useState(''),[data,setData]=useState(''),[example,setExample]=useState(false);
 const intensity=(()=>{try{return calculateReportedIntensities(metrics.area,metrics.energy,metrics.carbon)}catch{return null}})();
 const r=(()=>{try{return compareTrajectory(parseTrajectory(data),reference)}catch{return null}})();
 return <div className="mx-auto max-w-6xl space-y-6 px-4 py-10 [overflow-wrap:anywhere]"><h1 className="text-2xl font-bold">{t('title')}</h1><p className="text-muted">{t('intro')}</p><p className="text-sm text-muted">{t('scope')}</p>
 <section className="space-y-4 rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold">{t('report')}</h2><div className="grid gap-4 sm:grid-cols-3">{(['area','energy','carbon'] as const).map(k=><label className="min-w-0 text-sm" key={k}>{t(k)}<input id={'trajectory-'+k} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5" type="number" min={0} step="any" value={Number.isNaN(metrics[k])?'':metrics[k]} onChange={e=>setMetrics({...metrics,[k]:e.target.valueAsNumber})}/></label>)}</div><p className="text-sm text-muted">{t('metricsNote')}</p>{intensity?<dl id="trajectory-intensities" className="grid gap-4 sm:grid-cols-2">{(['energy','carbon'] as const).map(k=><div key={k}><dt>{t(k+'Intensity')}</dt><dd id={'trajectory-intensity-'+k} className="text-xl font-semibold">{fmt(intensity[k])}</dd></div>)}</dl>:<p className="text-sm text-muted">{t('invalid')}</p>}</section>
 <section className="space-y-4 rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold">{t('trajectory')}</h2><label className="block text-sm">{t('reference')}<input id="trajectory-reference" value={reference} onChange={e=>{setReference(e.target.value);setExample(false)}} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5"/></label><p className="text-sm text-muted">{t('referenceNote')}</p><label className="block text-sm">{t('data')}<textarea id="trajectory-data" rows={7} spellCheck={false} value={data} onChange={e=>{setData(e.target.value);setExample(false)}} placeholder="year;targetEnergy;targetCarbon;assetEnergy;assetCarbon" className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5 font-mono"/></label><p className="text-sm text-muted">{t('inputNote')}</p>
 <button id="trajectory-example" type="button" onClick={()=>{setData(EXAMPLE);setReference(t('exampleReference'));setExample(true)}} className="rounded-lg border border-card-border px-4 py-2 text-sm">{t('loadExample')}</button>{example&&<p className="text-sm text-muted">{t('exampleNote')}</p>}</section>
 {r?<><section id="trajectory-results" className="space-y-4 rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold">{t('result')}</h2><p>{t('period')}: {r.from}–{r.to}</p><dl className="grid gap-4 sm:grid-cols-3">{(['firstEnergy','firstCarbon','first'] as const).map(k=><div key={k}><dt>{t(k)}</dt><dd id={'trajectory-'+k} className="mt-2 text-xl font-semibold">{r[k]??t('none')}</dd></div>)}</dl><p className="text-sm text-muted">{t('scope')}</p></section>
 <div className="grid gap-6 lg:grid-cols-2">{(['Energy','Carbon'] as const).map(metric=><section key={metric} className="min-w-0 rounded-xl border border-card-border bg-card p-4"><h2 className="mb-4 font-semibold">{t('chart'+metric)}</h2><div className="h-72 w-full min-w-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={r.rows} margin={{top:10,right:15,bottom:5,left:0}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year" tick={{fontSize:12}}/><YAxis width={45} tick={{fontSize:12}}/><Tooltip formatter={value=>fmt(Number(value))}/><Legend/><Line type="linear" dataKey={'target'+metric} name={t('target'+metric)} stroke="#059669" strokeWidth={2} isAnimationActive={false}/><Line type="linear" dataKey={'asset'+metric} name={t('asset'+metric)} stroke="#1e3a5f" strokeWidth={2} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></section>)}</div>
 <section className="rounded-xl border border-card-border bg-card p-5"><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="mb-3 text-left">{t('result')} — {t('chartEnergy')} / {t('chartCarbon')}</caption><thead><tr>{['year','targetEnergy','assetEnergy','energyGap','targetCarbon','assetCarbon','carbonGap'].map(k=><th key={k} scope="col" className="p-3 text-left">{t(k)}</th>)}</tr></thead><tbody>{r.rows.map(row=><tr key={row.year} className="border-t border-card-border">{(['year','targetEnergy','assetEnergy','energyGap','targetCarbon','assetCarbon','carbonGap'] as const).map(k=><td key={k} className="p-3 tabular-nums">{k==='year'?row[k]:fmt(row[k])}</td>)}</tr>)}</tbody></table></div></section></>:<p role="status" className="text-sm text-muted">{t('invalid')}</p>}
 <section className="space-y-3 text-sm"><h2 className="font-semibold">{t('sources')}</h2><p className="text-muted">{t('officialNote')}</p><a className="block underline" href="https://crrem.org/learn/">{t('source0')}</a><a className="block underline" href="https://energy.ec.europa.eu/topics/energy-efficiency/energy-performance-buildings/energy-performance-buildings-directive_en">{t('source1')}</a></section></div>;
}
