"use client";
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {PdfButton} from '@/components/PdfButton';
import {HVAC_SCENARIO_EXAMPLE,EMPTY_HVAC_QUOTES,HVAC_LOTS,HVAC_SOURCES,compareHvac,formatHvacValue,buildHvacReport,type HvacScenario} from '@/lib/hvac-scenario';
export default function HVACSimulator(){
 const t=useTranslations('hvacScenarioAudit'),lot=useTranslations('hvac'),locale=useLocale();
 const [i,setInput]=useState(HVAC_SCENARIO_EXAMPLE),[quotes,setQuotes]=useState(EMPTY_HVAC_QUOTES);
 const r=(()=>{try{return compareHvac(i,quotes)}catch{return null}})();
 return <div className="mx-auto max-w-6xl space-y-6 px-4 py-10"><h1 className="text-2xl font-bold">{t('title')}</h1><p className="text-muted">{t('intro')}</p>
  <section className="rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold">{t('inputs')}</h2><p className="mt-3 text-sm text-muted">{t('energyNote')}</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(Object.keys(i) as (keyof HvacScenario)[]).map(k=><label key={k} className="text-sm">{t(k)}<input id={'hvac-'+k} type="number" min={k==='years'?1:0} max={k==='years'?50:k.startsWith('factor')?10:1e12} step={k==='years'?1:'any'} value={Number.isNaN(i[k])?'':i[k]} onChange={e=>setInput({...i,[k]:e.target.valueAsNumber})} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5"/></label>)}</div><p className="mt-4 text-sm text-muted">{t('powerNote')}</p></section>
  <section className="rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold">{t('quotes')}</h2><p className="mt-3 text-sm text-muted">{t('quoteNote')}</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{HVAC_LOTS.map(k=><label key={k} className="text-sm">{k==='other'?t('other'):lot('lots.'+k)} (EUR)<input id={'hvac-quote-'+k} type="number" min={0} max={1e12} step="any" value={Number.isNaN(quotes[k])?'':quotes[k]} onChange={e=>setQuotes({...quotes,[k]:e.target.valueAsNumber})} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5"/></label>)}</div></section>
  {!r&&<p role="alert" className="text-red-700">{t('invalid')}</p>}
  {r&&<section id="hvac-results" className="space-y-4"><h2 className="text-lg font-semibold">{t('results')}</h2>{r.budget===0&&<p className="rounded-lg border border-amber-300 p-4 text-sm">{t('missingBudget')}</p>}<dl className="rounded-xl border border-card-border bg-card p-5">{Object.entries(r).map(([k,v])=><div key={k} className="flex flex-wrap justify-between gap-3 border-b border-card-border py-3"><dt>{t(k)}</dt><dd id={'hvac-result-'+k} className="font-semibold">{formatHvacValue(k,v,locale,k=>t(k))}</dd></div>)}</dl><div className="flex justify-end"><PdfButton label="PDF" filename="chauffage-scenario.pdf" generateBlob={async()=>(await import('@/components/energy/EnergyAuditPdf')).generateEnergyAuditPdf(buildHvacReport(i,quotes,k=>t(k),k=>lot(k),locale))}/></div></section>}
  <section className="rounded-xl border border-card-border bg-card p-5 text-sm text-muted"><h2 className="font-semibold">{t('limits')}</h2><p className="mt-3">{t('financialNote')}</p><p className="mt-3">{t('aidNote')}</p><a href={HVAC_SOURCES[0]} className="mt-3 block underline">{t('source')}</a><a href={HVAC_SOURCES[1]} className="mt-3 block underline">{t('aidSource')}</a></section>
 </div>;
}
