"use client";
import {useState} from 'react';
import Link from 'next/link';
import {useLocale,useTranslations} from 'next-intl';
import {socialRentalExemption,socialRentalScenario} from '@/lib/social-rental-scenario';
export default function AISPage(){
 const t=useTranslations('socialRentalAudit'),locale=useLocale(),lp=locale==='fr'?'':'/'+locale;
 const [year,setYear]=useState(2026),[eligible,setEligible]=useState(false),[values,setValues]=useState({standardRent:'',socialRent:'',standardCosts:'',socialCosts:'',marginalRate:''});
 const money=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-LU':locale,{style:'currency',currency:'EUR',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
 let result:ReturnType<typeof socialRentalScenario>|null=null,invalid=false;
 try{if(Object.values(values).every(s=>s.trim()!==''))result=socialRentalScenario({year,eligible,standardRent:Number(values.standardRent),socialRent:Number(values.socialRent),standardCosts:Number(values.standardCosts),socialCosts:Number(values.socialCosts),marginalRate:Number(values.marginalRate)})}catch{invalid=true;}
 const inputClass='mt-1 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2 text-base';
 return <div className="bg-background py-8 sm:py-12"><div className="mx-auto max-w-5xl px-4 sm:px-6 [overflow-wrap:anywhere]">
  <Link href={lp+'/gestion-locative'} className="text-sm underline">{t('back')}</Link><h1 className="mt-3 text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-base text-muted">{t('intro')}</p>
  <div className="mt-6 rounded-xl border border-card-border bg-card p-5"><label className="block text-sm">{t('year')}<select aria-label={t('year')} value={year} onChange={e=>setYear(Number(e.target.value))} className={inputClass}>{Array.from({length:10},(_,i)=>2026-i).map(y=><option key={y} value={y}>{y}</option>)}</select></label><p className="mt-3 font-semibold text-navy">{t('exemption',{year,rate:socialRentalExemption(year)})}</p><p className="mt-2 text-sm text-muted">{t('rateNote')}</p></div>
  <div className="mt-6 rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold text-navy">{t('inputsTitle')}</h2><p className="mt-2 text-sm text-muted">{t('inputNote')}</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{(['standardRent','socialRent','standardCosts','socialCosts','marginalRate'] as const).map(key=><label key={key} className="text-sm">{t(key)}<input type="number" min="0" max={key==='marginalRate'?100:undefined} step="0.01" value={values[key]} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} className={inputClass}/></label>)}</div><label className="mt-5 flex items-start gap-3 text-sm"><input type="checkbox" checked={eligible} onChange={e=>setEligible(e.target.checked)} className="mt-1 shrink-0"/>{t('eligible')}</label>{invalid&&<p role="alert" className="mt-3 text-sm text-rose-700">{t('invalid')}</p>}</div>
  <div className="mt-6 grid gap-4 sm:grid-cols-2">{(['standardNet','socialNet'] as const).map(key=><div key={key} className="rounded-xl border border-card-border bg-card p-5"><h2 className="text-sm text-muted">{t(key)}</h2><p className="mt-2 text-xl font-bold text-navy">{result?money(result[key]):t('missing')}</p></div>)}</div>
  {result?.estimate?<div className="mt-6 rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold text-navy">{t('estimateTitle')}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{(['standardTax','socialTax','standardAfterTax','socialAfterTax','difference'] as const).map(key=><div key={key}><dt className="text-sm text-muted">{t(key)}</dt><dd className="mt-1 text-xl font-bold text-navy">{money(result!.estimate![key])}</dd></div>)}</dl></div>:<p className="mt-5 text-sm text-muted">{t('notReady')}</p>}
  <p className="mt-4 text-sm text-muted">{t('estimateNote')}</p>
  <section className="mt-8 rounded-xl border border-card-border bg-card p-5"><h2 className="text-lg font-semibold text-navy">{t('conditionsTitle')}</h2><p className="mt-3 text-sm text-muted">{t('conditions')}</p><div className="mt-4 flex flex-wrap gap-4 text-sm underline"><a href="https://logement.public.lu/fr/proprietaire/logement-location/gestion-locative-sociale.html">{t('directory')}</a><a href="https://impotsdirects.public.lu/fr/az/l/logem_loc.html">{t('acd')}</a></div><p className="mt-3 text-sm text-muted">{t('sourceDate')}</p></section>
 </div></div>;
}
