"use client";
import {useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {evaluerTerreAgricole,agriculturalCsv,type AgriculturalInput} from '@/lib/agricultural';
import {AGRICULTURAL_REFERENCE} from '@/lib/agricultural-reference';
import Breadcrumbs from '@/components/Breadcrumbs';
import RelatedTools from '@/components/RelatedTools';
const numeric=['surfaceHa','priceHa','buildingValue','demolitionCost','remediationCost'] as const;
const refs=['priceReference','buildingReference','demolitionReference','remediationReference','rightsReference'] as const;
type Draft=Record<keyof AgriculturalInput,string>;
const initial=Object.fromEntries([...numeric,...refs].map(k=>[k,''])) as Draft;
export default function TerresAgricoles(){
 const t=useTranslations('agriculturalEvidence'),locale=useLocale(),[draft,setDraft]=useState<Draft>(initial);
 const input=useMemo(()=>({...draft,...Object.fromEntries(numeric.map(k=>[k,draft[k].trim()?Number(draft[k]):NaN]))}) as unknown as AgriculturalInput,[draft]);
 const result=useMemo(()=>{try{return evaluerTerreAgricole(input)}catch{return null}},[input]);
 const fmt=(n:number,d=2)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:d,maximumFractionDigits:d});
 const field=(key:keyof Draft)=>{const isNumber=(numeric as readonly string[]).includes(key);return <label key={key} className="min-w-0 text-sm">{t(key)}<input id={'agricultural-'+key} type={isNumber?'number':'text'} value={draft[key]} min={isNumber?'0':undefined} step={key==='surfaceHa'?'0.0001':'0.01'} maxLength={500} onChange={e=>setDraft(old=>({...old,[key]:e.target.value}))} className="mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2 text-sm"/></label>};
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 [overflow-wrap:anywhere]"><Breadcrumbs/><h1 className="mt-3 text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-sm text-muted">{t('scope')}</p>
 <section className="mt-6 rounded-xl border border-card-border bg-card p-4"><div className="grid gap-4 sm:grid-cols-2">{field('surfaceHa')}{field('priceHa')}{field('priceReference')}{field('rightsReference')}{field('buildingValue')}{field('buildingReference')}{field('demolitionCost')}{field('demolitionReference')}{field('remediationCost')}{field('remediationReference')}</div><p className="mt-4 text-sm text-muted">{t('rightsScope')}</p></section>
 {!result?<p role="status" className="mt-5 rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{t('invalid')}</p>:<section data-agricultural-results className="mt-6"><h2 className="text-lg font-semibold text-navy">{t('result')}</h2><p className="mt-3 text-sm">{t('surfaceM2')}: <strong data-agricultural-surface>{fmt(result.surfaceM2,0)} m²</strong></p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(['landValue','buildingValue','demolitionCost','remediationCost','netValue'] as const).map(k=><div key={k} className="min-w-0 rounded-xl border border-card-border bg-card p-4"><h3 className="text-sm">{t(k)}</h3><p data-agricultural-total={k} className="mt-2 text-xl font-semibold">{fmt(result[k])} €</p></div>)}</div><p className="mt-3 text-sm text-muted">{t('formula')}</p><button id="agricultural-csv" type="button" className="mt-4 rounded-lg border border-card-border px-4 py-2 text-sm" onClick={()=>{const url=URL.createObjectURL(new Blob([agriculturalCsv(input)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='terres-agricoles.csv';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}}>{t('csv')}</button></section>}
 <section className="mt-8 rounded-xl border border-card-border bg-card p-4"><h2 className="text-lg font-semibold text-navy">{t('referenceTitle')}</h2><p className="mt-3 text-sm text-muted">{t('referenceScope')}</p><p className="mt-3 text-sm text-muted">{t('referenceFees')}</p><p className="mt-3 text-sm text-muted">{t('referenceDate')}</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr>{['year','arable','grassland','combinedMedian'].map(k=><th key={k} className="p-3 text-left">{t(k)}</th>)}</tr></thead><tbody>{[...AGRICULTURAL_REFERENCE.observations].reverse().map(row=><tr key={row.year} data-agricultural-year={row.year} className="border-t border-card-border"><td className="p-3">{row.year}</td>{(['arable','grassland','combinedMedian'] as const).map(k=><td key={k} data-value={k} className="whitespace-nowrap p-3">{row[k]===null?'—':fmt(row[k],0)}</td>)}</tr>)}</tbody></table></div><a className="mt-4 block text-sm underline" href="https://lustat.statec.lu/?pg=0&tm=DF_D2121" target="_blank" rel="noopener noreferrer">{t('source')}</a><a className="mt-3 block text-sm underline" href="https://agriculture.public.lu/de/agrarstatistik/landwirtschaftliche-preise-und-indizes.html" target="_blank" rel="noopener noreferrer">{t('methodology')}</a></section><RelatedTools keys={['carte','pagPap','valorisation']}/></main>;
}
