"use client";
import {useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {calculateHotelValue,hotelValueCsv,type HotelValueInput,type HotelComparable} from '@/lib/hotellerie/value-evidence';
import Breadcrumbs from '@/components/Breadcrumbs';
import RelatedTools from '@/components/RelatedTools';
type DraftComparable=Omit<HotelComparable,'price'|'rooms'|'adjustmentPct'|'weight'>&{price:string;rooms:string;adjustmentPct:string;weight:string};
const blank=(id:string):DraftComparable=>({id,name:'',date:'',price:'',rooms:'',adjustmentPct:'0',adjustmentReference:'',weight:'',reference:''});
const _fields=['name','valuationDate','rooms','rightsReference','annualIncome','incomeReference','capRatePct','rateReference'] as const;
type Draft=Record<typeof _fields[number],string>;
const toNumber=(s:string)=>s.trim()?Number(s):NaN;
export default function ValorisationHotelPage(){
 const t=useTranslations('hotelValueEvidence'),locale=useLocale(),[draft,setDraft]=useState<Draft>({name:'',valuationDate:'',rooms:'',rightsReference:'',annualIncome:'',incomeReference:'',capRatePct:'',rateReference:''}),[incomeEnabled,setIncomeEnabled]=useState(true),[comparisonEnabled,setComparisonEnabled]=useState(false),[comparables,setComparables]=useState<DraftComparable[]>([blank('comparable-1')]);
 const input=useMemo<HotelValueInput>(()=>({...draft,rooms:toNumber(draft.rooms),annualIncome:toNumber(draft.annualIncome),capRatePct:toNumber(draft.capRatePct),incomeEnabled,comparisonEnabled,comparables:comparables.map(c=>({...c,rooms:toNumber(c.rooms),price:toNumber(c.price),adjustmentPct:toNumber(c.adjustmentPct),weight:toNumber(c.weight)}))}),[draft,incomeEnabled,comparisonEnabled,comparables]);
 const result=useMemo(()=>{try{return calculateHotelValue(input)}catch{return null}},[input]);
 const fmt=(n:number)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:2,maximumFractionDigits:2}),css='mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2 text-sm';
 const field=(key:typeof _fields[number])=><label key={key} className="min-w-0 text-sm">{t(key)}<input id={'hotel-value-'+key} type={key==='valuationDate'?'date':['rooms','annualIncome','capRatePct'].includes(key)?'number':'text'} value={draft[key]} step={key==='rooms'?'1':key==='capRatePct'?'0.0001':'0.01'} maxLength={key==='name'?160:500} onChange={e=>setDraft(old=>({...old,[key]:e.target.value}))} className={css}/></label>;
 function update(id:string,patch:Partial<DraftComparable>){setComparables(old=>old.map(c=>c.id===id?{...c,...patch}:c))}
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 [overflow-wrap:anywhere]"><Breadcrumbs/><h1 className="mt-3 text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-sm text-muted">{t('scope')}</p><section className="mt-6 rounded-xl border border-card-border bg-card p-4"><div className="grid gap-4 sm:grid-cols-2">{field('name')}{field('valuationDate')}{field('rooms')}{field('rightsReference')}</div><p className="mt-4 text-sm text-muted">{t('rightsScope')}</p><div className="mt-4 flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm"><input id="hotel-value-income" type="checkbox" checked={incomeEnabled} onChange={e=>setIncomeEnabled(e.target.checked)}/>{t('incomeEnabled')}</label><label className="flex items-center gap-2 text-sm"><input id="hotel-value-comparison" type="checkbox" checked={comparisonEnabled} onChange={e=>setComparisonEnabled(e.target.checked)}/>{t('comparisonEnabled')}</label></div></section>
 {incomeEnabled&&<section className="mt-6 rounded-xl border border-card-border bg-card p-4"><h2 className="text-lg font-semibold text-navy">{t('incomeEnabled')}</h2><p className="mt-3 text-sm text-muted">{t('incomeScope')}</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{field('annualIncome')}{field('incomeReference')}{field('capRatePct')}{field('rateReference')}</div></section>}
 {comparisonEnabled&&<section className="mt-6"><h2 className="text-lg font-semibold text-navy">{t('comparisonEnabled')}</h2><p className="mt-3 text-sm text-muted">{t('comparisonScope')}</p><div className="mt-4 space-y-4">{comparables.map((c,i)=><section key={c.id} data-hotel-comparable={c.id} className="min-w-0 rounded-xl border border-card-border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{t('comparable')} {i+1}</h3><button type="button" onClick={()=>setComparables(old=>old.filter(row=>row.id!==c.id))} className="text-sm text-rose-700 underline">{t('remove')}</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{(['name','date','price','rooms','adjustmentPct','adjustmentReference','weight','reference'] as const).map(key=><label key={key} className="min-w-0 text-sm">{t(key)}<input data-field={key} type={key==='date'?'date':['price','rooms','adjustmentPct','weight'].includes(key)?'number':'text'} value={c[key]} step={key==='rooms'?'1':'0.01'} maxLength={key==='name'?160:500} onChange={e=>update(c.id,{[key]:e.target.value})} className={css}/></label>)}</div></section>)}</div><button id="hotel-value-add" type="button" disabled={comparables.length>=50} onClick={()=>setComparables(old=>[...old,blank(crypto.randomUUID())])} className="mt-4 rounded-lg border border-card-border px-4 py-2 text-sm disabled:opacity-50">{t('add')}</button></section>}
 {!result?<p role="status" className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{t('invalid')}</p>:<section data-hotel-value-results className="mt-8"><h2 className="text-xl font-semibold text-navy">{t('result')}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{incomeEnabled&&<div className="rounded-xl border border-card-border bg-card p-4"><h3 className="text-sm">{t('incomeValue')}</h3><p data-hotel-value="incomeValue" className="mt-2 text-2xl font-semibold">{result.incomeValue===null?'—':fmt(result.incomeValue)+' €'}</p>{result.incomeValue===null&&<p className="mt-3 text-sm text-muted">{t('noIncomeValue')}</p>}</div>}{comparisonEnabled&&<div className="rounded-xl border border-card-border bg-card p-4"><h3 className="text-sm">{t('comparisonValue')}</h3><p data-hotel-value="comparisonValue" className="mt-2 text-2xl font-semibold">{fmt(result.comparisonValue!)} €</p><p className="mt-3 text-sm">{t('selectedPricePerRoom')}: <span data-hotel-value="selectedPricePerRoom">{fmt(result.selectedPricePerRoom!)} €</span></p></div>}</div>{comparisonEnabled&&<div className="mt-4 overflow-x-auto rounded-lg border border-card-border"><table className="w-full min-w-[650px] text-sm"><thead><tr>{['comparable','pricePerRoom','adjustedPricePerRoom','normalizedWeight'].map(k=><th key={k} className="p-3 text-left">{t(k)}</th>)}</tr></thead><tbody>{result.comparables.map(c=><tr key={c.id} className="border-t border-card-border"><td className="p-3">{c.name}</td><td className="whitespace-nowrap p-3">{fmt(c.pricePerRoom)} €</td><td className="whitespace-nowrap p-3">{fmt(c.adjustedPricePerRoom)} €</td><td className="p-3">{fmt(c.normalizedWeight)} %</td></tr>)}</tbody></table></div>}<button id="hotel-value-csv" type="button" className="mt-4 rounded-lg border border-card-border px-4 py-2 text-sm" onClick={()=>{const url=URL.createObjectURL(new Blob([hotelValueCsv(input)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='hotel-valuation.csv';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}}>{t('csv')}</button></section>}
 <a href="https://ww3.rics.org/uk/en/journals/property-journal/valuation-approaches-methods-models.html" target="_blank" rel="noopener noreferrer" className="mt-6 block text-sm underline">{t('source')}</a><RelatedTools keys={['hotelExploitation','valorisation','hotelDscr']}/></main>;
}
