"use client";
import {Document,Page,Text,View,Link,pdf} from '@react-pdf/renderer';
import {calculateConstructionBudget,type ConstructionBudgetInput} from '@/lib/construction-budget';
export type ConstructionBudgetPdfParams={input:ConstructionBudgetInput;locale:string;labels:Record<string,string>};
function BudgetDocument({input,locale,labels:t}:ConstructionBudgetPdfParams){
 const result=calculateConstructionBudget(input),number=(n:number,d=2)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:d,maximumFractionDigits:d}).replace(/[\u00a0\u202f]/g,' '),money=(n:number)=>number(n)+' €';
 const page={fontFamily:'Helvetica',fontSize:10,paddingTop:40,paddingBottom:50,paddingHorizontal:40,color:'#1B2A4A'},note={fontSize:9,lineHeight:1.4,marginTop:8,color:'#475569'},heading={fontSize:14,fontWeight:700,marginTop:18,marginBottom:10};
 const footer=<View fixed style={{position:'absolute',left:40,right:40,bottom:24,flexDirection:'row',justifyContent:'space-between',borderTop:'0.5pt solid #ddd',paddingTop:5}}><Text style={{fontSize:8}}>tevaxia.lu</Text><Text style={{fontSize:8}} render={({pageNumber,totalPages})=>`${pageNumber} / ${totalPages}`}/></View>;
 return <Document><Page size="A4" style={page}><Text style={{fontSize:22,fontWeight:700}} hyphenationCallback={word=>[word]}>{t.title}</Text><Text style={note}>{t.scope}</Text><Text style={heading}>{t.resultTitle}</Text>
  {([['worksTtc','works'],['feesTtc','fees'],['contingencyTtc','contingencyAmount'],['totalTtc','total']] as const).map(([key,label])=><View key={key} style={{flexDirection:'row',justifyContent:'space-between',paddingVertical:10,borderBottom:'0.5pt solid #ddd'}}><Text style={{width:'65%'}}>{t[label]}</Text><Text style={{fontWeight:700}}>{money(result[key])}</Text></View>)}
  <Text style={note}>{t.partial}</Text><Text style={heading}>{t.contingency}</Text><Text>{number(input.contingencyPct)} %</Text><Text style={note}>{t.contingencyScope}</Text>{input.contingencyReason&&<Text style={note}>{t.reason}: {input.contingencyReason}</Text>}
  {input.surfaceM2!==null&&<><Text style={heading}>{t.surface}</Text><Text>{number(input.surfaceM2,4)} m²</Text><Text style={note}>{t.perM2}: {money(result.costPerM2!)} / m²</Text></>}{footer}
 </Page><Page size="A4" style={page}><Text style={heading}>{t.title}</Text>{result.lines.map((line,i)=><View key={line.id} wrap={false} style={{marginTop:12,paddingBottom:12,borderBottom:'0.5pt solid #ddd'}}><Text style={{fontSize:12,fontWeight:700}}>{i+1}. {line.label}</Text><Text style={note}>{t.kind}: {t[line.kind]}</Text><Text style={note}>{t.quantity}: {number(line.quantity,4)} {line.unit==='unit'?t.lump:line.unit==='m2'?'m²':line.unit==='m3'?'m³':line.unit} · {t.unitPrice}: {money(line.unitPriceTtc)}</Text><Text style={{marginTop:6,fontWeight:700}}>{t.total}: {money(line.totalTtc)}</Text><Text style={note}>{t.reference}: {line.reference}</Text></View>)}{footer}</Page><Page size="A4" style={page}><Text style={heading}>{t.title}</Text><Text style={note}>{t.scope}</Text><Text style={note}>{t.partial}</Text><Text style={note}>{t.contingencyScope}</Text><Text style={note}>{t.indexScope}</Text><Link style={{...note,color:'#1B2A4A'}} src="https://statistiques.public.lu/fr/donnees/methodologie/methodes/economie-totale-prix/prix-construction.html">{t.source}</Link>{footer}</Page></Document>;
}
export async function generateConstructionBudgetPdfBlob(params:ConstructionBudgetPdfParams):Promise<Blob>{return pdf(<BudgetDocument {...params}/>).toBlob()}
