"use client";
import {Document,Page,Text,View,Link,pdf} from '@react-pdf/renderer';
import {calculateDevelopment,DEVELOPMENT_SOURCES,type DevelopmentInput} from '@/lib/development-appraisal';
export type DevelopmentPdfParams={input:DevelopmentInput;locale:string;labels:Record<string,string>};
function DevelopmentDocument({input,locale,labels:t}:DevelopmentPdfParams){
 const r=calculateDevelopment(input),fmt=(n:number)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:2,maximumFractionDigits:2}).replace(/[\u00a0\u202f]/g,' '),money=(n:number)=>fmt(n)+' €';
 const page={fontFamily:'Helvetica',fontSize:10,paddingTop:40,paddingBottom:50,paddingHorizontal:40,color:'#1B2A4A'},note={fontSize:9,lineHeight:1.4,marginTop:8,color:'#475569'},heading={fontSize:15,fontWeight:700,marginTop:14,marginBottom:10};
 const footer=<View fixed style={{position:'absolute',left:40,right:40,bottom:24,flexDirection:'row',justifyContent:'space-between',borderTop:'0.5pt solid #ddd',paddingTop:5}}><Text style={{fontSize:8}}>tevaxia.lu</Text><Text style={{fontSize:8}} render={({pageNumber,totalPages})=>`${pageNumber} / ${totalPages}`}/></View>;
 const metrics: [string,number|null][]=[['revenue',r.totals.revenue],['costs',r.costs],['target',r.target],...(input.mode==='known'?[['landCost',r.landPrice],['acquisition',r.acquisition],['profit',r.profit],['headroom',r.headroom]] as [string,number|null][]:[['residualBudget',r.residualBudget],['landCapacity',r.landCapacity]] as [string,number|null][])];
 return <Document><Page size="A4" style={page}><Text style={{fontSize:22,fontWeight:700}}>{t.title}</Text><Text style={heading}>{input.name}</Text><Text style={note}>{t.scope}</Text><Text style={heading}>{t[input.mode]}</Text>{metrics.map(([key,value])=><View key={key} style={{flexDirection:'row',justifyContent:'space-between',paddingVertical:8,borderBottom:'0.5pt solid #ddd'}}><Text style={{width:'65%'}}>{t[key]}</Text><Text>{value===null?'—':money(value)}</Text></View>)}{r.profitPct!==null&&<Text style={note}>{t.profitPct}: {fmt(r.profitPct)} %</Text>}{input.mode==='residual'&&<Text style={note}>{t.residualScope}</Text>}{r.landCapacity===null&&input.mode==='residual'&&<Text style={note}>{t.unfunded}</Text>}{footer}</Page>
 <Page size="A4" style={page}><Text style={heading}>{t.lines}</Text>{input.lines.map((l,i)=><View key={l.id} wrap={false} style={{marginTop:10,paddingBottom:10,borderBottom:'0.5pt solid #ddd'}}><Text style={{fontSize:12,fontWeight:700}}>{i+1}. {l.label}</Text><Text style={note}>{t[l.kind]} · {t.month}: {l.month} · {money(l.amount)}</Text><Text style={note}>{t.reference}: {l.reference}</Text></View>)}{footer}</Page>
 <Page size="A4" style={page}><Text style={heading}>{t.mode}: {t[input.mode]}</Text><Text style={note}>{t.taxReference}: {input.taxReference}</Text><Text style={note}>{t.taxScope}</Text><Text style={note}>{t.targetPct}: {fmt(input.targetPct)} %</Text><Text style={note}>{t.targetReference}: {input.targetReference}</Text>{input.mode==='known'&&<><Text style={note}>{t.landPrice}: {money(input.landPrice!)}</Text><Text style={note}>{t.landReference}: {input.landReference}</Text></>}<Text style={note}>{t.landMonth}: {input.landMonth}</Text><Text style={note}>{t.acquisitionFixed}: {money(input.acquisitionFixed)}</Text><Text style={note}>{t.acquisitionPct}: {fmt(input.acquisitionPct)} %</Text><Text style={note}>{t.acquisitionReference}: {input.acquisitionReference}</Text><Text style={note}>{t.costScope}</Text><Link style={note} src={DEVELOPMENT_SOURCES.rics}>{t.source}</Link><Link style={note} src={DEVELOPMENT_SOURCES.vefa}>{t.vefaSource}</Link>{footer}</Page>
 {input.mode==='known'&&<Page size="A4" style={page}><Text style={heading}>{t.timeline}</Text><Text style={note}>{t.timingScope}</Text><Text style={note}>{t.maximumBudgetDeficit}: {money(r.maximumBudgetDeficit!)}</Text>{r.timeline.map(m=><View key={m.month} wrap={false} style={{marginTop:10,paddingBottom:8,borderBottom:'0.5pt solid #ddd'}}><Text style={{fontWeight:700}}>{t.month}: {m.month}</Text><Text style={note}>{t.revenue}: {money(m.revenue)} · {t.outflows}: {money(m.costs)}</Text><Text style={note}>{t.net}: {money(m.net)} · {t.cumulative}: {money(m.cumulative)}</Text><Text style={note}>{t.beforeReceipts}: {money(m.beforeReceipts)}</Text></View>)}{footer}</Page>}
 </Document>;
}
export async function generateDevelopmentPdfBlob(params:DevelopmentPdfParams):Promise<Blob>{return pdf(<DevelopmentDocument {...params}/>).toBlob()}
