"use client";
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {ESG_KEYS,EMPTY_ESG,summarizeEsgDeclarations,calculateEsgSensitivity,type EsgDeclarations,type EsgEvidence} from '@/lib/esg';
export function EsgDossier(){
 const t=useTranslations('esgDossierAudit'),v=useTranslations('valorisation'),locale=useLocale();
 const [i,setInput]=useState<EsgDeclarations>({...EMPTY_ESG}),[epc,setEpc]=useState(''),[certifications,setCertifications]=useState(''),[references,setReferences]=useState('');
 const [value,setValue]=useState(NaN),[adjustment,setAdjustment]=useState(0),[justification,setJustification]=useState('');
 const summary=summarizeEsgDeclarations(i),r=(()=>{try{return calculateEsgSensitivity(value,adjustment,justification)}catch{return null}})();
 const money=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{style:'currency',currency:'EUR'}).format(n);
 const field='mt-2 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2.5';
 return <div id="esg-dossier" className="space-y-6 [overflow-wrap:anywhere]"><h2 className="text-xl font-semibold">{t('title')}</h2><p className="text-muted">{t('intro')}</p><p className="text-sm text-muted">{t('scope')}</p>
 <section className="space-y-5 rounded-xl border border-card-border bg-card p-5"><label className="block text-sm">{t('epc')}<select id="esg-epc" className={field} value={epc} onChange={e=>setEpc(e.target.value)}><option value="">{t('unknown')}</option>{['A+','A','B','C','D','E','F','G','H','I'].map(c=><option key={c}>{c}</option>)}</select></label>
 <div className="grid gap-4 sm:grid-cols-2">{ESG_KEYS.map(k=><label key={k} className="min-w-0 text-sm">{v(k)}<select id={'esg-'+k} className={field} value={i[k]} onChange={e=>setInput({...i,[k]:e.target.value as EsgEvidence})}>{(['unknown','yes','no'] as const).map(s=><option key={s} value={s}>{t(s)}</option>)}</select></label>)}</div>
 <label className="block text-sm">{t('certifications')}<input id="esg-certifications" className={field} value={certifications} onChange={e=>setCertifications(e.target.value)}/></label><label className="block text-sm">{t('references')}<textarea id="esg-references" rows={3} className={field} value={references} onChange={e=>setReferences(e.target.value)}/></label><p className="text-sm text-muted">{t('referenceNote')}</p>
 <h3 className="font-semibold">{t('summary')}</h3><p>{t('answered')}: <span id="esg-answered">{summary.documented}</span> / 7 — {t('missing')}: <span id="esg-unknown">{summary.unknown}</span></p><p className="text-sm text-muted">{t('countNote')}</p></section>
 <section className="space-y-4 rounded-xl border border-card-border bg-card p-5"><h3 className="text-lg font-semibold">{t('sensitivity')}</h3><p className="text-sm text-muted">{t('sensitivityNote')}</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">{t('value')}<input id="esg-value" type="number" step="any" min={0} className={field} value={Number.isNaN(value)?'':value} onChange={e=>setValue(e.target.valueAsNumber)}/></label><label className="text-sm">{t('adjustment')}<input id="esg-adjustment" type="number" step="any" min={-100} max={100} className={field} value={Number.isNaN(adjustment)?'':adjustment} onChange={e=>setAdjustment(e.target.valueAsNumber)}/></label></div><label className="block text-sm">{t('adjustmentReference')}<textarea id="esg-justification" rows={3} className={field} value={justification} onChange={e=>setJustification(e.target.value)}/></label>
 {r?<dl id="esg-sensitivity" className="grid gap-4 sm:grid-cols-2"><div><dt>{t('change')}</dt><dd id="esg-change" className="text-xl font-semibold">{money(r.change)}</dd></div><div><dt>{t('adjusted')}</dt><dd id="esg-adjusted" className="text-xl font-semibold">{money(r.adjustedValue)}</dd></div></dl>:<p role="status" className="text-sm text-muted">{t('invalid')}</p>}<p className="text-sm text-muted">{t('resultNote')}</p></section>
 <a className="block text-sm underline" href="https://www.rics.org/profession-standards/rics-standards-and-guidance/sector-standards/valuation-standards/esg-and-sustainability-in-commercial-property-valuation">{t('source')}</a></div>;
}
