"use client";
import {useState,useMemo} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {calculerMLV} from '@/lib/valuation';
const fields=['cycle','liquidity','specific'] as const;
export function PrudentialValue({value}:{value:number}){
 const t=useTranslations('prudentialAudit'),locale=useLocale(),[cuts,setCuts]=useState({cycle:0,liquidity:0,specific:0}),[reference,setReference]=useState('');
 const r=useMemo(()=>{if(!reference.trim())return null;try{return calculerMLV({valeurMarche:value,decoteConjoncturelle:cuts.cycle,decoteCommercialisation:cuts.liquidity,decoteSpecifique:cuts.specific})}catch{return null}},[value,cuts,reference]);
 const money=(v:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{style:'currency',currency:'EUR'}).format(v);
 return <div id="prudential-value" className="space-y-5 [overflow-wrap:anywhere]"><h2 className="text-xl font-semibold">{t('title')}</h2><p>{t('scope')}</p><p className="text-sm text-muted">{t('regulation')}</p><section className="rounded-xl border border-card-border bg-card p-5 space-y-4"><p>{t('base')} : <strong id="prudential-base">{value>0?money(value):'—'}</strong></p><p className="text-sm text-muted">{t('baseNote')}</p><div className="grid gap-4 sm:grid-cols-3">{fields.map(k=><label className="text-sm" key={k}>{t(k)} (%)<input id={'prudential-'+k} type="number" min={0} max={100} step="any" value={Number.isNaN(cuts[k])?'':cuts[k]} onChange={e=>setCuts({...cuts,[k]:e.target.valueAsNumber})} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5"/></label>)}</div><label className="block text-sm">{t('reference')}<textarea id="prudential-reference" value={reference} onChange={e=>setReference(e.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5"/></label><p className="text-sm text-muted">{t('formula')}</p></section>{r?<section id="prudential-results" className="rounded-xl border border-card-border bg-card p-5 space-y-3"><p>{t('cut')} : <strong id="prudential-cut">{money(r.totalDecotes)}</strong></p><p>{t('result')} : <strong id="prudential-result">{money(r.mlv)}</strong></p><p className="text-sm text-muted">{t('noTransfer')}</p></section>:<p role="status">{t('invalid')}</p>}<p className="text-sm text-muted">{t('weights')}</p><a className="block underline text-sm" href="https://eur-lex.europa.eu/eli/reg/2024/1623/oj">{t('source')}</a></div>;
}
