"use client";
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import type {ReconciliationResult} from '@/lib/valuation';
export type ReconciliationWeights={comparison:number;capitalisation:number;dcf:number};
const rows=[{key:'comparison',label:'tabComparaison',name:'Comparaison'},{key:'capitalisation',label:'tabCapitalisation',name:'Capitalisation'},{key:'dcf',label:'tabDCF',name:'DCF'}] as const;
export function ReconciliationPanel({values,weights,onWeights,result}:{values:ReconciliationWeights;weights:ReconciliationWeights;onWeights:(v:ReconciliationWeights)=>void;result:ReconciliationResult|null}){
 const t=useTranslations('reconciliationAudit'),v=useTranslations('valorisation'),locale=useLocale(),[low,setLow]=useState(0),[high,setHigh]=useState(0),[note,setNote]=useState('');
 const money=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{style:'currency',currency:'EUR'}).format(n),num=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{maximumFractionDigits:4}).format(n);
 const ready=result&&result.methodes.length>0,scenarioValid=[low,high].every(n=>Number.isFinite(n)&&n>=0&&n<=100);
 return <div id="reconciliation-panel" className="space-y-5 [overflow-wrap:anywhere]"><h2 className="text-xl font-semibold">{t('title')}</h2><p>{t('scope')}</p><p className="text-sm text-muted">{t('weights')}</p><section className="rounded-xl border border-card-border bg-card p-5 space-y-4">{rows.map(row=><div key={row.key} className="grid gap-3 sm:grid-cols-[1fr_10rem]"><div><div className="text-sm font-medium">{v(row.label)}</div><div id={'reconciliation-value-'+row.key} className="font-semibold">{values[row.key]>0?money(values[row.key]):'—'}</div></div><label className="text-sm">{t('weight')}<input id={'reconciliation-weight-'+row.key} type="number" min={0} max={100} step="any" value={Number.isNaN(weights[row.key])?'':weights[row.key]} onChange={e=>onWeights({...weights,[row.key]:e.target.valueAsNumber})} className="mt-1 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2"/></label></div>)}<label className="block text-sm">{t('note')}<textarea value={note} onChange={e=>setNote(e.target.value)} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2" rows={3}/></label><p className="text-sm text-muted">{t('noteScope')}</p></section>{ready?<section id="reconciliation-results" className="rounded-xl border border-card-border bg-card p-5 space-y-4"><h3>{t('result')}</h3><p id="reconciliation-result" className="text-3xl font-bold">{money(result.valeurReconciliee)}</p><dl className="space-y-2">{result.methodes.map(m=><div key={m.nom} className="grid gap-1 sm:grid-cols-[1fr_auto]"><dt>{v(rows.find(row=>row.name===m.nom)!.label)} — {num(m.poidsEffectif)} %</dt><dd>{money(m.contribution)}</dd></div>)}</dl><p className="text-sm text-muted">{t('transfer')}</p>{result.methodes.length>1&&<><p>{t('gap')} : {num(result.ecartMaxPct)} %</p><p>{t('dispersion')} : {money(result.ecartType)}</p><p className="text-sm text-muted">{t('dispersionNote')}</p></>}</section>:<p id="reconciliation-invalid" role="status">{t('invalid')}</p>}<section className="rounded-xl border border-card-border bg-card p-5 space-y-4"><h3 className="text-lg font-semibold">{t('scenario')}</h3><p className="text-sm text-muted">{t('scenarioNote')}</p><div className="grid gap-4 sm:grid-cols-2">{[{key:'low',label:t('low'),value:low,set:setLow},{key:'high',label:t('high'),value:high,set:setHigh}].map(row=><label key={row.key} className="text-sm">{row.label} (%)<input id={'reconciliation-'+row.key} type="number" min={0} max={100} step="any" value={Number.isNaN(row.value)?'':row.value} onChange={e=>row.set(e.target.valueAsNumber)} className="mt-1 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2"/></label>)}</div>{ready&&scenarioValid?<p id="reconciliation-scenario">{money(result.valeurReconciliee*(1-low/100))} — {money(result.valeurReconciliee*(1+high/100))}</p>:<p>{t('scenarioInvalid')}</p>}</section></div>;
}
