"use client";
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {calculerResiduelleEnergetique} from '@/lib/valuation';
const KEYS=['value','works','fees','finance','margin','grant'] as const;
export function RenovationResidual(){
 const t=useTranslations('renovationResidualAudit'),locale=useLocale(),[i,setInput]=useState({value:NaN,works:NaN,fees:0,finance:0,margin:0,grant:0}),[reference,setReference]=useState('');
 const r=(()=>{try{if(!reference.trim())return null;return calculerResiduelleEnergetique({classeActuelle:'',classeCible:'',valeurApresRenovation:i.value,coutTravauxRenovation:i.works,honorairesEtudes:i.fees,fraisFinancement:i.finance,margePrudentielle:i.margin,aidesPrevues:i.grant})}catch{return null}})();
 const money=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{style:'currency',currency:'EUR'}).format(n),pct=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{maximumFractionDigits:2}).format(n)+' %';
 return <div id="renovation-residual" className="space-y-6 [overflow-wrap:anywhere]"><h2 className="text-xl font-semibold">{t('title')}</h2><p className="text-muted">{t('intro')}</p><p className="text-sm text-muted">{t('scope')}</p><section className="space-y-4 rounded-xl border border-card-border bg-card p-5"><div className="grid gap-4 sm:grid-cols-2">{KEYS.map(k=><label className="text-sm" key={k}>{t(k)}<input id={'residual-'+k} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5" type="number" min={0} max={k==='margin'?100:1e12} step="any" value={Number.isNaN(i[k])?'':i[k]} onChange={e=>setInput({...i,[k]:e.target.valueAsNumber})}/></label>)}</div><p className="text-sm text-muted">{t('costNote')}</p><p className="text-sm text-muted">{t('grantNote')}</p><label className="block text-sm">{t('reference')}<textarea id="residual-reference" rows={3} value={reference} onChange={e=>setReference(e.target.value)} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5"/></label></section>
 {r?<section id="residual-results" className="space-y-4 rounded-xl border border-card-border bg-card p-5"><h3 className="text-lg font-semibold">{t('result')}</h3><dl className="space-y-3">{[{key:'value',value:r.valeurApresRenovation},{key:'brut',value:r.coutTotalBrut},{key:'reserve',value:r.margePrudentielleMontant},{key:'budget',value:r.coutTotalAvecMarge},{key:'grant',value:r.aidesDeduites},{key:'net',value:r.coutNetApresAides},{key:'residual',value:r.valeurResiduelle}].map(row=><div key={row.key} className="grid gap-1 border-t border-card-border pt-3 sm:grid-cols-[1fr_auto]"><dt>{t(row.key)}</dt><dd id={'residual-result-'+row.key} className="font-semibold">{money(row.value)}</dd></div>)}<div className="grid gap-1 sm:grid-cols-[1fr_auto]"><dt>{t('costShare')}</dt><dd>{pct(r.decoteEnergetiquePct)}</dd></div></dl>{r.valeurResiduelle<0&&<p id="residual-negative" className="font-medium">{t('negative')}</p>}<p className="text-sm text-muted">{t('resultNote')}</p></section>:<p role="status" className="text-sm text-muted">{t('invalid')}</p>}
 <a className="block text-sm underline" href="https://guichet.public.lu/fr/citoyens/logement/acquisition/performances-energie/demande-passeport-energetique.html">{t('source')}</a></div>;
}
