"use client";
import {useState,useMemo,useEffect} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {calculerTermeReversion} from '@/lib/valuation';
const KEYS=['rent','erv','years','termRate','reversionRate'] as const;
export function TermReversion({onValue}:{onValue:(value:number)=>void}){
 const t=useTranslations('termReversionAudit'),locale=useLocale(),[i,setInput]=useState({rent:36000,erv:42000,years:5,termRate:4,reversionRate:5}),[reference,setReference]=useState('');
 const r=useMemo(()=>{try{return calculerTermeReversion({loyerEnPlace:i.rent,erv:i.erv,dureeRestanteBail:i.years,tauxTerme:i.termRate/100,tauxReversion:i.reversionRate/100})}catch{return null}},[i]);
 useEffect(()=>{onValue(r?.valeur??0)},[onValue,r?.valeur]);
 const number=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{maximumFractionDigits:4}).format(n),money=(n:number)=>new Intl.NumberFormat(locale==='lb'?'de-DE':locale,{style:'currency',currency:'EUR'}).format(n);
 const gap=i.rent>0?(i.erv-i.rent)/i.rent*100:null;
 return <div id="term-reversion" className="space-y-6 [overflow-wrap:anywhere]"><h2 className="text-xl font-semibold">{t('title')}</h2><p className="text-muted">{t('intro')}</p><p className="text-sm text-muted">{t('scope')}</p><section className="space-y-4 rounded-xl border border-card-border bg-card p-5"><div className="grid gap-4 sm:grid-cols-2">{KEYS.map(k=><label key={k} className="text-sm">{t(k)}<input id={'term-'+k} type="number" min={0} max={k==='rent'||k==='erv'?1e12:100} step={k==='years'?1:'any'} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5" value={Number.isNaN(i[k])?'':i[k]} onChange={e=>setInput({...i,[k]:e.target.valueAsNumber})}/></label>)}</div><label className="block text-sm">{t('reference')}<textarea value={reference} onChange={e=>setReference(e.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-input-border bg-input-bg px-3 py-2.5"/></label></section>
 {r?<section id="term-results" className="space-y-4 rounded-xl border border-card-border bg-card p-5"><h3 className="text-lg font-semibold">{t('result')}</h3><dl className="space-y-3">{[{key:'termValue',value:r.valeurTerme},{key:'reversionValue',value:r.valeurReversion},{key:'value',value:r.valeur}].map(row=><div key={row.key} className="grid gap-1 sm:grid-cols-[1fr_auto]"><dt>{t(row.key)}</dt><dd id={'term-result-'+row.key} className="font-semibold">{money(row.value)}</dd></div>)}{[{key:'equivalent',value:r.rendementEquivalent},{key:'reversionary',value:r.rendementReversionnaire},{key:'initial',value:r.rendementInitialSimple}].map(row=><div key={row.key} className="grid gap-1 border-t border-card-border pt-3 sm:grid-cols-[1fr_auto]"><dt>{t(row.key)}</dt><dd id={'term-result-'+row.key} className="font-semibold">{number(row.value*100)} %</dd></div>)}<div className="grid gap-1 sm:grid-cols-[1fr_auto]"><dt>{t('gap')}</dt><dd id="term-gap">{gap===null?t('undefined'):gap===0?t('same'):number(gap)+' %'}</dd></div></dl><p className="text-sm text-muted">{t('explanation')}</p><p className="text-sm text-muted">{t('transfer')}</p></section>:<p role="status" className="text-sm text-muted">{t('invalid')}</p>}
 <a className="block text-sm underline" href="https://ww3.rics.org/uk/en/journals/property-journal/apc-valuation-competency-advice.html">{t('source')}</a></div>;
}
