"use client";
import {useMemo,useState} from 'react';
import {useLocale,useTranslations,useMessages} from 'next-intl';
import {calculateDevelopment,developmentCsv,parseDevelopmentSnapshot,DEVELOPMENT_SOURCES,type DevelopmentInput,type DevelopmentLine} from '@/lib/development-appraisal';
import {PdfButton} from '@/components/PdfButton';
import Breadcrumbs from '@/components/Breadcrumbs';
import RelatedTools from '@/components/RelatedTools';
type DraftLine=Omit<DevelopmentLine,'amount'|'month'>&{amount:string;month:string};
type Draft=Omit<DevelopmentInput,'lines'|'targetPct'|'landPrice'|'landMonth'|'acquisitionFixed'|'acquisitionPct'>&{lines:DraftLine[];targetPct:string;landPrice:string;landMonth:string;acquisitionFixed:string;acquisitionPct:string};
const blank=(id:string,kind:DevelopmentLine['kind']='works'):DraftLine=>({id,kind,label:'',amount:'',month:'',reference:''});
const initial:Draft={version:1,name:'',mode:'known',lines:[blank('line-1','revenue'),blank('line-2')],targetPct:'',targetReference:'',landPrice:'',landMonth:'',landReference:'',acquisitionFixed:'',acquisitionPct:'',acquisitionReference:'',taxReference:''};
const number=(s:string)=>s.trim()?Number(s):NaN;
function toDraft(i:DevelopmentInput):Draft{return {...i,targetPct:String(i.targetPct),landPrice:i.landPrice===null?'':String(i.landPrice),landMonth:String(i.landMonth),acquisitionFixed:String(i.acquisitionFixed),acquisitionPct:String(i.acquisitionPct),lines:i.lines.map(l=>({...l,amount:String(l.amount),month:String(l.month)}))}}
export default function BilanPromoteur(){
 const t=useTranslations('developmentAppraisal'),locale=useLocale(),messages=useMessages(),[draft,setDraft]=useState<Draft>(initial),[notice,setNotice]=useState<'importError'|'importSuccess'|null>(null);
 const input=useMemo<DevelopmentInput>(()=>({...draft,targetPct:number(draft.targetPct),landPrice:draft.mode==='known'?number(draft.landPrice):null,landMonth:number(draft.landMonth),acquisitionFixed:number(draft.acquisitionFixed),acquisitionPct:number(draft.acquisitionPct),lines:draft.lines.map(l=>({...l,amount:number(l.amount),month:number(l.month)}))}),[draft]);
 const result=useMemo(()=>{try{return calculateDevelopment(input)}catch{return null}},[input]);
 const fmt=(n:number)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:2,maximumFractionDigits:2}),money=(n:number)=>fmt(n)+' €';
 const css='mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2 text-sm';
 function field(key:Exclude<keyof Draft,'lines'|'version'|'mode'>,numeric=false){return <label className="min-w-0 text-sm" key={key}>{t(key)}<input id={'development-'+key} type={numeric?'number':'text'} value={draft[key]} min={numeric?'0':undefined} step={numeric?'any':undefined} maxLength={key==='name'?160:500} onChange={e=>setDraft(old=>({...old,[key]:e.target.value}))} className={css}/></label>}
 function update(id:string,patch:Partial<DraftLine>){setDraft(old=>({...old,lines:old.lines.map(l=>l.id===id?{...l,...patch}:l)}))}
 function download(text:string,type:string,filename:string){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const keys=(draft.mode==='known'?['costs','landPrice','acquisition','profit','profitPct','target','headroom']:['costs','target','residualBudget','landCapacity']) as ('costs'|'landPrice'|'acquisition'|'profit'|'profitPct'|'target'|'headroom'|'residualBudget'|'landCapacity')[];
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 [overflow-wrap:anywhere]"><Breadcrumbs/><h1 className="mt-3 text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-sm text-muted">{t('scope')}</p>
 <section className="mt-6 rounded-xl border border-card-border bg-card p-4"><div className="grid gap-4 sm:grid-cols-2">{field('name')}<label className="text-sm">{t('mode')}<select id="development-mode" value={draft.mode} onChange={e=>setDraft(old=>({...old,mode:e.target.value as Draft['mode']}))} className={css}><option value="known">{t('known')}</option><option value="residual">{t('residual')}</option></select></label>{field('taxReference')}{field('targetPct',true)}{field('targetReference')}{draft.mode==='known'&&field('landPrice',true)}{field('landMonth',true)}{draft.mode==='known'&&field('landReference')}{field('acquisitionFixed',true)}{field('acquisitionPct',true)}{field('acquisitionReference')}</div><p className="mt-4 text-sm text-muted">{t('taxScope')}</p></section>
 <h2 className="mt-6 text-lg font-semibold text-navy">{t('lines')}</h2><p className="mt-2 text-sm text-muted">{t('costScope')}</p>
 <div className="mt-4 space-y-4">{draft.lines.map((line,i)=><section key={line.id} data-development-line={line.id} className="min-w-0 rounded-xl border border-card-border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{t('line')} {i+1}</h3><button type="button" onClick={()=>setDraft(old=>({...old,lines:old.lines.filter(l=>l.id!==line.id)}))} className="text-sm text-rose-700 underline">{t('remove')}</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="min-w-0 text-sm">{t('label')}<input data-field="label" value={line.label} maxLength={160} onChange={e=>update(line.id,{label:e.target.value})} className={css}/></label><label className="min-w-0 text-sm">{t('kind')}<select data-field="kind" value={line.kind} onChange={e=>update(line.id,{kind:e.target.value as DraftLine['kind']})} className={css}>{(['revenue','works','fees','finance','contingency'] as const).map(k=><option key={k} value={k}>{t(k)}</option>)}</select></label><label className="min-w-0 text-sm">{t('amount')}<input data-field="amount" type="number" min="0" max="1000000000" step="0.01" value={line.amount} onChange={e=>update(line.id,{amount:e.target.value})} className={css}/></label><label className="min-w-0 text-sm">{t('month')}<input data-field="month" type="number" min="1" max="120" step="1" value={line.month} onChange={e=>update(line.id,{month:e.target.value})} className={css}/></label><label className="min-w-0 text-sm sm:col-span-2">{t('reference')}<input data-field="reference" value={line.reference} maxLength={500} onChange={e=>update(line.id,{reference:e.target.value})} className={css}/></label></div></section>)}</div>
 <button id="development-add" type="button" disabled={draft.lines.length>=200} onClick={()=>setDraft(old=>({...old,lines:[...old.lines,blank(crypto.randomUUID())]}))} className="mt-4 rounded-lg border border-card-border px-4 py-2 text-sm disabled:opacity-50">{t('add')}</button>
 {!result?<p role="status" className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{t('invalid')}</p>:<section data-development-results className="mt-8"><h2 className="text-xl font-semibold text-navy">{t('result')}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-xl border border-card-border bg-card p-4"><h3 className="text-sm">{t('revenue')}</h3><p data-development-total="revenue" className="mt-2 text-xl font-semibold">{money(result.totals.revenue)}</p></div>{keys.map(key=><div key={key} className="min-w-0 rounded-xl border border-card-border bg-card p-4"><h3 className="text-sm">{t(key)}</h3><p data-development-total={key} className="mt-2 text-xl font-semibold">{result[key]===null?'—':key==='profitPct'?fmt(result[key])+' %':money(result[key])}</p></div>)}</div>{draft.mode==='residual'&&<><p className="mt-4 text-sm text-muted">{t('residualScope')}</p>{result.landCapacity===null&&<p className="mt-3 text-sm text-rose-700">{t('unfunded')}</p>}</>}
 {draft.mode==='known'&&<><h2 className="mt-6 text-lg font-semibold">{t('timeline')}</h2><p className="mt-2 text-sm text-muted">{t('timingScope')}</p><p className="mt-3 text-sm font-semibold">{t('maximumBudgetDeficit')}: <span data-development-total="maximumBudgetDeficit">{money(result.maximumBudgetDeficit!)}</span></p><div className="mt-4 overflow-x-auto rounded-lg border border-card-border"><table className="w-full min-w-[700px] text-sm"><thead><tr>{['month','revenue','outflows','net','cumulative','beforeReceipts'].map(k=><th key={k} className="p-3 text-left">{t(k)}</th>)}</tr></thead><tbody>{result.timeline.map(m=><tr key={m.month} data-development-month={m.month} className="border-t border-card-border"><td className="p-3">{m.month}</td>{(['revenue','costs','net','cumulative','beforeReceipts'] as const).map(k=><td key={k} data-value={k} className="whitespace-nowrap p-3">{money(m[k])}</td>)}</tr>)}</tbody></table></div></>}
 <div className="mt-6 flex flex-wrap gap-3"><button id="development-csv" type="button" onClick={()=>download(developmentCsv(input),'text/csv;charset=utf-8','bilan-promoteur.csv')} className="rounded-lg border border-card-border px-4 py-2 text-sm">{t('exportCsv')}</button><button id="development-json" type="button" onClick={()=>download(JSON.stringify(input,null,2),'application/json','bilan-promoteur.json')} className="rounded-lg border border-card-border px-4 py-2 text-sm">{t('exportJson')}</button><PdfButton label={t('pdf')} filename="bilan-promoteur.pdf" generateBlob={async()=>{const {generateDevelopmentPdfBlob}=await import('@/components/DevelopmentPdf');return generateDevelopmentPdfBlob({input,locale,labels:messages.developmentAppraisal as Record<string,string>})}}/></div>
 </section>}
 <section className="mt-8 rounded-xl border border-card-border bg-card p-4"><label htmlFor="development-import" className="text-sm font-semibold">{t('importJson')}</label><input id="development-import" type="file" accept=".json,application/json" className="mt-3 block w-full min-w-0 text-sm" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>250000)throw Error('Size');const next=parseDevelopmentSnapshot(await file.text());setDraft(toDraft(next));setNotice('importSuccess')}catch{setNotice('importError')}}}/><p className="mt-3 text-sm text-muted">{t('saveScope')}</p>{notice&&<p role={notice==='importError'?'alert':'status'} className="mt-2 text-sm">{t(notice)}</p>}</section>
 <div className="mt-6 space-y-2 text-sm"><p><a href={DEVELOPMENT_SOURCES.rics} target="_blank" rel="noopener noreferrer" className="underline">{t('source')}</a></p><p><a href={DEVELOPMENT_SOURCES.vefa} target="_blank" rel="noopener noreferrer" className="underline">{t('vefaSource')}</a></p></div><RelatedTools keys={['estimateurConstruction','calculateurVrd','bancaire']}/></main>;
}
