"use client";
import {useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {calculateHotelCoverage,hotelCoverageCsv,type HotelCoverageInput} from '@/lib/hotellerie/coverage';
import Breadcrumbs from '@/components/Breadcrumbs';
import RelatedTools from '@/components/RelatedTools';
const numeric=['principal','annualRatePct','months','monthlyCosts','upfrontCosts','annualCash','target','propertyValue','stressedAnnualCash'] as const;
const fields=['name','principal','annualRatePct','months','monthlyCosts','upfrontCosts','loanReference','annualCash','cashReference','target','targetReference','propertyValue','valueReference','stressedAnnualCash','stressReference'] as const;
type Draft=Record<typeof fields[number],string>;
const initial=Object.fromEntries(fields.map(k=>[k,''])) as Draft;
export default function DscrHotelPage(){
 const t=useTranslations('hotelCoverageEvidence'),locale=useLocale(),[draft,setDraft]=useState<Draft>(initial);
 const input=useMemo(()=>({...draft,...Object.fromEntries(numeric.map(k=>[k,draft[k].trim()?Number(draft[k]):k==='propertyValue'||k==='stressedAnnualCash'?null:NaN]))}) as unknown as HotelCoverageInput,[draft]);
 const result=useMemo(()=>{try{return calculateHotelCoverage(input)}catch{return null}},[input]);
 const fmt=(n:number,d=2)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:d,maximumFractionDigits:d});
 const metrics=['monthlyPayment','monthlyOutflow','annualDebtService','dscr','stressDscr','ltv','capacity','interest','recurringCosts','upfrontCosts','totalRepayment'] as const;
 return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 [overflow-wrap:anywhere]"><Breadcrumbs/><h1 className="mt-3 text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-sm text-muted">{t('scope')}</p><section className="mt-6 rounded-xl border border-card-border bg-card p-4"><div className="grid gap-4 sm:grid-cols-2">{fields.map(key=><label key={key} className="min-w-0 text-sm">{t(key)}<input id={'coverage-'+key} type={(numeric as readonly string[]).includes(key)?'number':'text'} value={draft[key]} step={key==='months'?'1':key==='annualRatePct'||key==='target'?'0.0001':'0.01'} maxLength={key==='name'?160:500} onChange={e=>setDraft(old=>({...old,[key]:e.target.value}))} className="mt-1 w-full min-w-0 rounded-lg border border-input-border bg-input-bg px-3 py-2 text-sm"/></label>)}</div><p className="mt-4 text-sm text-muted">{t('loanScope')}</p><p className="mt-3 text-sm text-muted">{t('cashScope')}</p><p className="mt-3 text-sm text-muted">{t('targetScope')}</p></section>
 {!result?<p role="status" className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{t('invalid')}</p>:<section data-coverage-results className="mt-8"><h2 className="text-xl font-semibold text-navy">{t('result')}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(k=><div key={k} className="min-w-0 rounded-xl border border-card-border bg-card p-4"><h3 className="text-sm">{t(k)}</h3><p data-coverage-total={k} className="mt-2 text-xl font-semibold">{result[k]===null?'—':fmt(result[k],k==='dscr'||k==='stressDscr'?3:2)+(k==='dscr'||k==='stressDscr'?' ×':k==='ltv'?' %':' €')}</p></div>)}</div><h2 className="mt-6 text-lg font-semibold text-navy">{t('schedule')}</h2>{result.years.length===0?<p className="mt-3 text-sm">{t('none')}</p>:<div className="mt-4 overflow-x-auto rounded-lg border border-card-border"><table className="w-full min-w-[1000px] text-sm"><thead><tr>{['year','periodMonths','repaid','interest','recurringCosts','debtService','cash','dscr','stressDscr','remaining'].map(k=><th key={k} className="p-3 text-left">{t(k)}</th>)}</tr></thead><tbody>{result.years.map(y=><tr key={y.year} data-coverage-year={y.year} className="border-t border-card-border"><td className="p-3">{y.year}</td><td data-value="months" className="p-3">{y.months}</td>{(['principal','interest','costs','debtService','cash','dscr','stressDscr','remaining'] as const).map(k=><td data-value={k} key={k} className="whitespace-nowrap p-3">{y[k]===null?'—':fmt(y[k],k==='dscr'||k==='stressDscr'?3:2)+(k==='dscr'||k==='stressDscr'?' ×':' €')}</td>)}</tr>)}</tbody></table></div>}<button id="coverage-csv" type="button" className="mt-4 rounded-lg border border-card-border px-4 py-2 text-sm" onClick={()=>{const url=URL.createObjectURL(new Blob([hotelCoverageCsv(input)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='hotel-debt-coverage.csv';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}}>{t('csv')}</button></section>}
 <a href="https://www.eba.europa.eu/activities/single-rulebook/regulatory-activities/credit-risk/guidelines-loan-origination-and-monitoring?version=2020" target="_blank" rel="noopener noreferrer" className="mt-6 block text-sm underline">{t('source')}</a><RelatedTools keys={['hotelExploitation','hotelValorisation','bancaire']}/></main>;
}
