const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, '..', 'src', 'messages', 'fr.json');
const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

data.valorisation.seo = {
  faqTitle: "Questions fréquentes sur la valorisation immobilière",
  relatedTitle: "Outils complémentaires",
  evs2025Title: "Évaluation immobilière conforme EVS 2025 au Luxembourg",
  evs2025Content: "<p>Les <strong>European Valuation Standards (EVS) 2025</strong>, publiés par TEGoVA, constituent le cadre de référence pour toute évaluation immobilière professionnelle au Luxembourg. La CSSF, dans sa circulaire 21/773, impose aux établissements de crédit de recourir à des évaluations conformes aux standards européens pour les biens immobiliers acceptés en garantie.</p><p>Au Luxembourg, la valeur de marché (Market Value) est définie comme le prix le plus probable auquel un bien serait vendu, à la date de l'évaluation, après une commercialisation adéquate, entre un vendeur et un acheteur consentants, agissant chacun de manière indépendante. Cette définition, alignée sur l'article 4(1)(76) du CRR, est essentielle pour le calcul du ratio LTV par les banques.</p><p>L'évaluateur doit documenter la <strong>date de valeur</strong>, l'<strong>objet de l'évaluation</strong> (garantie hypothécaire, transaction, comptabilité IFRS, succession), les <strong>hypothèses spéciales</strong> retenues et les sources de données utilisées. Le rapport d'évaluation doit être signé par un évaluateur qualifié — au Luxembourg, il n'existe pas de titre protégé, mais la pratique professionnelle s'appuie sur les qualifications REV (Recognised European Valuer) délivrées par TEGoVA.</p>",
  methodesTitle: "Les 5 méthodes d'évaluation reconnues",
  methodesContent: "<p>Notre outil de valorisation intègre les cinq approches d'évaluation consacrées par les standards internationaux :</p><ul><li><strong>Méthode par comparaison</strong> : approche directe basée sur les transactions récentes de biens similaires. Au Luxembourg, nous exploitons la base de l'Administration de l'Enregistrement (AED) qui recense l'intégralité des actes notariés. Les ajustements portent sur la surface, la localisation, l'étage, l'état, la classe énergétique et les aménagements extérieurs.</li><li><strong>Méthode par capitalisation</strong> : le revenu locatif net est capitalisé au taux de rendement observé dans la zone. Les taux prime bureaux à Luxembourg-Ville (Kirchberg, Cloche d'Or) oscillaient entre 4,0 % et 4,5 % début 2025 selon JLL et CBRE.</li><li><strong>Méthode DCF (Discounted Cash Flow)</strong> : projection des flux nets sur 10 ans avec valeur terminale. Particulièrement adaptée aux immeubles multi-locataires avec des baux à échéances différentes. Le taux d'actualisation est déterminé par le WACC immobilier luxembourgeois.</li><li><strong>Mortgage Lending Value (MLV)</strong> : valeur prudente exigée par le règlement CRR (article 229) pour les expositions garanties par des biens immobiliers. Elle intègre une décote de prudence de 10 à 20 % par rapport à la valeur de marché.</li><li><strong>Méthode terme et réversion</strong> : distinction entre le revenu contractuel (terme) et le revenu de marché attendu après expiration du bail (réversion), capitalisés à des taux différenciés.</li></ul>",
  reconciliationTitle: "Réconciliation et pondération des méthodes",
  reconciliationContent: "<p>L'évaluateur professionnel ne retient jamais une seule méthode. La <strong>réconciliation</strong> consiste à attribuer un poids à chaque approche en fonction de la fiabilité des données disponibles et de la nature du bien :</p><ul><li>Pour un <strong>appartement standard</strong> en zone urbaine, la comparaison recevra un poids prépondérant (60-70 %) car les transactions sont nombreuses et homogènes.</li><li>Pour un <strong>immeuble de rapport</strong>, la capitalisation et le DCF seront privilégiés (poids cumulé de 70-80 %), la comparaison servant de contrôle.</li><li>Pour un <strong>bien atypique</strong> (château, terrain à bâtir, bien rural), l'évaluateur s'appuiera davantage sur la méthode résiduelle ou la comparaison ajustée, avec des intervalles de confiance plus larges.</li></ul><p>Notre algorithme de réconciliation utilise un modèle de pondération bayésien qui ajuste les poids en fonction du nombre de comparables disponibles, de la dispersion des valeurs et de la profondeur des données locatives.</p>",
  rapportTitle: "Structure du rapport d'évaluation",
  rapportContent: "<p>Un rapport d'évaluation conforme aux EVS 2025 comprend les éléments suivants :</p><ul><li><strong>Identification du bien</strong> : adresse, références cadastrales (section, numéro de parcelle), description physique, servitudes et droits réels inscrits au Livre Foncier.</li><li><strong>Contexte juridique</strong> : régime de copropriété, bail emphytéotique, droit de superficie, conformité urbanistique (PAG/PAP).</li><li><strong>Analyse du marché local</strong> : tendances de prix, volumes de transactions, offre et demande, projets d'infrastructure (tramway, routes, zones d'activités).</li><li><strong>Application des méthodes</strong> : détail des calculs, sources des données, justification des paramètres retenus (taux, comparables, loyers de référence).</li><li><strong>Réconciliation et conclusion</strong> : valeur retenue, intervalle de confiance, réserves éventuelles, conditions suspensives.</li></ul><p>Le rapport généré par tevaxia respecte cette structure et peut servir de base à une expertise formelle, sous réserve de validation par un évaluateur qualifié.</p>",
  faq1Q: "Qui peut réaliser une évaluation immobilière au Luxembourg ?",
  faq1A: "Au Luxembourg, le titre d'expert immobilier n'est pas légalement protégé. Toutefois, les banques exigent généralement un évaluateur titulaire de la qualification REV (Recognised European Valuer) délivrée par TEGoVA, ou un membre d'une organisation professionnelle reconnue. La CSSF recommande que les évaluations pour garanties hypothécaires soient réalisées par des professionnels indépendants du processus d'octroi de crédit.",
  faq2Q: "Quelle méthode d'évaluation utiliser selon le type de bien ?",
  faq2A: "Pour un appartement ou une maison d'habitation, la méthode par comparaison est généralement la plus fiable car les transactions sont nombreuses. Pour un immeuble de bureaux ou commercial loué, la capitalisation des revenus ou le DCF sont privilégiés. Pour un terrain à bâtir, la méthode résiduelle (compte à rebours) est incontournable. L'évaluateur professionnel utilise toujours au moins deux méthodes et procède à une réconciliation.",
  faq3Q: "Quelle différence entre valeur de marché et Mortgage Lending Value (MLV) ?",
  faq3A: "La valeur de marché représente le prix le plus probable à la date d'évaluation. La MLV (valeur hypothécaire) est une valeur prudente, stable dans le temps, qui tient compte des caractéristiques durables du bien et des conditions normales du marché local. Elle exclut les éléments spéculatifs et applique généralement une décote de 10 à 20 % par rapport à la valeur de marché. La MLV est exigée par le règlement CRR pour le calcul des fonds propres des banques.",
  faq4Q: "À quelle fréquence faut-il réévaluer un bien immobilier ?",
  faq4A: "Pour les biens en garantie hypothécaire, la CSSF exige une réévaluation au minimum tous les 3 ans pour l'immobilier résidentiel et tous les ans pour l'immobilier commercial (circulaire 21/773). En comptabilité IFRS (IAS 40), les immeubles de placement doivent être réévalués à chaque clôture si le modèle de la juste valeur est retenu. Pour une succession, l'évaluation doit refléter la valeur au jour du décès.",
  faq5Q: "Combien coûte une expertise immobilière au Luxembourg ?",
  faq5A: "Les honoraires d'un expert immobilier au Luxembourg varient selon la complexité du bien et l'objet de l'évaluation. Pour un appartement standard, comptez entre 1 500 et 3 000 EUR pour un rapport conforme EVS. Pour un immeuble de rapport ou un bien commercial, les honoraires se situent généralement entre 3 000 et 8 000 EUR. Les évaluations de portefeuilles importants font l'objet de tarifs dégressifs. L'outil tevaxia permet d'obtenir une pré-évaluation instantanée, utile avant de mandater une expertise formelle."
};

data.hedonique.seo = {
  faqTitle: "Questions fréquentes sur le modèle hédonique",
  relatedTitle: "Outils complémentaires",
  modeleTitle: "Le modèle hédonique appliqué au marché luxembourgeois",
  modeleContent: "<p>Le <strong>modèle hédonique</strong> est une approche économétrique qui décompose le prix d'un bien immobilier en la somme des valeurs implicites de ses caractéristiques. Développé par Rosen (1974), il repose sur l'hypothèse que le prix observé sur le marché reflète les préférences des acheteurs pour chaque attribut du logement.</p><p>Au Luxembourg, l'<strong>Observatoire de l'Habitat</strong> (Ministère du Logement / LISER) publie régulièrement des modèles hédoniques calibrés sur les transactions réelles enregistrées par l'Administration de l'Enregistrement (AED). Ces modèles permettent de construire des indices de prix à qualité constante, en neutralisant l'effet de composition du parc vendu.</p><p>Notre implémentation utilise un modèle <strong>log-linéaire</strong> : ln(Prix) = &beta;<sub>0</sub> + &Sigma;(&beta;<sub>i</sub> &times; X<sub>i</sub>) + &epsilon;. La variable dépendante est le logarithme du prix, ce qui permet d'interpréter directement les coefficients comme des élasticités (impact en pourcentage). Les variables explicatives couvrent la surface, la localisation (commune/quartier), l'étage, l'état général, la classe énergétique CPE, la présence d'un parking et les aménagements extérieurs.</p>",
  coefficientsTitle: "Coefficients et variables explicatives",
  coefficientsContent: "<p>Les coefficients de notre modèle sont calibrés à partir des données luxembourgeoises disponibles :</p><ul><li><strong>Surface</strong> : élasticité de -0,35 % par m² supplémentaire au-delà de 80 m². Ce coefficient traduit la décroissance marginale du prix au m² avec la surface — un phénomène bien documenté dans la littérature immobilière.</li><li><strong>Étage</strong> : le rez-de-chaussée subit une décote d'environ 7 %, le premier étage de 3 %. Les étages élevés (4+) bénéficient d'une prime de 3 %, et l'attique jusqu'à 8 %. Source : Observatoire de l'Habitat.</li><li><strong>État général</strong> : un bien neuf ou entièrement rénové obtient une prime d'environ 7 %. Un bien à rafraîchir subit une décote de 5 %, et un bien à rénover de 15 %. Ces ajustements sont cohérents avec l'analyse des transactions de la base AED.</li><li><strong>Classe énergétique CPE</strong> : les classes A-B apportent une prime de 5 %, tandis que les classes F-G entraînent une décote de 8 %. La Spuerkeess a documenté cet écart dans ses études sur le green premium luxembourgeois.</li><li><strong>Parking</strong> : un emplacement intérieur ajoute environ 5 % au prix du logement (équivalent à 30 000-45 000 EUR selon la localisation).</li></ul>",
  sourcesTitle: "Sources de données",
  sourcesContent: "<p>La fiabilité d'un modèle hédonique dépend directement de la qualité et de la représentativité des données sous-jacentes. Au Luxembourg, nous exploitons plusieurs sources :</p><ul><li><strong>Observatoire de l'Habitat</strong> : indices de prix hédoniques publiés trimestriellement, basés sur les actes notariés transmis par l'AED. Couverture exhaustive du marché résidentiel depuis 2010.</li><li><strong>STATEC</strong> : indice des prix des logements (IPIL), prix moyens par commune, statistiques de construction. Le STATEC publie également les données détaillées par type de bien (appartement existant, maison existante, VEFA).</li><li><strong>Administrations communales</strong> : données PAG/PAP, permis de bâtir, informations cadastrales.</li><li><strong>Annonces immobilières</strong> : les prix affichés servent de référence complémentaire mais sont généralement supérieurs de 5 à 10 % aux prix de transaction effectifs.</li></ul><p>La mise à jour des coefficients est réalisée semestriellement pour intégrer les évolutions du marché.</p>",
  limitesTitle: "Limites du modèle : R² et intervalle de confiance",
  limitesContent: "<p>Tout modèle statistique présente des limites qu'il est essentiel de comprendre :</p><ul><li><strong>R² (coefficient de détermination)</strong> : notre modèle affiche un R² d'environ 0,75, ce qui signifie que 75 % de la variance des prix est expliquée par les variables retenues. Les 25 % restants relèvent de facteurs non observés (qualité de la vue, luminosité, bruit, micro-localisation, état des parties communes).</li><li><strong>Intervalle de confiance</strong> : l'estimation ponctuelle est toujours accompagnée d'un intervalle. En zone urbaine dense avec de nombreuses transactions, l'intervalle est de &plusmn;10 %. En zone rurale avec peu de données, il peut atteindre &plusmn;18 %.</li><li><strong>Biens atypiques</strong> : le modèle est calibré sur des biens standards. Les propriétés de luxe, les maisons de caractère ou les biens présentant des défauts majeurs peuvent s'écarter significativement de l'estimation.</li><li><strong>Effet temporel</strong> : les coefficients reflètent les conditions de marché au moment de la calibration. En période de retournement rapide, un décalage peut apparaître.</li></ul>",
  faq1Q: "Quel est le R² du modèle hédonique pour le Luxembourg ?",
  faq1A: "Le R² de notre modèle est d'environ 0,75, ce qui est comparable aux résultats obtenus par l'Observatoire de l'Habitat dans ses publications officielles. Cela signifie que 75 % de la variance des prix de transaction est expliquée par les caractéristiques observées du bien (surface, localisation, étage, état, énergie). Les 25 % restants dépendent de facteurs non mesurables comme la vue, le bruit ou l'état précis des finitions.",
  faq2Q: "Quelle différence entre le modèle hédonique et une expertise immobilière ?",
  faq2A: "Le modèle hédonique fournit une estimation statistique basée sur des données de marché, sans visite physique du bien. Une expertise immobilière (conforme EVS) inclut une inspection sur site, une analyse juridique approfondie (servitudes, urbanisme), la vérification de l'état réel du bien et un jugement professionnel. Le modèle hédonique est idéal pour un premier cadrage de prix ou un avis de valeur rapide, tandis que l'expertise est nécessaire pour les opérations bancaires, les successions ou les litiges.",
  faq3Q: "Le modèle hédonique est-il applicable à l'immobilier commercial ?",
  faq3A: "Notre modèle hédonique est calibré principalement sur le marché résidentiel luxembourgeois (appartements et maisons). Pour l'immobilier commercial (bureaux, commerces, logistique), les méthodes d'évaluation par les revenus (capitalisation, DCF) sont plus appropriées car le prix dépend essentiellement du rendement locatif. Nous proposons un outil DCF multi-locataires dédié à l'immobilier de rapport.",
  faq4Q: "Quelle est la précision du modèle par commune ?",
  faq4A: "La précision varie selon la densité de transactions. À Luxembourg-Ville, Esch-sur-Alzette ou Differdange, où les volumes sont élevés, l'intervalle de confiance est de &plusmn;10 %. Dans les communes rurales du nord (Winseler, Kiischpelt) avec moins de 10 transactions par an, l'intervalle peut atteindre &plusmn;18 %. Le modèle affiche systématiquement un indice de confiance adapté à chaque commune."
};

data.dcfMulti.seo = {
  faqTitle: "Questions fréquentes sur le DCF immobilier",
  relatedTitle: "Outils complémentaires",
  analyseTitle: "L'analyse DCF pour l'immobilier de rapport au Luxembourg",
  analyseContent: "<p>La méthode <strong>Discounted Cash Flow (DCF)</strong> est l'approche de référence pour évaluer les immeubles de rapport multi-locataires. Elle consiste à projeter l'ensemble des flux de trésorerie nets générés par l'immeuble sur une période d'analyse définie (généralement 10 ans), puis à les actualiser à un taux reflétant le risque de l'investissement.</p><p>Au Luxembourg, le DCF est particulièrement pertinent pour les immeubles de bureaux (Kirchberg, Cloche d'Or, Gare Centrale), les immeubles mixtes et les résidences locatives. Les investisseurs institutionnels (fonds immobiliers SIF/RAIF réglementés par la CSSF) utilisent systématiquement cette méthode pour leur reporting INREV et leurs due diligences d'acquisition.</p><p>La valeur DCF se décompose en deux composantes : la <strong>valeur actuelle des revenus nets</strong> perçus pendant la période d'analyse, et la <strong>valeur terminale actualisée</strong> (prix de revente estimé en fin de période). La valeur terminale représente typiquement 50 à 70 % de la valeur totale, ce qui souligne l'importance du choix du taux de capitalisation de sortie.</p>",
  bailParBailTitle: "Analyse bail par bail : loyer, indexation et vacance",
  bailParBailContent: "<p>Notre outil DCF multi-locataires modélise chaque bail individuellement, ce qui permet une analyse granulaire de l'état locatif :</p><ul><li><strong>Loyer contractuel</strong> : le loyer en place est projeté jusqu'à l'échéance du bail, avec application de l'indexation contractuelle. Au Luxembourg, la plupart des baux commerciaux prévoient une indexation annuelle basée sur l'indice des prix à la consommation (IPCN) publié par le STATEC.</li><li><strong>Option de break</strong> : si le bail prévoit une option de sortie anticipée, le modèle intègre une probabilité de non-renouvellement qui génère un flux de vacance potentiel.</li><li><strong>Estimated Rental Value (ERV)</strong> : à l'expiration de chaque bail, le loyer est rebasé sur le loyer de marché estimé. L'écart entre le loyer en place et l'ERV (potentiel de réversion) est un indicateur clé de la sous- ou sur-évaluation du revenu.</li><li><strong>Vacance structurelle</strong> : un taux de vacance est appliqué sur l'ERV pour les périodes de relocation. Au Luxembourg, la vacance de bureaux à Luxembourg-Ville était d'environ 3,5 % début 2025 (source : JLL Luxembourg).</li><li><strong>Franchise et fit-out</strong> : les périodes de franchise (rent-free) et les contributions aux aménagements locataires sont modélisées comme des flux négatifs dans l'année de renouvellement.</li></ul>",
  tauxTitle: "Taux d'actualisation et taux de capitalisation de sortie",
  tauxContent: "<p>Le choix des taux est déterminant dans le résultat de l'évaluation DCF :</p><ul><li><strong>Taux d'actualisation (discount rate)</strong> : il reflète le rendement exigé par l'investisseur compte tenu du risque. Au Luxembourg, les taux d'actualisation pour les bureaux prime se situent entre 5,5 % et 6,5 % (2025). Pour le résidentiel, ils oscillent entre 4,5 % et 5,5 %. Ces taux s'obtiennent par la méthode du build-up : taux sans risque (OAT 10 ans) + prime de risque immobilier + prime de liquidité + prime spécifique.</li><li><strong>Taux de capitalisation de sortie (exit cap rate)</strong> : il détermine la valeur de revente à la fin de la période d'analyse. Il est généralement supérieur de 25 à 50 points de base au taux initial pour refléter le vieillissement de l'immeuble. Les taux prime bureaux à Luxembourg-Kirchberg s'établissaient à 4,25 % début 2025 (CBRE).</li><li><strong>Sensibilité</strong> : une variation de 25 bps du taux d'actualisation peut modifier la valeur de 3 à 5 %. Il est essentiel de réaliser une analyse de sensibilité croisée (taux d'actualisation &times; taux de sortie) pour calibrer l'intervalle de valeur.</li></ul>",
  irrTitle: "TRI (Taux de Rendement Interne) et analyse de sensibilité",
  irrContent: "<p>Le <strong>TRI (IRR)</strong> est le taux d'actualisation qui annule la valeur actuelle nette (VAN) de l'investissement. C'est l'indicateur synthétique de performance le plus utilisé par les investisseurs institutionnels :</p><ul><li><strong>TRI non-leveragé</strong> : rendement de l'actif indépendamment du financement. Il permet de comparer des projets entre eux sur une base homogène.</li><li><strong>TRI on equity (leveraged)</strong> : rendement sur fonds propres après service de la dette. L'effet de levier amplifie le rendement si le TRI non-leveragé est supérieur au coût de la dette. Notre outil permet de modéliser la dette (montant, taux) pour calculer le TRI equity.</li><li><strong>Analyse de sensibilité</strong> : notre matrice de sensibilité croise le taux d'actualisation et le taux de sortie pour visualiser l'impact sur la valeur DCF. Les zones vertes, jaunes et rouges permettent d'identifier les scénarios favorables et défavorables.</li></ul><p>Pour un immeuble de bureaux bien localisé à Luxembourg-Ville avec des baux fermes de longue durée, un TRI cible de 5,5 à 7 % est représentatif en 2025. Pour des actifs value-add nécessitant des travaux ou une relocation, les investisseurs visent un TRI de 8 à 12 %.</p>",
  faq1Q: "Quel taux d'actualisation utiliser pour un DCF au Luxembourg ?",
  faq1A: "Le taux d'actualisation dépend de la classe d'actifs et du profil de risque. Pour les bureaux prime à Luxembourg-Ville (Kirchberg, CBD), comptez entre 5,5 % et 6,5 % en 2025. Pour le résidentiel locatif, entre 4,5 % et 5,5 %. Pour les actifs secondaires ou à repositionner, entre 7 % et 9 %. La méthode du build-up (taux sans risque + primes de risque) est la plus rigoureuse pour justifier le taux retenu.",
  faq2Q: "Quelle différence entre cap rate et discount rate ?",
  faq2A: "Le cap rate (taux de capitalisation) est le ratio entre le revenu net stabilisé et la valeur du bien — il reflète le rendement immédiat. Le discount rate (taux d'actualisation) est le taux utilisé pour actualiser les flux futurs dans un DCF — il intègre les anticipations de croissance des loyers et la prime de risque globale. Le discount rate est généralement supérieur au cap rate de 100 à 200 bps car il rémunère également le risque temporel.",
  faq3Q: "Comment modéliser la vacance structurelle ?",
  faq3A: "La vacance structurelle représente le délai moyen de relocation entre deux locataires. Au Luxembourg, pour les bureaux prime, la vacance structurelle est de l'ordre de 3 à 6 mois (vacance de 2,5 à 5 %). Pour les bureaux secondaires, elle peut atteindre 12 mois. Notre outil applique ce taux de vacance sur l'ERV uniquement pendant les périodes de relocation identifiées bail par bail.",
  faq4Q: "Quel horizon d'analyse retenir pour un DCF immobilier ?",
  faq4A: "L'horizon standard est de 10 ans, ce qui correspond à la durée typique des baux commerciaux au Luxembourg. Pour des actifs avec des baux très longs (15-25 ans, fréquents dans la logistique ou le public), on peut étendre à 15 ans. Un horizon plus court (5-7 ans) est utilisé pour les stratégies value-add ou opportunistes. L'essentiel est que l'horizon couvre au moins un cycle complet de renouvellement des baux."
};

data.outilsBancaires.seo = {
  faqTitle: "Questions fréquentes sur le crédit immobilier au Luxembourg",
  relatedTitle: "Outils complémentaires",
  creditTitle: "Les outils de crédit immobilier au Luxembourg",
  creditContent: "<p>Le marché du crédit immobilier luxembourgeois présente des spécificités importantes par rapport aux pays voisins. Le secteur bancaire est dominé par des acteurs locaux (Spuerkeess/BCEE, BIL, BGL BNP Paribas, Raiffeisen) et des banques internationales (ING, Deutsche Bank) qui proposent des conditions différenciées.</p><p>Les taux d'intérêt au Luxembourg suivent les décisions de la <strong>Banque Centrale Européenne (BCE)</strong>, avec un spread bancaire typique de 80 à 150 points de base au-dessus du taux de refinancement. En 2025, les taux fixes à 10 ans s'établissent autour de 3,0 à 3,8 %, tandis que les taux variables (indexés sur l'EURIBOR 3 mois) oscillent entre 3,2 et 4,0 %.</p><p>La <strong>CSSF</strong> (Commission de Surveillance du Secteur Financier) encadre les pratiques d'octroi via ses circulaires et recommandations, notamment en matière de ratio LTV (Loan-to-Value) et de capacité de remboursement. Depuis 2020, le Comité du Risque Systémique (CRS) a émis des recommandations macro-prudentielles spécifiques au marché luxembourgeois.</p>",
  ltvTitle: "Ratio LTV et seuils CSSF",
  ltvContent: "<p>Le <strong>ratio Loan-to-Value (LTV)</strong> est le rapport entre le montant du prêt et la valeur du bien. La CSSF et le CRS ont émis des recommandations de plafonds LTV différenciés :</p><ul><li><strong>Primo-accédants (résidence principale)</strong> : LTV maximum recommandé de 100 % (financement intégral possible sous conditions). En pratique, les banques accordent fréquemment des LTV de 90 à 100 % aux primo-accédants bénéficiant de la garantie de l'État.</li><li><strong>Accédants non-primo (résidence principale)</strong> : LTV recommandé de 90 % maximum, soit un apport de 10 %.</li><li><strong>Investissement locatif</strong> : LTV limité à 80 %, imposant un apport minimum de 20 %. Certaines banques sont plus restrictives (75 %).</li><li><strong>Buy-to-let</strong> : des conditions spécifiques s'appliquent, avec parfois des seuils à 70 % LTV et des taux majorés de 20 à 50 bps.</li></ul><p>Il est important de noter que le LTV se calcule sur la <strong>valeur d'expertise</strong> du bien, pas sur le prix d'achat. Si le prix d'achat est supérieur à l'expertise, la banque retiendra la valeur la plus basse.</p>",
  capaciteTitle: "Capacité d'emprunt et règle des 40 %",
  capaciteContent: "<p>La capacité d'emprunt est déterminée par le <strong>ratio d'endettement</strong> (debt-to-income), qui ne doit généralement pas dépasser <strong>40 % des revenus nets</strong> du ménage au Luxembourg. Ce seuil est plus généreux que dans certains pays voisins (35 % en France, 33 % en Belgique).</p><ul><li><strong>Revenus pris en compte</strong> : salaire net, revenus locatifs (généralement retenus à 70-80 %), revenus d'activité indépendante (moyenne sur 3 ans), pensions.</li><li><strong>Charges déduites</strong> : crédits en cours, pensions alimentaires, loyer résiduel si applicable.</li><li><strong>Reste à vivre</strong> : au-delà du ratio d'endettement, les banques luxembourgeoises vérifient un seuil de reste à vivre minimum (environ 1 200 EUR/mois pour un célibataire, 2 000 EUR pour un couple).</li></ul><p>Notre simulateur calcule la mensualité maximale admissible et en déduit le montant maximum empruntable selon la durée et le taux choisis.</p>",
  amortissementTitle: "Amortissement : constant vs progressif",
  amortissementContent: "<p>Les banques luxembourgeoises proposent principalement deux types d'amortissement :</p><ul><li><strong>Amortissement constant (annuités constantes)</strong> : la mensualité reste fixe pendant toute la durée du prêt. La part d'intérêts diminue progressivement tandis que la part de capital remboursé augmente. C'est le schéma le plus courant au Luxembourg.</li><li><strong>Amortissement linéaire (capital constant)</strong> : le remboursement de capital est identique chaque mois, ce qui produit des mensualités décroissantes. Les intérêts baissent régulièrement. Ce schéma est plus avantageux en coût total d'intérêts mais impose des mensualités initiales plus élevées.</li><li><strong>In fine</strong> : seuls les intérêts sont payés pendant la durée du prêt, le capital étant remboursé en une fois à l'échéance. Utilisé principalement pour l'investissement locatif avec un contrat d'assurance-vie en adossement.</li></ul><p>Notre tableau d'amortissement détaille mois par mois l'évolution du capital restant dû, la répartition intérêts/capital et le coût total du crédit.</p>",
  dscrTitle: "DSCR pour l'investissement locatif",
  dscrContent: "<p>Le <strong>Debt Service Coverage Ratio (DSCR)</strong> est un ratio utilisé par les banques pour évaluer la capacité d'un bien locatif à couvrir le service de la dette :</p><p><strong>DSCR = Revenu net d'exploitation / Service annuel de la dette</strong></p><ul><li>Un DSCR supérieur à <strong>1,20</strong> est généralement exigé par les banques luxembourgeoises pour un crédit immobilier locatif.</li><li>Un DSCR de <strong>1,00</strong> signifie que les loyers couvrent exactement les remboursements — situation à risque en cas de vacance ou d'imprévu.</li><li>Un DSCR inférieur à <strong>1,00</strong> implique que l'investisseur doit compléter le service de la dette sur ses revenus personnels.</li></ul><p>Pour le calcul, le revenu net intègre une vacance normative (généralement 5 à 8 %), les charges non récupérables et une provision pour travaux. Le service de la dette comprend les intérêts et le remboursement du capital.</p>",
  faq1Q: "Taux fixe ou variable : que choisir au Luxembourg ?",
  faq1A: "Le choix dépend de votre profil de risque et de votre horizon. Le taux fixe offre la sécurité d'une mensualité constante, ce qui est recommandé si vous empruntez au maximum de votre capacité. Le taux variable (EURIBOR + marge) peut être plus avantageux si les taux baissent, mais il vous expose à des hausses. Au Luxembourg, une option populaire est le taux révisable capé, qui combine un taux variable avec un plafond de hausse. En 2025, l'écart entre fixe et variable s'est réduit, rendant le fixe particulièrement attractif.",
  faq2Q: "Quel apport minimum pour acheter au Luxembourg ?",
  faq2A: "Pour les primo-accédants (résidence principale), un financement à 100 % est théoriquement possible grâce à la garantie de l'État. En pratique, les banques recommandent un apport de 10 à 20 %. Pour un investissement locatif, l'apport minimum est de 20 % (LTV 80 %). Les frais d'acquisition (droits d'enregistrement, notaire, TVA) représentent environ 7 à 10 % du prix et ne sont généralement pas financés — il faut donc les ajouter à l'apport.",
  faq3Q: "Comment fonctionne la garantie de l'État luxembourgeois ?",
  faq3A: "La garantie de l'État pour le logement (loi modifiée du 25 février 1979) permet aux primo-accédants de bénéficier d'une garantie publique couvrant jusqu'à 30 % du montant du prêt, avec un plafond de 250 000 EUR. Cette garantie facilite l'obtention d'un prêt sans apport personnel. Les conditions incluent un plafond de revenus du ménage et l'obligation d'occuper le bien comme résidence principale. La demande se fait auprès du Ministère du Logement via le guichet unique myguichet.lu.",
  faq4Q: "Quel est l'impact de la classe énergétique CPE sur le crédit ?",
  faq4A: "Depuis les recommandations de la CSSF sur les risques climatiques, les banques luxembourgeoises intègrent progressivement la performance énergétique dans leurs critères d'octroi. Un bien classé A-B peut bénéficier de conditions préférentielles (réduction de taux de 10 à 30 bps). Inversement, les biens classés F-G (passoires énergétiques) font l'objet d'une analyse renforcée, avec parfois une décote sur la valeur d'expertise et un provisionnement du coût des travaux de rénovation énergétique.",
  faq5Q: "Peut-on refinancer un crédit immobilier au Luxembourg ?",
  faq5A: "Oui, le refinancement est possible et peut être avantageux si les taux ont baissé depuis la souscription. Les frais à prévoir sont : l'indemnité de remboursement anticipé (IRA, plafonnée à 6 mois d'intérêts ou 1 % du capital remboursé selon le Code de la consommation), les frais de mainlevée d'hypothèque (environ 500 à 1 000 EUR), et les frais de nouvelle inscription hypothécaire. Le calcul de rentabilité dépend de l'écart de taux, du capital restant dû et de la durée résiduelle."
};

data.bilanPromoteur.seo = {
  faqTitle: "Questions fréquentes sur le bilan promoteur",
  relatedTitle: "Outils complémentaires",
  faisabiliteTitle: "Le bilan promoteur : outil de faisabilité d'une opération immobilière",
  faisabiliteContent: "<p>Le <strong>bilan promoteur</strong> (ou bilan d'opération) est l'outil fondamental de tout promoteur immobilier pour évaluer la viabilité économique d'un projet de construction ou de réhabilitation. Au Luxembourg, où les coûts de construction et les prix du foncier figurent parmi les plus élevés d'Europe, une analyse rigoureuse est indispensable avant tout engagement.</p><p>Le bilan met en regard les <strong>recettes prévisionnelles</strong> (chiffre d'affaires des ventes ou des mises en location) et l'ensemble des <strong>coûts</strong> (foncier, construction, honoraires, frais financiers, commercialisation). La différence constitue la <strong>marge brute</strong> de l'opération, dont le promoteur déduit sa rémunération et les aléas.</p><p>Au Luxembourg, les opérations de promotion sont encadrées par la loi du 22 octobre 2008 (secteur de l'aménagement communal) et le règlement grand-ducal du 28 juillet 2011 relatif aux plans d'aménagement. La conformité au PAG (Plan d'Aménagement Général) et au PAP (Plan d'Aménagement Particulier) détermine les paramètres fondamentaux du projet : COS, CUS, nombre d'étages, reculs, pourcentage de logements abordables.</p>",
  compteAReboursTitle: "La méthode du compte à rebours (Residual Land Value)",
  compteAReboursContent: "<p>La <strong>méthode résiduelle</strong> ou compte à rebours (Residual Land Value) permet de déterminer la valeur maximale du foncier en partant du chiffre d'affaires prévisionnel et en soustrayant l'ensemble des coûts :</p><p><strong>Valeur foncière maximale = Chiffre d'affaires - Coûts de construction - Honoraires - Frais financiers - Marge promoteur</strong></p><ul><li>Le <strong>chiffre d'affaires</strong> est calculé sur la base des prix de vente au m² par type de lot (appartements, maisons, commerces), ajustés selon la localisation et le standing.</li><li>Les <strong>coûts de construction</strong> intègrent le gros œuvre, le second œuvre, les lots techniques et les VRD (voir notre estimateur construction).</li><li>Les <strong>honoraires</strong> comprennent l'architecte (8-12 % selon l'OAI), le bureau d'études, le géomètre, le contrôle technique et la coordination sécurité.</li><li>Les <strong>frais financiers</strong> couvrent le portage foncier et le financement de la construction (taux de 3 à 5 % sur 24-36 mois).</li></ul><p>Cette méthode est systématiquement utilisée par les promoteurs luxembourgeois pour négocier le prix d'acquisition du terrain.</p>",
  coutsTitle: "Décomposition des coûts : foncier, construction, honoraires",
  coutsContent: "<p>La structure de coûts d'une opération de promotion au Luxembourg se décompose typiquement comme suit :</p><ul><li><strong>Foncier</strong> : 25 à 40 % du chiffre d'affaires selon la localisation. À Luxembourg-Ville, le foncier peut représenter jusqu'à 50 % du prix de vente final. Les droits d'enregistrement (7 % pour les terrains à bâtir) s'ajoutent au prix d'acquisition.</li><li><strong>Construction</strong> : 35 à 50 % du CA. Les coûts de construction au Luxembourg oscillent entre 2 200 et 3 500 EUR/m² SCP selon le standing et la complexité (données STATEC/OAI 2025). La TVA construction est de 17 % (taux normal) ou 3 % (taux super-réduit pour le logement, plafonné à 50 000 EUR par logement).</li><li><strong>Honoraires et frais</strong> : 12 à 18 % du CA. Incluent l'architecte, les ingénieurs, le notaire, la commercialisation (2-4 %), les assurances (décennale, TRC) et les frais financiers.</li><li><strong>Marge promoteur</strong> : cible de 8 à 15 % du CA pour une opération standard. Les opérations complexes ou risquées justifient une marge supérieure.</li></ul>",
  margeTitle: "Marge et rentabilité sur fonds propres",
  margeContent: "<p>La rentabilité d'une opération de promotion se mesure à travers plusieurs indicateurs :</p><ul><li><strong>Marge sur chiffre d'affaires</strong> : rapport entre le résultat net prévisionnel et le chiffre d'affaires. Un objectif de 10 à 15 % est standard au Luxembourg.</li><li><strong>Rentabilité sur fonds propres (ROE)</strong> : rapport entre le résultat et les fonds propres investis. Avec un effet de levier (financement bancaire à 60-70 %), un promoteur peut viser un ROE de 15 à 25 %.</li><li><strong>Multiple sur fonds propres</strong> : rapport entre le résultat et l'apport initial. Un multiple de 1,5x à 2,0x sur 24-36 mois est considéré comme attractif.</li></ul><p>L'analyse de sensibilité est cruciale : une baisse de 5 % des prix de vente ou une hausse de 10 % des coûts de construction peut anéantir la marge. Notre outil permet de simuler ces scénarios et de déterminer les seuils de rentabilité (prix de vente minimum, coût foncier maximum).</p>",
  faq1Q: "Quel est le ratio foncier/construction typique au Luxembourg ?",
  faq1A: "Le ratio varie considérablement selon la localisation. À Luxembourg-Ville (Belair, Limpertsberg, Kirchberg), le foncier représente 40 à 50 % du coût total de l'opération. En périphérie (Esch-sur-Alzette, Differdange, Mersch), le ratio descend à 25-35 %. Dans les zones rurales, le foncier peut ne représenter que 15-20 %. Ce ratio est un indicateur clé de la faisabilité : un ratio foncier/CA supérieur à 40 % rend l'opération fragile en cas de retournement de marché.",
  faq2Q: "La TVA est-elle récupérable sur une opération de promotion ?",
  faq2A: "Oui, le promoteur assujetti à la TVA récupère l'intégralité de la TVA sur les coûts de construction, les honoraires et les frais. La vente de logements neufs est soumise à la TVA (17 % ou 3 % super-réduit avec plafond de 50 000 EUR/logement). Pour les ventes de terrains à bâtir par un assujetti, la TVA s'applique également. En revanche, la vente d'un immeuble ancien est soumise aux droits d'enregistrement (7 %) et non à la TVA. Le choix du régime fiscal (TVA vs droits d'enregistrement) peut impacter significativement la rentabilité de l'opération.",
  faq3Q: "Comment gérer le risque de commercialisation ?",
  faq3A: "Le risque de commercialisation est majeur dans une opération de promotion. Au Luxembourg, les bonnes pratiques incluent : la pré-commercialisation (viser 30-40 % de réservations avant le démarrage des travaux), le recours à un contrat VEFA conforme à la loi du 18 avril 2008, la diversification de la gamme (mix de surfaces et de standings), et une clause de condition suspensive dans le compromis foncier liée au taux de pré-vente. Notre outil permet de simuler différents scénarios de rythme de vente et leur impact sur la trésorerie et la marge.",
  faq4Q: "Quel est le délai moyen d'une opération de promotion au Luxembourg ?",
  faq4A: "Le délai global d'une opération de promotion au Luxembourg est typiquement de 4 à 7 ans. L'obtention du PAP (Plan d'Aménagement Particulier) peut prendre 12 à 24 mois. L'autorisation de construire nécessite 3 à 12 mois supplémentaires. La construction proprement dite dure 18 à 30 mois pour une opération de 20 à 50 logements. La commercialisation commence idéalement 6 à 12 mois avant la livraison. Ces délais longs immobilisent le capital et augmentent les frais financiers, ce que notre outil intègre dans le bilan prévisionnel."
};

data.estimateurConstruction.seo = {
  faqTitle: "Questions fréquentes sur les coûts de construction",
  relatedTitle: "Outils complémentaires",
  estimerTitle: "Estimer le coût de construction au Luxembourg en 2025",
  estimerContent: "<p>Le Luxembourg figure parmi les pays européens où les <strong>coûts de construction</strong> sont les plus élevés, en raison des exigences réglementaires strictes (normes énergétiques, qualité des matériaux), du coût de la main-d'œuvre qualifiée et de la pression sur les entreprises du secteur.</p><p>Notre estimateur s'appuie sur les données du <strong>STATEC</strong> (indice des coûts de construction), de l'<strong>OAI</strong> (Ordre des Architectes et Ingénieurs-Conseils) et des mercuriales de prix observées sur les appels d'offres récents. Les coûts sont exprimés en EUR/m² de surface construite brute (SCB) ou de surface de construction pure (SCP) selon la norme de référence choisie.</p><p>L'estimation intègre l'ensemble des corps d'état : gros œuvre, charpente/couverture, façades, menuiseries, lots techniques (HVAC, électricité, plomberie, sanitaire), finitions et aménagements extérieurs. Les VRD (Voiries et Réseaux Divers) sont traités séparément dans notre outil dédié.</p>",
  prixM2Title: "Prix au m² par type de construction",
  prixM2Content: "<p>Les coûts de construction au Luxembourg varient significativement selon le type de projet (données 2025, hors foncier et honoraires) :</p><ul><li><strong>Résidentiel collectif standard</strong> : 2 200 à 2 800 EUR/m² SCP. Ce coût couvre un immeuble de 10 à 40 logements avec des finitions de qualité moyenne, conforme aux exigences énergétiques AA (performances proches du standard nZEB).</li><li><strong>Résidentiel haut de gamme</strong> : 3 000 à 3 800 EUR/m² SCP. Finitions supérieures, domotique, triple vitrage, matériaux nobles (pierre naturelle, parquet massif).</li><li><strong>Maison individuelle</strong> : 2 500 à 4 000 EUR/m², forte variation selon la surface et le standing. Les maisons passives ou à énergie positive ajoutent un surcoût de 10 à 15 %.</li><li><strong>Bureaux</strong> : 2 000 à 3 200 EUR/m². Faux planchers, faux plafonds, climatisation, contrôle d'accès. Les certifications BREEAM/DGNB ajoutent 5 à 8 % au coût.</li><li><strong>Commercial</strong> : 1 500 à 2 500 EUR/m². Grandes surfaces ouvertes, structure portante adaptée, quais de livraison.</li></ul>",
  facteursTitle: "Facteurs influençant le coût de construction",
  facteursContent: "<p>Plusieurs facteurs font varier le coût de construction au Luxembourg :</p><ul><li><strong>Localisation</strong> : les entreprises basées au Luxembourg sont plus chères que celles de la Grande Région (Belgique, France, Allemagne). Les chantiers en centre-ville impliquent des surcoûts logistiques (stationnement, livraisons, nuisances).</li><li><strong>Complexité architecturale</strong> : les formes irrégulières, les grandes portées, les sous-sols profonds et les toitures-terrasses végétalisées augmentent significativement le coût.</li><li><strong>Standing et finitions</strong> : l'écart entre des finitions standard et haut de gamme peut représenter 30 à 50 % du coût du second œuvre.</li><li><strong>Normes énergétiques</strong> : depuis le règlement grand-ducal du 9 juin 2021, les bâtiments neufs doivent respecter le standard nZEB (nearly Zero Energy Building). L'isolation renforcée, la ventilation double-flux, les panneaux photovoltaïques et les pompes à chaleur représentent un surcoût de 8 à 12 %.</li><li><strong>Conjoncture</strong> : l'inflation des matériaux (bois, acier, cuivre) et les tensions sur la main-d'œuvre qualifiée influencent les prix de manière cyclique.</li></ul>",
  normesTitle: "Normes OAI FC.04 et ILNAS 101",
  normesContent: "<p>Au Luxembourg, deux référentiels de surface coexistent et impactent directement le calcul des coûts au m² :</p><ul><li><strong>OAI FC.04</strong> : le référentiel de l'Ordre des Architectes et Ingénieurs-Conseils définit la <strong>Surface de Construction Pure (SCP)</strong>, la <strong>Surface Construite Brute (SCB)</strong> et la <strong>Surface Utile (SU)</strong>. La SCP exclut les murs extérieurs et les gaines techniques, tandis que la SCB les inclut. Les coûts de construction sont généralement exprimés en EUR/m² SCP.</li><li><strong>ILNAS EN 15221-6</strong> : norme européenne transposée au Luxembourg qui harmonise les définitions de surface pour le facility management. Elle distingue notamment la Gross Floor Area (GFA) et la Net Floor Area (NFA).</li></ul><p>La confusion entre SCB et SCP peut entraîner des écarts de 15 à 20 % dans l'estimation des coûts. Notre outil permet de basculer entre les deux référentiels et intègre les ratios de conversion standard (SCB/SCP = 1,15 à 1,25 selon la typologie).</p>",
  faq1Q: "Faut-il prévoir un budget pour les fondations spéciales ?",
  faq1A: "Au Luxembourg, les fondations spéciales (pieux, parois moulées, micropieux) sont nécessaires dans les zones alluvionnaires (vallée de l'Alzette, Moselle) ou sur les terrains en pente du Gutland et de l'Oesling. Le surcoût varie de 50 à 200 EUR/m² de surface au sol. Une étude géotechnique préalable (essai pressiométrique, sondages) est indispensable et coûte entre 5 000 et 15 000 EUR. Nous recommandons d'ajouter une provision de 5 à 8 % au poste fondations en l'absence d'étude détaillée.",
  faq2Q: "Quel surcoût pour les matériaux durables et biosourcés ?",
  faq2A: "L'utilisation de matériaux biosourcés (bois massif CLT, isolation chanvre/laine de bois, enduits chaux) entraîne un surcoût de 10 à 20 % sur les lots concernés par rapport aux matériaux conventionnels. Toutefois, ces matériaux peuvent ouvrir droit à des bonus dans la certification LENOZ (Lëtzebuerger Nohaltegkeets-Zertifizéierung) et améliorer le bilan carbone du bâtiment. La construction bois est de plus en plus compétitive au Luxembourg, notamment pour les immeubles de 3 à 6 étages.",
  faq3Q: "Quels sont les délais moyens de construction au Luxembourg ?",
  faq3A: "Les délais varient selon la taille du projet : 12 à 18 mois pour une maison individuelle, 18 à 24 mois pour un petit immeuble collectif (10-20 logements), 24 à 36 mois pour une opération importante (50+ logements ou immeuble de bureaux). Ces délais n'incluent pas les phases d'études et d'autorisations qui peuvent ajouter 12 à 24 mois. Une marge de 15 à 20 % sur le planning est prudente pour absorber les retards.",
  faq4Q: "Quel pourcentage prévoir pour les honoraires d'architecte ?",
  faq4A: "Les honoraires d'architecte au Luxembourg sont encadrés par le règlement de l'OAI et calculés en pourcentage du coût des travaux. Pour un projet résidentiel, comptez 8 à 12 % du montant des travaux (hors TVA). Ce pourcentage inclut les phases d'esquisse, avant-projet, projet d'autorisation, dossier d'exécution, appel d'offres, direction des travaux et réception. Les honoraires des bureaux d'études ajoutent 3 à 5 % supplémentaires."
};

data.calculateurVrd.seo = {
  faqTitle: "Questions fréquentes sur les VRD au Luxembourg",
  relatedTitle: "Outils complémentaires",
  viabilisationTitle: "Coûts de viabilisation (VRD) au Luxembourg",
  viabilisationContent: "<p>La <strong>viabilisation</strong> d'un terrain au Luxembourg englobe l'ensemble des travaux de Voiries et Réseaux Divers (VRD) nécessaires pour rendre un terrain constructible et raccordable aux réseaux publics. Ces travaux constituent un poste budgétaire majeur dans toute opération d'aménagement ou de promotion immobilière.</p><p>Au Luxembourg, les coûts de VRD sont influencés par la topographie (plateau du Gutland vs reliefs de l'Oesling), la nature du sol, la distance aux réseaux existants et les exigences spécifiques de chaque commune. Les communes luxembourgeoises disposent d'une autonomie importante en matière d'aménagement, ce qui entraîne des différences significatives dans les cahiers des charges techniques.</p><p>Le <strong>Pacte Logement 2.0</strong> (loi du 30 juillet 2021) et la réforme de la taxe de remaniement ont modifié les mécanismes de financement des infrastructures, avec une participation accrue des promoteurs au coût des équipements publics.</p>",
  postesTitle: "Les grands postes de VRD",
  postesContent: "<p>Les travaux de VRD se décomposent en plusieurs postes principaux :</p><ul><li><strong>Voirie</strong> : terrassement, fond de forme, sous-couche, couche de roulement (enrobé), bordures, trottoirs, signalisation. Coût moyen : 80 à 150 EUR/m² de voirie. Les voiries communales doivent respecter les normes de l'Administration des Ponts et Chaussées.</li><li><strong>Réseaux d'eau potable</strong> : canalisations, branchements, bouches à clé, compteurs. Le raccordement au réseau communal est soumis à la taxe d'infrastructure fixée par règlement communal (1 500 à 5 000 EUR par lot).</li><li><strong>Assainissement</strong> : réseau séparatif (eaux usées + eaux pluviales) obligatoire dans les nouvelles zones d'aménagement. Bassins de rétention obligatoires selon la loi modifiée du 19 décembre 2008 relative à l'eau.</li><li><strong>Réseaux secs</strong> : électricité (réseau souterrain obligatoire en zone urbaine), télécommunications (fibre optique), gaz naturel (Enovos/Creos). Les tranchées communes permettent d'optimiser les coûts.</li><li><strong>Éclairage public</strong> : mâts, luminaires LED, câblage, armoires de commande. Les nouvelles installations doivent respecter le règlement grand-ducal du 11 novembre 2022 sur la pollution lumineuse.</li></ul>",
  coutParLotTitle: "Coût de viabilisation par lot selon la densité",
  coutParLotContent: "<p>Le coût de VRD par lot varie fortement selon la densité d'aménagement :</p><ul><li><strong>Maisons individuelles isolées</strong> (5-10 lots/ha) : 40 000 à 70 000 EUR/lot. La faible densité implique des linéaires de réseaux importants par lot.</li><li><strong>Maisons en bande</strong> (15-25 lots/ha) : 25 000 à 45 000 EUR/lot. La densité intermédiaire optimise le ratio longueur de réseau/nombre de lots.</li><li><strong>Immeubles collectifs</strong> (50-100 logements/ha) : 10 000 à 25 000 EUR/logement. La densité élevée mutualise les coûts d'infrastructure.</li></ul><p>Ces fourchettes incluent les VRD primaires (desserte du terrain) et secondaires (distribution interne), mais excluent les VRD tertiaires (aménagements privés, parkings, espaces verts privatifs).</p><p>Le rapport LISER sur l'aménagement foncier souligne que la densification est la stratégie la plus efficace pour réduire le coût des infrastructures par logement.</p>",
  obligationsTitle: "Obligations communales et participation financière",
  obligationsContent: "<p>Au Luxembourg, les obligations en matière de VRD sont encadrées par plusieurs textes :</p><ul><li><strong>Loi du 19 juillet 2004</strong> (aménagement communal) : elle définit les zones constructibles dans le PAG et les conditions d'aménagement dans les PAP. Le promoteur est généralement tenu de réaliser les VRD internes au lotissement et de les rétrocéder à la commune après réception.</li><li><strong>Participation financière</strong> : le promoteur doit contribuer au financement des équipements publics (écoles, espaces verts, infrastructure de transport). Le Pacte Logement 2.0 prévoit des mécanismes de convention entre communes et promoteurs.</li><li><strong>Convention de lotissement</strong> : document contractuel entre le promoteur et la commune qui fixe les spécifications techniques des VRD, le calendrier de réalisation, les garanties financières (caution bancaire) et les conditions de rétrocession.</li><li><strong>Taxe d'infrastructure</strong> : chaque commune fixe par règlement le montant des taxes de raccordement aux réseaux. Ces taxes s'ajoutent au coût des travaux de VRD.</li></ul>",
  faq1Q: "Qui paie les travaux de VRD dans un lotissement ?",
  faq1A: "Dans un lotissement au Luxembourg, le promoteur finance généralement l'intégralité des VRD internes (voiries internes, réseaux de distribution, éclairage, espaces verts) et contribue aux VRD externes (renforcement des réseaux en amont). Après réception des travaux, les voiries et réseaux sont rétrocédés à la commune qui en assure l'entretien. Le coût des VRD est répercuté dans le prix de vente des lots ou des logements.",
  faq2Q: "Quel est le coût de raccordement aux réseaux publics ?",
  faq2A: "Le coût dépend de la commune et du type de réseau. Pour l'eau potable : 1 500 à 5 000 EUR par lot. Pour l'assainissement : 2 000 à 8 000 EUR. Le raccordement électrique (Creos) : 2 000 à 6 000 EUR. La fibre optique (POST Luxembourg) est généralement gratuite pour les nouvelles constructions. Au total, les frais de raccordement représentent 8 000 à 20 000 EUR par lot.",
  faq3Q: "Comment gérer un terrain en pente pour les VRD ?",
  faq3A: "Un terrain en pente au Luxembourg (fréquent dans l'Oesling et les vallées) entraîne des surcoûts significatifs : murs de soutènement (150 à 500 EUR/m² de parement), terrassements importants, systèmes de drainage spécifiques, et canalisations sous pression. Le surcoût global peut atteindre 30 à 50 % par rapport à un terrain plat. Une étude topographique et géotechnique préalable est indispensable.",
  faq4Q: "Quel est le délai moyen de viabilisation d'un terrain ?",
  faq4A: "La viabilisation prend généralement 6 à 12 mois pour les travaux proprement dits, hors délais administratifs. Les phases préparatoires (études, autorisations communales) peuvent ajouter 6 à 18 mois. La réception provisoire a lieu à la fin des travaux, suivie d'une période de garantie d'un an avant la réception définitive et la rétrocession à la commune. Le délai total est typiquement de 18 à 36 mois."
};

data.convertisseurSurfaces.seo = {
  faqTitle: "Questions fréquentes sur les surfaces immobilières",
  relatedTitle: "Outils complémentaires",
  comprendreTitle: "Comprendre les surfaces immobilières au Luxembourg : SCB, SCP, utile, habitable",
  comprendreContent: "<p>Au Luxembourg, la multiplicité des définitions de surface est une source de confusion fréquente pour les acheteurs, les investisseurs et même les professionnels. Contrairement à la France où la loi Carrez impose une définition unique, le Grand-Duché utilise plusieurs référentiels qui coexistent :</p><ul><li><strong>Surface Construite Brute (SCB)</strong> : surface totale mesurée à l'extérieur des murs, incluant les murs, les gaines techniques et les parties communes. C'est la surface utilisée pour le calcul du COS dans les PAG/PAP.</li><li><strong>Surface de Construction Pure (SCP)</strong> : surface mesurée à l'intérieur des murs porteurs, excluant les gaines techniques mais incluant les cloisons intérieures. C'est la référence pour les coûts de construction (OAI FC.04).</li><li><strong>Surface Utile (SU)</strong> : surface réellement utilisable, excluant les murs, cloisons, gaines et escaliers internes. C'est la surface la plus pertinente pour comparer des logements.</li><li><strong>Surface Habitable</strong> : sous-ensemble de la surface utile, limitée aux pièces à usage d'habitation. Exclut les caves, greniers non aménagés et garages.</li></ul>",
  normesTitle: "Normes de référence : OAI FC.04 et ILNAS 101",
  normesContent: "<p>Deux normes principales encadrent le mesurage des surfaces au Luxembourg :</p><ul><li><strong>OAI FC.04 (Fiche de Calcul n°4)</strong> : publiée par l'Ordre des Architectes et Ingénieurs-Conseils, elle définit les méthodes de mesurage pour les projets de construction. Elle distingue la SCB, la SCP, la surface utile et les surfaces accessoires. C'est le référentiel utilisé par les architectes pour établir les plans et calculer les honoraires.</li><li><strong>ILNAS-EN 15221-6</strong> : norme européenne transposée au Luxembourg par l'ILNAS (Institut Luxembourgeois de la Normalisation). Elle harmonise les définitions de surface pour le facility management. Elle distingue la Gross Floor Area (GFA), la Net Floor Area (NFA) et la Net Room Area (NRA).</li></ul><p>La correspondance entre les deux référentiels n'est pas toujours directe, ce qui nécessite des tables de conversion. Notre outil intègre les ratios de conversion officiels publiés par l'OAI.</p>",
  ponderationTitle: "Pondération des surfaces accessoires : caves, balcons, terrasses, garages",
  ponderationContent: "<p>Dans la pratique immobilière luxembourgeoise, les surfaces accessoires ne sont pas comptabilisées à 100 % de leur valeur. Les coefficients de pondération standard sont :</p><ul><li><strong>Caves</strong> : coefficient de 0,25 à 0,50 selon la hauteur sous plafond et l'aménagement. Une cave aménagée (hauteur &gt; 2,20 m, éclairage naturel) sera pondérée à 0,50.</li><li><strong>Balcons</strong> : coefficient de 0,30 à 0,50. Un balcon couvert sera pondéré plus haut (0,50) qu'un balcon ouvert (0,30).</li><li><strong>Terrasses</strong> : coefficient de 0,25 à 0,50 selon la surface et l'exposition. Les grandes terrasses en attique peuvent être pondérées à 0,50.</li><li><strong>Jardins privatifs</strong> : coefficient de 0,10 à 0,20 selon la localisation et la surface.</li><li><strong>Garages et parkings</strong> : non pondérés dans la surface habitable, mais valorisés séparément (25 000 à 50 000 EUR par emplacement intérieur).</li></ul><p>Ces coefficients sont utilisés pour calculer la <strong>surface pondérée</strong> qui sert de base au prix au m² dans les transactions et les expertises.</p>",
  circulaireTitle: "Circulaire ACT sur les surfaces commerciales",
  circulaireContent: "<p>L'<strong>Administration des Contributions Directes (ACD)</strong> et l'<strong>Administration de l'Enregistrement (AED)</strong> utilisent des définitions de surface spécifiques pour les calculs fiscaux :</p><ul><li>La <strong>surface commerciale</strong> mentionnée dans les actes notariés au Luxembourg n'est pas définie par une loi unique. En pratique, elle correspond généralement à la SCP augmentée des surfaces accessoires pondérées.</li><li>Pour l'<strong>impôt foncier</strong> (Grundsteuer), la surface prise en compte est la surface utile incluant les annexes pondérées.</li><li>Pour les <strong>droits d'enregistrement</strong>, c'est la surface mentionnée dans l'acte notarié qui fait foi. Il est donc crucial que le notaire précise la méthode de mesurage utilisée.</li></ul><p>Notre convertisseur permet de basculer entre les différentes définitions et d'appliquer les coefficients de pondération adéquats pour obtenir une surface cohérente avec le contexte d'utilisation (transaction, expertise, fiscalité, gestion locative).</p>",
  faq1Q: "Quelle surface est utilisée pour calculer le prix au m² ?",
  faq1A: "Au Luxembourg, il n'existe pas de norme légale unique pour le prix au m². En pratique, les agences et les portails d'annonces utilisent la surface habitable (sans caves et garages) ou la surface utile (incluant les annexes pondérées). L'Observatoire de l'Habitat utilise la surface utile pour ses statistiques. Pour comparer des biens, assurez-vous d'utiliser la même définition de surface.",
  faq2Q: "La surface Carrez existe-t-elle au Luxembourg ?",
  faq2A: "Non, la loi Carrez est une disposition du droit français qui n'a pas d'équivalent au Luxembourg. Il n'existe pas d'obligation légale de mentionner une surface certifiée dans les actes de vente en copropriété. Toutefois, de plus en plus de promoteurs font appel à un géomètre assermenté pour certifier les surfaces, et certains notaires recommandent d'annexer un mesurage OAI FC.04 à l'acte de vente.",
  faq3Q: "Quel coefficient de pondération pour une terrasse au Luxembourg ?",
  faq3A: "Le coefficient varie selon les critères : pour une terrasse couverte attenante au séjour, le coefficient standard est de 0,50. Pour une terrasse ouverte de taille moyenne (10-20 m²), on retient généralement 0,30 à 0,40. Pour les grandes terrasses en attique (50+ m²), un coefficient dégressif est appliqué : 0,50 pour les 20 premiers m² et 0,25 au-delà.",
  faq4Q: "Quelle surface est prise en compte pour les impôts fonciers ?",
  faq4A: "Pour l'impôt foncier luxembourgeois (Grundsteuer), la base de calcul est la valeur unitaire (Einheitswert) déterminée par l'Administration des Contributions Directes. Cette valeur tient compte de la surface utile incluant les annexes pondérées. Toutefois, les valeurs unitaires n'ont pas été réévaluées depuis 1941, ce qui les rend largement déconnectées des surfaces et valeurs actuelles. Une réforme est en discussion depuis plusieurs années."
};

data.portfolio.seo = {
  faqTitle: "Questions fréquentes sur la gestion de patrimoine immobilier",
  relatedTitle: "Outils complémentaires",
  gestionTitle: "Gérer un patrimoine immobilier au Luxembourg",
  gestionContent: "<p>La <strong>gestion de patrimoine immobilier</strong> au Luxembourg requiert une approche structurée qui intègre les dimensions financière, fiscale, énergétique et juridique. Que vous déteniez 2 ou 20 biens, le suivi systématique de vos indicateurs de performance est essentiel pour optimiser votre rendement et anticiper les risques.</p><p>Le marché immobilier luxembourgeois présente des spécificités qui impactent la gestion de portefeuille : une fiscalité favorable aux revenus locatifs (déduction des intérêts, amortissement accéléré sous conditions), un cadre réglementaire strict en matière de baux d'habitation (loi du 21 septembre 2006), et une législation énergétique de plus en plus contraignante (directive EPBD, obligations CPE).</p><p>Notre outil Portfolio regroupe l'ensemble de vos évaluations et calculs tevaxia pour vous offrir une vision consolidée de votre patrimoine : valeur globale, rendement agrégé, exposition au risque de taux, répartition géographique et performance énergétique.</p>",
  indicateursTitle: "Indicateurs clés : rendement, LTV, répartition",
  indicateursContent: "<p>Les indicateurs de performance essentiels pour piloter votre portefeuille immobilier :</p><ul><li><strong>Rendement brut</strong> : rapport entre les loyers annuels encaissés et la valeur de marché du bien. Au Luxembourg, les rendements bruts résidentiels se situent entre 3,0 % et 4,5 % (2025). Les bureaux offrent des rendements de 4,0 à 5,5 %.</li><li><strong>Rendement net</strong> : rendement brut diminué des charges non récupérables, de la vacance, des travaux d'entretien, des assurances et de la taxe foncière. Le rendement net est typiquement inférieur de 1,0 à 1,5 point au rendement brut.</li><li><strong>Ratio LTV global</strong> : endettement total rapporté à la valeur totale du portefeuille. Un LTV supérieur à 60 % est considéré comme risqué. Les banques surveillent ce ratio pour les investisseurs multi-biens.</li><li><strong>Répartition géographique</strong> : la concentration sur une seule commune expose à un risque idiosyncratique. La diversification entre Luxembourg-Ville, la Ceinture Sud et le Nord réduit la volatilité.</li><li><strong>Répartition par type</strong> : mixer résidentiel et commercial permet de bénéficier de cycles économiques différents.</li></ul>",
  performanceTitle: "Suivi de la performance dans le temps",
  performanceContent: "<p>Le suivi temporel de la performance permet d'identifier les tendances et de prendre des décisions éclairées :</p><ul><li><strong>Évolution de la valeur</strong> : comparaison de la valeur du portefeuille à N et N-1, décomposée entre effet de marché (évolution des prix) et effet de périmètre (acquisitions/cessions).</li><li><strong>Évolution des loyers</strong> : suivi des indexations annuelles (IPCN pour les baux d'habitation, indices convenus pour les baux commerciaux) et des rebasements lors des renouvellements.</li><li><strong>Vacance</strong> : taux de vacance effectif comparé à la vacance structurelle de marché. Un taux supérieur à la moyenne peut signaler un problème de positionnement.</li><li><strong>CAPEX et travaux</strong> : suivi des investissements d'entretien et d'amélioration. La norme est de provisionner 1 à 2 % de la valeur du bien par an pour le maintien en état.</li></ul>",
  energieTitle: "Score CPE pondéré du parc immobilier",
  energieContent: "<p>La <strong>performance énergétique</strong> de votre portefeuille est devenue un enjeu stratégique majeur au Luxembourg :</p><ul><li><strong>Directive EPBD</strong> : la refonte de 2024 impose des trajectoires de rénovation ambitieuses. Les bâtiments les plus énergivores (classes F-G) devront atteindre la classe E d'ici 2030 et la classe D d'ici 2033.</li><li><strong>Score CPE pondéré</strong> : notre outil calcule un score énergétique moyen de votre parc, pondéré par la surface de chaque bien. Ce score permet d'identifier les passoires énergétiques et de prioriser les investissements de rénovation.</li><li><strong>Green premium / brown discount</strong> : au Luxembourg, les biens classés A-B bénéficient d'une prime de valeur de 5 à 8 %. Les biens classés F-G subissent une décote de 8 à 15 % et des conditions de financement plus restrictives.</li><li><strong>Aides à la rénovation</strong> : le dispositif PRIMe House offre des subventions généreuses (isolation, chauffage, énergies renouvelables) couvrant 30 à 50 % du coût des travaux de rénovation énergétique.</li></ul>",
  faq1Q: "Comment diversifier un portefeuille immobilier au Luxembourg ?",
  faq1A: "La diversification peut s'opérer sur plusieurs axes : géographique (Luxembourg-Ville vs Ceinture Sud vs Nord), typologique (résidentiel vs bureaux vs commercial), locatif (baux d'habitation vs baux commerciaux), et temporel (biens neufs vs anciens). Un portefeuille équilibré pourrait comprendre 60-70 % de résidentiel (revenus stables) et 30-40 % de commercial (rendements plus élevés).",
  faq2Q: "Quel rendement viser pour un investissement locatif au Luxembourg ?",
  faq2A: "Les rendements cibles varient selon la stratégie. Pour du résidentiel core (bien neuf, bien situé), visez un rendement net de 2,5 à 3,5 %. Pour du résidentiel value-add (bien à rénover), le rendement net cible après travaux est de 3,5 à 4,5 %. Pour des bureaux prime à Luxembourg-Ville, les rendements nets sont de 3,5 à 4,5 %. Comparez toujours avec les placements alternatifs (assurance-vie, obligations).",
  faq3Q: "Quelle est la fiscalité d'un patrimoine multi-biens au Luxembourg ?",
  faq3A: "Les revenus locatifs sont imposés au barème progressif (taux marginal de 42 % + contribution au fonds pour l'emploi de 9 %). Les charges déductibles incluent les intérêts d'emprunt, les frais d'entretien, les assurances, la taxe foncière et l'amortissement (2 % par an). Les plus-values de cession bénéficient d'un taux réduit après 2 ans de détention. La détention via une SCI ou un véhicule corporate peut offrir des avantages spécifiques.",
  faq4Q: "Quand faut-il vendre un bien de son portefeuille ?",
  faq4A: "Les signaux de vente incluent : un rendement net inférieur à 2 % sans perspective d'amélioration, des travaux majeurs à venir, une classe CPE F ou G avec un coût de rénovation disproportionné, un changement de dynamique du quartier, ou une opportunité de réinvestissement plus performante. Fiscalement, il est préférable de vendre après 2 ans de détention pour bénéficier du taux réduit sur les plus-values."
};

data.amlKyc.seo = {
  faqTitle: "Questions fréquentes sur l'AML/KYC immobilier",
  relatedTitle: "Outils complémentaires",
  obligationsTitle: "Obligations anti-blanchiment dans l'immobilier au Luxembourg",
  obligationsContent: "<p>La <strong>lutte contre le blanchiment d'argent</strong> (Anti-Money Laundering, AML) est une obligation majeure pour tous les professionnels de l'immobilier au Luxembourg. Le secteur immobilier est identifié par le GAFI (Groupe d'Action Financière) comme un vecteur de blanchiment particulièrement à risque en raison des montants élevés et de la complexité des structures de détention.</p><p>Au Luxembourg, les professionnels de l'immobilier (agents immobiliers, promoteurs, gestionnaires de biens, évaluateurs) sont assujettis aux obligations de vigilance depuis la transposition de la 4e directive européenne anti-blanchiment. La <strong>CSSF</strong> et le <strong>Ministère de la Justice</strong> assurent la supervision.</p><p>Les sanctions en cas de non-conformité sont sévères : amendes administratives pouvant atteindre 5 millions d'euros ou 10 % du chiffre d'affaires, sanctions pénales (emprisonnement de 1 à 5 ans), interdiction d'exercer et atteinte réputationnelle considérable.</p>",
  loi2004Title: "La loi du 12 novembre 2004 modifiée",
  loi2004Content: "<p>La <strong>loi du 12 novembre 2004</strong> relative à la lutte contre le blanchiment et le financement du terrorisme, modifiée à plusieurs reprises (notamment en 2018 et 2020 pour transposer les 4e et 5e directives AML), constitue le cadre légal de référence :</p><ul><li><strong>Champ d'application</strong> : toute personne physique ou morale qui, à titre professionnel, intervient dans des transactions portant sur l'achat, la vente, la location ou la gestion de biens immobiliers.</li><li><strong>Obligations principales</strong> : identification et vérification de l'identité du client et du bénéficiaire effectif, évaluation et gestion des risques de blanchiment, conservation des documents, formation du personnel, déclaration des opérations suspectes à la CRF.</li><li><strong>Approche basée sur les risques</strong> : mesures de vigilance renforcées pour les clients à haut risque (PPE, pays à risque, structures complexes).</li><li><strong>Registre des bénéficiaires effectifs (RBE)</strong> : les sociétés détenant des biens immobiliers doivent enregistrer leurs bénéficiaires effectifs auprès du RBE géré par le LBR (Luxembourg Business Registers).</li></ul>",
  identificationTitle: "Identification du client et vigilance renforcée",
  identificationContent: "<p>Les mesures d'identification et de vigilance (KYC — Know Your Customer) dans le secteur immobilier luxembourgeois comprennent :</p><ul><li><strong>Identification standard</strong> : vérification de l'identité (pièce d'identité officielle, passeport), de l'adresse (facture de service public, attestation bancaire) et de l'origine des fonds. Pour les personnes morales : statuts, extrait du RCS, identification des associés et des bénéficiaires effectifs (seuil de 25 %).</li><li><strong>Vigilance renforcée</strong> (Enhanced Due Diligence) : obligatoire pour les personnes politiquement exposées (PPE), les clients résidant dans des pays à haut risque (liste GAFI), les transactions inhabituellement complexes ou de montant élevé, et les structures de détention opaques.</li><li><strong>Vigilance simplifiée</strong> : possible pour les clients présentés par un confrère assujetti, les institutions publiques luxembourgeoises ou les sociétés cotées sur un marché réglementé de l'UE.</li><li><strong>Suivi continu</strong> : l'obligation de vigilance ne se limite pas à l'entrée en relation. Le professionnel doit actualiser les informations KYC régulièrement et surveiller les transactions.</li></ul>",
  declarationTitle: "Déclaration de soupçon et sanctions",
  declarationContent: "<p>Le dispositif de déclaration et de sanction est un pilier du système AML luxembourgeois :</p><ul><li><strong>Déclaration de soupçon</strong> : tout professionnel qui suspecte une transaction liée au blanchiment ou au financement du terrorisme doit adresser une déclaration à la <strong>Cellule de Renseignement Financier (CRF)</strong> du Parquet de Luxembourg. La déclaration doit être faite avant l'exécution de la transaction si possible.</li><li><strong>Tipping-off</strong> : il est strictement interdit d'informer le client ou un tiers qu'une déclaration a été déposée (article 5-1 de la loi).</li><li><strong>Sanctions administratives</strong> : amendes de 1 250 à 5 000 000 EUR pour les personnes morales. Le Ministère de la Justice peut prononcer un blâme, une interdiction temporaire d'exercer ou un retrait d'agrément.</li><li><strong>Sanctions pénales</strong> : le blanchiment est puni d'un emprisonnement de 1 à 5 ans et d'une amende de 1 250 à 1 250 000 EUR (article 506-1 du Code pénal). Le manquement aux obligations de déclaration est également puni pénalement.</li><li><strong>Registre des sanctions</strong> : les sanctions administratives sont publiées sur le site du Ministère de la Justice.</li></ul>",
  faq1Q: "Qui est assujetti aux obligations AML dans l'immobilier au Luxembourg ?",
  faq1A: "Sont assujettis : les agents immobiliers (inscrits au registre de commerce), les promoteurs immobiliers, les administrateurs de biens, les syndics de copropriété, les notaires (pour les transactions immobilières), les avocats (lorsqu'ils assistent des clients dans des opérations immobilières), et les experts en évaluation immobilière. Toute personne qui, à titre professionnel, intervient dans une transaction immobilière est potentiellement assujettie.",
  faq2Q: "Comment identifier une Personne Politiquement Exposée (PPE) ?",
  faq2A: "Une PPE est une personne exerçant ou ayant exercé une fonction politique, judiciaire ou administrative de premier plan : chefs d'État, ministres, parlementaires, hauts magistrats, ambassadeurs, officiers supérieurs des forces armées, dirigeants d'entreprises publiques. Les membres de leur famille proche et les personnes connues pour être étroitement associées sont également considérés comme PPE. Des bases de données spécialisées (World-Check, Dow Jones) permettent le screening systématique.",
  faq3Q: "Existe-t-il un seuil de déclaration pour les transactions immobilières ?",
  faq3A: "Il n'existe pas de seuil monétaire en dessous duquel l'obligation de vigilance ne s'applique pas. Toute transaction immobilière, quel que soit son montant, est soumise aux obligations KYC. En revanche, la déclaration de soupçon est basée sur des indices qualitatifs (comportement inhabituel du client, incohérence entre le profil et la transaction, recours à des structures complexes) et non sur un seuil quantitatif. Les paiements en espèces supérieurs à 10 000 EUR sont toutefois soumis à une obligation de déclaration spécifique.",
  faq4Q: "Combien de temps conserver les documents KYC ?",
  faq4A: "La loi du 12 novembre 2004 impose une conservation des documents et informations KYC pendant une durée minimale de 5 ans après la fin de la relation d'affaires ou après la date de la transaction occasionnelle. Les documents relatifs aux transactions doivent être conservés 5 ans après l'exécution de la transaction. En pratique, compte tenu des délais de prescription pénale au Luxembourg (5 à 10 ans), il est recommandé de conserver les documents pendant 10 ans."
};

fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
console.log('FR done, file size:', fs.statSync(filePath).size);
