"use client";
import {useMemo,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import LocaleLink from '@/components/LocaleLink';
import {getAllMarketData,slugifyCommune,MARKET_SOURCES} from '@/lib/market-data';
import {MARKET_OBSERVATIONS,MARKET_EVIDENCE_LABELS} from '@/lib/market-evidence';
import {PUBLISHED_MARKET_REPORTS} from '@/lib/published-market-data';
import {PriceEvolutionChart} from '@/components/PriceChart';
import {PdfButton} from '@/components/PdfButton';
import RelatedTools from '@/components/RelatedTools';
type Tab='residentiel'|'bureaux'|'commerces'|'logistique'|'terrains'|'macro';
type Field='commune'|'canton'|typeof MARKET_OBSERVATIONS[number][0];
function download(name:string,headers:string[],rows:unknown[][]){const cell=(v:unknown)=>'"'+String(v??'').replace(/"/g,'""')+'"',csv='\uFEFF'+[headers,...rows].map(row=>row.map(cell).join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export default function MarchePage(){
 const t=useTranslations('publishedMarket'),m=useTranslations('marche'),e=useTranslations('marketEvidence'),locale=useLocale();
 const [tab,setTab]=useState<Tab>('residentiel'),[query,setQuery]=useState(''),[sort,setSort]=useState<Field>('commune'),[ascending,setAscending]=useState(true);
 const format=(n:number,d=2)=>n.toLocaleString(locale==='lb'?'de-DE':locale,{minimumFractionDigits:d,maximumFractionDigits:d});
 const rows=useMemo(()=>getAllMarketData().filter(c=>(c.commune+' '+c.canton).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a,b)=>{const av=a[sort],bv=b[sort];if(av==null)return bv==null?0:1;if(bv==null)return -1;const diff=typeof av==='string'?av.localeCompare(String(bv)):av-Number(bv);return ascending?diff:-diff}),[query,sort,ascending]);
 const fields=['commune','canton',...MARKET_OBSERVATIONS.map(r=>r[0])] as Field[];
 const fieldLabel=(field:Field)=>field==='commune'||field==='canton'?m(field):e(MARKET_OBSERVATIONS.find(r=>r[0]===field)![1]);
 const report=tab==='bureaux'||tab==='commerces'||tab==='terrains'?PUBLISHED_MARKET_REPORTS[tab]:null;
 function sortBy(field:Field){if(sort===field)setAscending(!ascending);else{setSort(field);setAscending(true)}}
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12 [overflow-wrap:anywhere]">
  <h1 className="text-2xl font-bold text-navy sm:text-3xl">{t('title')}</h1><p className="mt-3 text-sm text-muted">{t('scope')}</p><LocaleLink href="/marche/forecast" className="mt-3 inline-block text-sm text-navy underline">{m('forecastLink')}</LocaleLink>
  <div className="my-6 flex flex-wrap gap-2" aria-label={t('segments')}>{(['residentiel','bureaux','commerces','logistique','terrains','macro'] as Tab[]).map(key=><button key={key} id={'market-tab-'+key} aria-pressed={tab===key} onClick={()=>setTab(key)} className={'rounded-lg border px-3 py-2 text-sm '+(tab===key?'bg-navy text-white':'border-card-border bg-card text-navy')}>{m('tab'+key[0].toUpperCase()+key.slice(1))}</button>)}</div>
  {tab==='residentiel'&&<section>
   <PriceEvolutionChart/><p className="mt-5 text-sm text-muted">{e('scope')}</p><p className="mt-2 text-sm text-muted">{t('noAggregate')}</p>
   <div className="mt-4 flex flex-wrap items-center gap-3"><input id="market-search" value={query} onChange={ev=>setQuery(ev.target.value)} aria-label={m('searchCommuneCanton')} placeholder={m('searchCommuneCanton')} className="min-w-0 flex-1 rounded-lg border border-input-border bg-input-bg p-3 text-sm"/><button id="market-export" onClick={()=>download('marche-residentiel.csv',[...fields,'periode','source'],rows.map(c=>[...fields.map(k=>c[k]),c.periode,c.source]))} className="rounded-lg border border-card-border px-3 py-2 text-sm">{m('exportCSV')}</button>{rows.length>0&&<PdfButton label="PDF" filename="marche-communes.pdf" generateBlob={async()=>{const {generateMarchePdfBlob}=await import('@/components/ToolsPdf');return generateMarchePdfBlob({communes:rows,locale,title:t('pdfTitle'),countLabel:m('communeCount',{count:rows.length}),scope:t('noAggregate'),labels:Object.fromEntries(MARKET_EVIDENCE_LABELS.map(k=>[k,e(k)])) as Record<typeof MARKET_EVIDENCE_LABELS[number],string>})}}/>}</div>
   <p className="mt-2 text-sm text-muted">{m('communeCount',{count:rows.length})}</p><div className="mt-3 overflow-x-auto rounded-xl border border-card-border"><table className="w-full text-sm"><thead><tr>{fields.map(field=><th key={field} aria-sort={sort===field?(ascending?'ascending':'descending'):'none'} className="min-w-36 p-3 text-left"><button onClick={()=>sortBy(field)}>{fieldLabel(field)} {sort===field?(ascending?'↑':'↓'):''}</button></th>)}<th className="min-w-48 p-3 text-left">{e('period')}</th></tr></thead><tbody>{rows.map(c=><tr key={c.commune} data-market-row={c.commune} className="border-t border-card-border">{fields.map(field=><td key={field} className="p-3">{field==='commune'?<LocaleLink href={'/commune/'+slugifyCommune(c.commune)} className="text-navy underline">{c.commune}</LocaleLink>:field==='canton'?c.canton:c[field]==null?e('unpublished'):format(c[field]!,MARKET_OBSERVATIONS.find(r=>r[0]===field)![2]==='count'?0:2)+(MARKET_OBSERVATIONS.find(r=>r[0]===field)![2]==='count'?'':' €')}</td>)}<td className="p-3">{c.periode}</td></tr>)}</tbody></table></div>{rows.length===0&&<p role="status" className="mt-3 text-sm">{m('noCommuneFound')}</p>}
   <div className="mt-3 flex flex-wrap gap-3 text-sm underline">{([['transactions','sourceSales'],['annonces','sourceAsking'],['loyers','sourceRent']] as const).map(([key,label])=><a key={key} href={MARKET_SOURCES[key]} target="_blank" rel="noopener noreferrer">{e(label)}</a>)}</div>
  </section>}
  {report&&<section data-published-report className="rounded-xl border border-card-border bg-card p-4 sm:p-6"><h2 className="font-semibold text-navy">{report.title}</h2><p className="mt-2 text-sm">{e('period')}: {report.period}</p><p className="mt-3 text-sm text-muted">{t(report.scope)}</p><dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{report.rows.map(r=><div key={r.key} className="min-w-0 rounded-lg bg-navy/5 p-3"><dt className="text-sm text-muted">{t(r.key)}</dt><dd data-market-metric={r.key} className="mt-2 text-xl font-bold text-navy">{format(r.value,r.unit==='count'||r.unit==='m²'||r.unit==='€'?0:2)} {r.unit==='count'?'':r.unit==='€/m²/month'?t('rentUnit'):r.unit}</dd></div>)}</dl><a className="mt-4 inline-block text-sm underline" href={report.url} target="_blank" rel="noopener noreferrer">{t('report')}</a><button id="market-report-export" onClick={()=>download('marche-'+tab+'.csv',['indicator','value','unit','period','source','url','page','scope'],report.rows.map(r=>[t(r.key),r.value,r.unit,report.period,report.title,report.url,r.page,t(report.scope)]))} className="ml-3 mt-4 rounded-lg border border-card-border px-3 py-2 text-sm">{m('exportCSV')}</button></section>}
  {(tab==='logistique'||tab==='macro')&&<section className="rounded-xl border border-card-border bg-card p-4 text-sm"><h2 className="font-semibold">{t('unavailableTitle')}</h2><p className="mt-3 text-muted">{t(tab==='logistique'?'logisticsScope':'macroScope')}</p>{tab==='macro'?<div className="mt-4 flex flex-wrap gap-4"><a href="https://www.bcl.lu/fr/statistiques/series_statistiques_luxembourg/03_marche_capitaux_interets/index.html" className="underline" target="_blank" rel="noopener noreferrer">BCL</a><a href="https://lustat.statec.lu/" className="underline" target="_blank" rel="noopener noreferrer">STATEC / LUSTAT</a><LocaleLink href="/indices" className="underline">{m('indices')}</LocaleLink></div>:<LocaleLink href="/valorisation" className="mt-4 inline-block underline">{t('valuation')}</LocaleLink>}</section>}
  <RelatedTools keys={['carte','indices','estimation','valorisation']}/>
 </main>;
}
