import {describe,it,expect} from 'vitest';
import {calculateAcquisition,acquisitionIrr,acquisitionCsv,parseAcquisition,type AcquisitionInput} from '../hotellerie/acquisition-evidence';
const fixture=():AcquisitionInput=>({version:1,name:'Hotel',price:100000,entryCosts:10000,entryCapex:10000,entryReference:'Purchase and quotes',debt:60000,annualRatePct:0,months:24,monthlyCosts:0,loanReference:'Offer',exitPrice:110000,exitCosts:10000,exitReference:'Sale assumption',discountPct:10,discountReference:'Required equity return',years:[{cash:40000,reference:'Year 1'},{cash:40000,reference:'Year 2'}]});
describe('documented acquisition',()=>{
 it('balances initial funding and all final proceeds without counting equity twice',()=>{const r=calculateAcquisition(fixture());expect(r.initialEquity).toBe(60000);expect(r.monthlyPayment).toBe(2500);expect(r.years[0].debtService).toBe(30000);expect(r.years[0].dscr).toBeCloseTo(4/3);expect(r.exitDebt).toBe(0);expect(r.netExit).toBe(100000);expect(r.distributed).toBe(120000);expect(r.multiple).toBe(2);expect(r.netGain).toBe(60000);expect(r.npv).toBeCloseTo(-60000+10000/1.1+110000/1.21);const rate=r.irr!/100;expect(-60000+10000/(1+rate)+110000/(1+rate)**2).toBeCloseTo(0,5)});
 it('stops debt service at maturity and subtracts residual principal only on exit',()=>{let i=fixture();i.months=12;let r=calculateAcquisition(i);expect(r.years[1].debtService).toBe(0);expect(r.years[1].dscr).toBeNull();i=fixture();i.months=120;r=calculateAcquisition(i);expect(r.exitDebt).toBe(48000);expect(r.netExit).toBe(52000)});
 it('counts fees only in repayment months including a partial first year',()=>{const i=fixture();i.months=7;i.monthlyCosts=100;const r=calculateAcquisition(i);expect(r.years[0].debtMonths).toBe(7);expect(r.years[0].debtService).toBeCloseTo(60700);expect(r.years[1].debtService).toBe(0)});
 it('includes subsequent equity contributions and preserves exit losses',()=>{const i=fixture();i.years[0].cash=-10000;i.exitPrice=0;const r=calculateAcquisition(i);expect(r.contributed).toBe(100000);expect(r.distributed).toBe(0);expect(r.netGain).toBe(-100000);expect(r.irr).toBeNull();expect(r.netExit).toBe(-10000)});
 it('does not invent an IRR for ambiguous or absent contributions',()=>{expect(acquisitionIrr([-100,230,-132])).toBeNull();expect(acquisitionIrr([0,100,100])).toBeNull();expect(acquisitionIrr([-100,110])).toBeCloseTo(10);expect(acquisitionIrr([-100,50])).toBeCloseTo(-50)});
 it('rejects incomplete, nonfinite, overfinanced and legacy snapshots',()=>{for(const patch of [{price:NaN},{debt:120001},{months:1.5},{entryReference:''},{years:[]},{exitPrice:Infinity},{version:0}])expect(()=>calculateAcquisition({...fixture(),...patch} as AcquisitionInput)).toThrow();expect(()=>parseAcquisition('{"asking_price":100}')).toThrow();expect(parseAcquisition(JSON.stringify(fixture()))).toEqual(fixture())});
 it('exports assumptions and annual cash with explicit units and formula escaping',()=>{const i=fixture();i.name='=TEST';const csv=acquisitionCsv(i);expect(csv).toContain('"\'=TEST"');expect(csv).toContain('"year_1";"reference";"Year 1";"text"');expect(csv).toContain('"result";"multiple";"2";"times"')});
});
