import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {evaluerTerreAgricole,agriculturalCsv,type AgriculturalInput} from '../agricultural';
import {AGRICULTURAL_REFERENCE as data} from '../agricultural-reference';
const input:AgriculturalInput={surfaceHa:2.5,priceHa:40000.25,priceReference:'Comparable contract',buildingValue:10000,buildingReference:'Retained barn',demolitionCost:2000,demolitionReference:'Shed quote',remediationCost:3000,remediationReference:'Site quote',rightsReference:'Lease and tax basis reviewed'};
describe('documented agricultural calculation',()=>{
 it('converts hectares and adds only documented contributions and costs in cents',()=>{const r=evaluerTerreAgricole(input);expect(r.surfaceM2).toBe(25000);expect(r.landValue).toBe(100000.63);expect(r.netValue).toBe(105000.63)});
 it('preserves explicit zero and negative net results without an automatic lease haircut',()=>{expect(evaluerTerreAgricole({...input,buildingValue:0,demolitionCost:0,remediationCost:0}).netValue).toBe(100000.63);expect(evaluerTerreAgricole({...input,demolitionCost:200000}).netValue).toBe(-92999.37);expect(evaluerTerreAgricole({...input,rightsReference:'Existing rural lease'}).landValue).toBe(100000.63)});
 it('rejects unknown amounts, invalid areas, excess precision and missing supporting references',()=>{for(const patch of [{surfaceHa:0},{surfaceHa:-1},{surfaceHa:.00001},{priceHa:NaN},{buildingValue:Infinity},{demolitionCost:-1},{priceHa:1.001},{remediationReference:''}])expect(()=>evaluerTerreAgricole({...input,...patch})).toThrow()});
 it('exports every reference and protects CSV cells',()=>{const csv=agriculturalCsv({...input,priceReference:'=1+1'});expect(csv).toContain("'=1+1");expect(csv).toContain('105000.63');expect(csv).toContain('Lease and tax basis reviewed')});
 it('matches all 66 official observations and source byte hashes without reconstructing the combined median',()=>{const raw=readFileSync('docs/sources/agricultural-land-d2121-2026-09-09.csv');expect(createHash('sha256').update(raw).digest('hex')).toBe(data.csvSha256);expect(createHash('sha256').update(readFileSync('docs/sources/agricultural-land-d2121-structure.xml')).digest('hex')).toBe(data.structureSha256);const rows=raw.toString().trim().split(/\r?\n/).filter(Boolean).slice(1).map(row=>row.split(','));expect(rows.length).toBe(66);for(const row of rows){const observation=data.observations.find(r=>r.year===Number(row[3]));const key=Object.entries(data.codes).find(([,code])=>code===row[2])![0] as 'arable'|'grassland'|'combinedMedian';expect(observation?.[key]).toBe(Number(row[4]))}expect(data.observations.at(-1)).toEqual({year:2024,arable:48180,grassland:48700,combinedMedian:48455});expect(data.observations.at(-1)!.combinedMedian).not.toBe((48180+48700)/2)});
});
