import {describe,it,expect} from 'vitest';
import {calculateCompset,parseCompset,compsetCsv,type CompsetInput} from '../hotellerie/compset-evidence';
const fixture=():CompsetInput=>({version:1,start:'2024-02-01',end:'2024-02-29',selectionReference:'Same market and room revenue basis',hotels:[{id:'a',name:'A',role:'benchmark',rooms:10,available:100,sold:50,revenue:5000,reference:'A records'},{id:'b',name:'B',role:'benchmark',rooms:20,available:300,sold:240,revenue:36000,reference:'B records'},{id:'s',name:'Subject',role:'subject',rooms:10,available:100,sold:70,revenue:9800,reference:'Subject records'}]});
describe('documented hotel comparisons',()=>{
 it('aggregates revenues and room nights instead of averaging ratios',()=>{const r=calculateCompset(fixture());expect(r.days).toBe(29);expect(r.benchmarkCount).toBe(2);expect(r.totals.available).toBe(400);expect(r.totals.sold).toBe(290);expect(r.totals.revenue).toBe(41000);expect(r.totals.adr).toBeCloseTo(41000/290);expect(r.totals.occupancyPct).toBe(72.5);expect(r.totals.revpar).toBe(102.5);expect(r.totals.adr).not.toBe(125)});
 it('excludes subject and computes indices consistently',()=>{const r=calculateCompset(fixture());expect(r.ari).toBeCloseTo(140/(41000/290)*100);expect(r.mpi).toBeCloseTo(70/72.5*100);expect(r.rgi).toBeCloseTo(98/102.5*100);expect(r.ari!*r.mpi!/100).toBeCloseTo(r.rgi!)});
 it('distinguishes zero activity from unavailable denominators',()=>{const i=fixture();i.hotels=i.hotels.slice(0,1);i.hotels[0].sold=0;i.hotels[0].revenue=0;let r=calculateCompset(i);expect(r.totals.adr).toBeNull();expect(r.totals.occupancyPct).toBe(0);expect(r.totals.revpar).toBe(0);expect(r.ari).toBeNull();i.hotels[0].available=0;r=calculateCompset(i);expect(r.totals.occupancyPct).toBeNull();expect(r.totals.revpar).toBeNull()});
 it('rejects invalid periods, impossible counts, missing references and duplicate roles',()=>{for(const patch of [{end:'2024-02-30'},{end:'2024-01-01'},{selectionReference:''},{hotels:[]}])expect(()=>calculateCompset({...fixture(),...patch})).toThrow();for(const patch of [{sold:101},{available:291},{revenue:NaN},{rooms:1.5},{reference:''},{id:'b'},{role:'subject'}]){const i=fixture();Object.assign(i.hotels[0],patch);expect(()=>calculateCompset(i)).toThrow()}});
 it('preserves source data in snapshots and export units',()=>{const i=fixture();expect(parseCompset(JSON.stringify(i))).toEqual(i);expect(()=>parseCompset('{"adr":125}')).toThrow();i.hotels[0].name='=TEST';const csv=compsetCsv(i);expect(csv).toContain('"\'=TEST"');expect(csv).toContain('"benchmark";"sold";"290";"sold-room-nights"');expect(csv).toContain('"hotel_s";"reference";"Subject records";"text"')});
});
