import {describe,it,expect} from 'vitest';
import {calculateDevelopment,developmentCsv,parseDevelopmentSnapshot,type DevelopmentInput} from '../development-appraisal';
const fixture:DevelopmentInput={version:1,name:'Project',mode:'known',taxReference:'Net recoverable VAT confirmed',targetPct:15,targetReference:'Target decision',landPrice:200000,landMonth:1,landReference:'Contract',acquisitionFixed:10000,acquisitionPct:7,acquisitionReference:'Declared costs',lines:[{id:'r',kind:'revenue',label:'Sales',amount:1000000,month:3,reference:'Sales plan'},{id:'w',kind:'works',label:'Works',amount:600000,month:2,reference:'Quote'},{id:'f',kind:'finance',label:'Finance',amount:20000,month:3,reference:'Lender schedule'}]};
describe('documented development appraisal',()=>{
 it('separates actual projected profit, target and all-in acquisition costs; schedule reconciles',()=>{const r=calculateDevelopment(fixture);expect(r.acquisition).toBe(24000);expect(r.profit).toBe(156000);expect(r.target).toBe(150000);expect(r.headroom).toBe(6000);expect(r.profitPct).toBe(15.6);expect(r.timeline.at(-1)?.cumulative).toBe(r.profit);expect(r.maximumBudgetDeficit).toBe(844000)});
 it('solves land price plus acquisition costs without calling residual the profit',()=>{const r=calculateDevelopment({...fixture,mode:'residual',landPrice:null});expect(r.residualBudget).toBe(220000);expect(r.landCapacity).toBe(205607.47);expect(r.profit).toBeNull();expect(r.timeline).toEqual([]);expect(calculateDevelopment({...fixture,landPrice:r.landCapacity}).headroom).toBeGreaterThanOrEqual(0)});
 it('retains losses and negative residual budget without negative acquisition charges',()=>{const lines=fixture.lines.map(l=>l.kind==='revenue'?{...l,amount:500000}:l);expect(calculateDevelopment({...fixture,lines}).profit).toBe(-344000);const r=calculateDevelopment({...fixture,lines,mode:'residual',landPrice:null});expect(r.residualBudget).toBe(-205000);expect(r.landCapacity).toBeNull()});
 it('rounds proportional amounts in cents and preserves explicit zero costs',()=>{const r=calculateDevelopment({...fixture,landPrice:.1,acquisitionPct:5,acquisitionFixed:0});expect(r.acquisition).toBe(.01);expect(calculateDevelopment({...fixture,acquisitionPct:0,acquisitionFixed:0}).acquisition).toBe(0)});
 it('rejects missing, invalid, duplicated and out-of-scope data',()=>{for(const patch of [{targetPct:NaN},{acquisitionFixed:-1},{landPrice:null},{taxReference:''},{acquisitionReference:''},{targetPct:100.1},{landMonth:0}])expect(()=>calculateDevelopment({...fixture,...patch})).toThrow();for(const patch of [{amount:1.001},{amount:Infinity},{month:1.5},{reference:''}])expect(()=>calculateDevelopment({...fixture,lines:[fixture.lines[0],{...fixture.lines[1],...patch}]})).toThrow();expect(()=>calculateDevelopment({...fixture,lines:[fixture.lines[0],fixture.lines[0]]})).toThrow()});
 it('round-trips every assumption and rejects old incomplete snapshots atomically',()=>{expect(parseDevelopmentSnapshot(JSON.stringify(fixture))).toEqual(fixture);expect(()=>parseDevelopmentSnapshot('{"surfaceVendable":2000}')).toThrow();expect(()=>parseDevelopmentSnapshot(JSON.stringify({...fixture,mode:'residual',landReference:{}}))).toThrow();const csv=developmentCsv({...fixture,name:'=1+1'});expect(csv).toContain("'"+'=1+1');expect(csv).toContain('Lender schedule');expect(csv).toContain('net_of_recoverable_VAT_including_nonrecoverable_VAT');expect(csv).toContain('156000')});
});
