import {describe,it,expect} from 'vitest';
import {calculateHotelCoverage,hotelCoverageCsv,type HotelCoverageInput} from '../hotellerie/coverage';
const input:HotelCoverageInput={name:'Hotel fixture',principal:120000,annualRatePct:0,months:120,monthlyCosts:0,upfrontCosts:0,loanReference:'Offer',annualCash:15000,cashReference:'Available cash calculation',target:1.25,targetReference:'Covenant',propertyValue:200000,valueReference:'Valuation',stressedAnnualCash:12000,stressReference:'Scenario'};
describe('documented hotel debt coverage',()=>{
 it('supports zero interest and solves the same annuity for target capacity',()=>{const r=calculateHotelCoverage(input);expect(r.monthlyPayment).toBe(1000);expect(r.dscr).toBe(1.25);expect(r.stressDscr).toBe(1);expect(r.capacity).toBe(120000);expect(r.ltv).toBe(60);expect(r.interest).toBe(0);expect(r.years.at(-1)?.remaining).toBe(0)});
 it('includes recurring fees once and keeps upfront costs outside recurring debt service',()=>{const r=calculateHotelCoverage({...input,monthlyCosts:100,upfrontCosts:200});expect(r.annualDebtService).toBe(13200);expect(r.dscr).toBeCloseTo(15000/13200);expect(r.capacity).toBe(108000);expect(r.totalRepayment).toBe(132200)});
 it('prorates both cash and service over the final partial period',()=>{const r=calculateHotelCoverage({...input,principal:7000,months:7});expect(r.years).toHaveLength(1);expect(r.years[0].months).toBe(7);expect(r.years[0].debtService).toBe(7000);expect(r.years[0].cash).toBe(8750);expect(r.years[0].dscr).toBe(1.25);expect(r.years[0].remaining).toBe(0)});
 it('retains losses and leaves debt-free coverage or absent LTV undefined',()=>{expect(calculateHotelCoverage({...input,annualCash:-15000}).dscr).toBe(-1.25);const r=calculateHotelCoverage({...input,principal:0,propertyValue:null});expect(r.dscr).toBeNull();expect(r.stressDscr).toBeNull();expect(r.ltv).toBeNull();expect(r.years).toEqual([])});
 it('uses the amortization engine consistently at positive rates and rejects invalid data',()=>{const r=calculateHotelCoverage({...input,annualRatePct:4.5,months:121});expect(r.years.at(-1)?.months).toBe(1);expect(r.years.reduce((s,y)=>s+y.principal,0)).toBeCloseTo(120000,6);expect(r.years.at(-1)?.remaining).toBe(0);for(const patch of [{months:1.5},{annualRatePct:NaN},{annualCash:Infinity},{target:0},{loanReference:''},{propertyValue:0},{principal:0,monthlyCosts:1}])expect(()=>calculateHotelCoverage({...input,...patch})).toThrow()});
 it('exports inputs and ratios with explicit units',()=>{const csv=hotelCoverageCsv({...input,name:'=1+1'});expect(csv).toContain("'=1+1");expect(csv).toContain('EUR/year');expect(csv).toContain('times');expect(csv).toContain('Covenant');expect(csv).toContain('Available cash calculation')});
});
