import {describe,it,expect} from 'vitest';
import {calculateHotelValue,hotelValueCsv,type HotelValueInput} from '../hotellerie/value-evidence';
const input:HotelValueInput={name:'Hotel fixture',valuationDate:'2026-09-09',rooms:20,rightsReference:'Property and specified fixtures',incomeEnabled:true,comparisonEnabled:true,annualIncome:100000,incomeReference:'Stabilised annual net income',capRatePct:5,rateReference:'Income yield evidence',comparables:[{id:'a',name:'A',date:'2025-01-01',price:1000000,rooms:10,adjustmentPct:10,adjustmentReference:'Condition adjustment',weight:1,reference:'Transaction A'},{id:'b',name:'B',date:'2026-01-01',price:2400000,rooms:20,adjustmentPct:-5,adjustmentReference:'Location adjustment',weight:3,reference:'Transaction B'}]};
describe('evidenced hotel valuation',()=>{
 it('separates direct capitalisation and weighted comparable prices without arbitrary averaging',()=>{const r=calculateHotelValue(input);expect(r.incomeValue).toBe(2000000);expect(r.selectedPricePerRoom).toBe(113000);expect(r.comparisonValue).toBe(2260000);expect(r.comparables.map(c=>c.normalizedWeight)).toEqual([25,75])});
 it('does not equate a nonpositive income with zero property value',()=>{expect(calculateHotelValue({...input,annualIncome:0}).incomeValue).toBeNull();expect(calculateHotelValue({...input,annualIncome:-100}).incomeValue).toBeNull();expect(calculateHotelValue({...input,annualIncome:-100}).comparisonValue).toBe(2260000)});
 it('allows either documented method independently',()=>{expect(calculateHotelValue({...input,incomeEnabled:false,annualIncome:NaN,capRatePct:NaN}).comparisonValue).toBe(2260000);expect(calculateHotelValue({...input,comparisonEnabled:false,comparables:[]}).incomeValue).toBe(2000000)});
 it('rejects unsupported rates, dates, room counts, references, weights and comparables after the valuation date',()=>{for(const patch of [{rooms:0},{rooms:1.2},{capRatePct:0},{annualIncome:Infinity},{rightsReference:''},{valuationDate:'2026-02-30'},{incomeEnabled:false,comparisonEnabled:false}])expect(()=>calculateHotelValue({...input,...patch})).toThrow();expect(()=>calculateHotelValue({...input,comparables:input.comparables.map(c=>({...c,weight:0}))})).toThrow();expect(()=>calculateHotelValue({...input,comparables:[{...input.comparables[0],date:'2027-01-01'}]})).toThrow();expect(()=>calculateHotelValue({...input,comparables:[{...input.comparables[0],reference:''}]})).toThrow()});
 it('exports source transactions, normalized weights, dates, units and independent results',()=>{const csv=hotelValueCsv({...input,name:'=1+1'});expect(csv).toContain("'=1+1");expect(csv).toContain('2260000');expect(csv).toContain('2000000');expect(csv).toContain('2025-01-01');expect(csv).toContain('Transaction B');expect(csv).toContain('EUR/room')});
});
