import {describe,it,expect} from 'vitest';
import {HOTEL_OPERATING_KINDS,calculateHotelOperating,hotelOperatingCsv,type HotelOperatingInput} from '../hotellerie/operating';
const values=[29000,5000,1000,8000,4000,2000,3000,1000,500,1500,2000];
const input:HotelOperatingInput={name:'Hotel test',start:'2024-02-01',end:'2024-02-29',rooms:20,availableRoomNights:580,soldRoomNights:290,capacityReference:'PMS',accountingReference:'Accounts net recoverable VAT',lines:HOTEL_OPERATING_KINDS.map((kind,i)=>({id:kind,kind,label:kind,amount:values[i],reference:'Ledger'}))};
describe('documented hotel operating statement',()=>{
 it('counts actual leap-year days and calculates KPIs from supplied sold/available room nights',()=>{const r=calculateHotelOperating(input);expect(r.days).toBe(29);expect(r.theoreticalRoomNights).toBe(580);expect(r.occupancy).toBe(50);expect(r.adr).toBe(100);expect(r.revpar).toBe(50)});
 it('counts payroll once and separates GOP, EBITDA and replacement reserve',()=>{const r=calculateHotelOperating(input);expect(r.revenue).toBe(35000);expect(r.payroll).toBe(10000);expect(r.departmentalProfit).toBe(23000);expect(r.gop).toBe(18000);expect(r.ebitda).toBe(16000);expect(r.afterReserve).toBe(14000);expect(r.goppar).toBeCloseTo(18000/580);expect(r.ebitdaMargin).toBeCloseTo(16000/35000*100)});
 it('uses explicit unavailable inventory and keeps genuine zero demand and undefined ratios',()=>{const r=calculateHotelOperating({...input,availableRoomNights:400});expect(r.unavailableRoomNights).toBe(180);expect(r.occupancy).toBe(72.5);const closed=calculateHotelOperating({...input,availableRoomNights:0,soldRoomNights:0,lines:input.lines.map(l=>({...l,amount:l.kind.endsWith('Revenue')?0:l.amount}))});expect(closed.adr).toBeNull();expect(closed.revpar).toBeNull();expect(closed.occupancy).toBeNull();expect(closed.ebitda).toBe(-19000)});
 it('rejects invented dates, fractional or inconsistent capacity, missing categories and non-finite costs',()=>{for(const patch of [{end:'2023-02-29'},{end:'2024-01-31'},{end:'2026-01-01'},{rooms:1.2},{availableRoomNights:581},{soldRoomNights:581},{capacityReference:''}])expect(()=>calculateHotelOperating({...input,...patch})).toThrow();expect(()=>calculateHotelOperating({...input,lines:input.lines.slice(1)})).toThrow();expect(()=>calculateHotelOperating({...input,lines:input.lines.map((l,i)=>i?l:{...l,amount:NaN})})).toThrow();expect(()=>calculateHotelOperating({...input,soldRoomNights:0})).toThrow()});
 it('exports all inputs, categories, references and separate reserve results',()=>{const csv=hotelOperatingCsv({...input,name:'=1+1'});expect(csv).toContain("'=1+1");expect(csv).toContain('16000');expect(csv).toContain('14000');expect(csv).toContain('2024-02-29');expect(csv).toContain('Ledger')});
});
