import {describe,it,expect} from 'vitest';
import {EMPTY_TAXONOMY,screenTaxonomy,type TaxonomyInput} from '../taxonomy';
const old:TaxonomyInput={...EMPTY_TAXONOMY,period:'before',use:'residential',epc:'A',epcEvidence:'yes',adaptation:'yes',safeguards:'yes'};
const check=(i:TaxonomyInput,key:string)=>screenTaxonomy(i).checks.find(c=>c.key===key)?.status;
describe('Taxonomy 7.7 preliminary document screening',()=>{
 it('does not accept class B as the EPC A pathway',()=>{expect(check({...old,epc:'B'},'energy')).toBe('unmet');expect(check({...old,epc:'A+'},'energy')).toBe('met');expect(screenTaxonomy(old).status).toBe('review')});
 it('requires explicit top-15 evidence and valid comparable PED',()=>{const i={...old,route:'top15' as const,ped:70,threshold:70};expect(screenTaxonomy(i).status).toBe('incomplete');expect(screenTaxonomy({...i,thresholdEvidence:'yes'}).status).toBe('review');expect(check({...i,ped:70.001},'energy')).toBe('unmet')});
 it('checks exact nZEB minus 10% and additional requirements above 5000 m²',()=>{const i:TaxonomyInput={...old,period:'after',ped:45,threshold:50,thresholdEvidence:'yes',area:5000};expect(screenTaxonomy(i).limit).toBe(45);expect(screenTaxonomy(i).status).toBe('review');expect(check({...i,ped:45.001},'energy')).toBe('unmet');expect(screenTaxonomy({...i,area:5000.01}).status).toBe('incomplete');expect(screenTaxonomy({...i,area:5001,envelope:'yes',gwp:'yes'}).status).toBe('review')});
 it('requires monitoring only for non-residential systems strictly above 290 kW',()=>{const i:TaxonomyInput={...old,use:'nonResidential',power:290};expect(check(i,'monitoring')).toBe('notApplicable');expect(check({...i,power:290.01},'monitoring')).toBe('missing');expect(screenTaxonomy({...i,power:300,monitoring:'yes'}).status).toBe('review');expect(check({...old,power:300},'monitoring')).toBe('notApplicable')});
 it('keeps missing/invalid data unresolved and never substitutes a threshold',()=>{expect(screenTaxonomy(EMPTY_TAXONOMY).status).toBe('incomplete');for(const n of [NaN,Infinity,-1]){expect(check({...old,route:'top15',ped:n,threshold:75},'energy')).toBe('missing');expect(check({...old,route:'top15',ped:40,threshold:n},'energy')).toBe('missing')}expect(check({...old,route:'top15',ped:0,threshold:0},'energy')).toBe('missing')});
 it('does not certify alignment, or add irrelevant DNSH axes and arbitrary scores',()=>{const r=screenTaxonomy(old);expect(r).not.toHaveProperty('aligned');expect(r).not.toHaveProperty('score');expect(r.checks.map(c=>c.key)).not.toContain('water');expect(screenTaxonomy({...old,adaptation:'no'}).status).toBe('issues');expect(screenTaxonomy({...old,safeguards:'unknown'}).status).toBe('incomplete')});
});
