import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {TOURISM_MONTHS,TOURISM_SOURCES,tourismYear,tourismCsv} from '../hotellerie/tourism-evidence';
describe('published Luxembourg tourism series',()=>{
 it('matches every observation and checksum in the official snapshots',()=>{for(const [key,s] of Object.entries(TOURISM_SOURCES)){const raw=readFileSync('docs/sources/'+s.file);expect(createHash('sha256').update(raw).digest('hex')).toBe(s.sha256);const d=JSON.parse(raw.toString());expect(d.dimension.geo.category.index).toEqual({LU:0});expect(d.updated).toBe(s.updated);if(key==='rooms')expect(d.dimension.accomunit.category.index).toEqual({BEDRM:0});else expect(d.dimension.nace_r2.category.index).toEqual({I551:0});for(const row of TOURISM_MONTHS){const pos=d.dimension.time.category.index[row.period];expect(row[key==='rooms'?'roomOccupancyPct':key as 'nights'|'arrivals']).toBe(d.value[String(pos)]??null)}}});
 it('retains published precise values and unpublished month as missing',()=>{expect(TOURISM_MONTHS[0]).toEqual({period:'2023-01',nights:106284,arrivals:57791,roomOccupancyPct:33.04});expect(TOURISM_MONTHS.at(-1)).toEqual({period:'2026-07',nights:null,arrivals:null,roomOccupancyPct:null});expect(tourismYear(2025).nights).toBe(2019907);expect(tourismYear(2025).months).toBe(12)});
 it('compares a partial year with the same months of the preceding year',()=>{const r=tourismYear(2026);expect(r.months).toBe(6);const prior=TOURISM_MONTHS.filter(m=>m.period>='2025-01'&&m.period<='2025-06').reduce((s,m)=>s+m.nights!,0);expect(r.previousNights).toBe(prior);expect(r.changePct).toBeCloseTo((r.nights!/prior-1)*100);expect(tourismYear(2023).changePct).toBeNull();expect(tourismYear(2022).nights).toBeNull();expect(()=>tourismYear(NaN)).toThrow()});
 it('exports missing values as blank and identifies statistical units and sources',()=>{const csv=tourismCsv(2026);expect(csv).toContain('"person_nights"');expect(csv).toContain('"net_bedroom_occupancy_percent"');expect(csv).toContain('"2026-07";"";"";"";');expect(csv).toContain('accomunit=BEDRM');expect(csv).toContain('"2026-06";"172461";"100244";"40.92"')});
});
